from django.urls import path
from .views import (
    LookupLateralityListView, LookupICDCodeListView, LookupFMACodeListView,
    LookupPresentationListView, LookupOutcomeTypeListView, LookupLesionTypeListView,
    LookupResponseTypeListView, LookupProteinListView, LookupGeneListView,
    LookupTreatmentIntentListView, LookupTreatmentSequenceListView, LookupSystemicAgentListView,
    LookupVolumeUnitsListView, LookupSizeUnitsListView, LookupDoseUnitsListView,
    LookupLabResultsUnitsListView, LookupMassUnitsListView, LookupDrugRouteListView,
    LookupCTCAEGradeListView, LookupOutcomeListView, LookupStagingSystemListView,
    LookupAJCCStagePrefixListView, LookupAJCCStageSuffixListView,
    LookupAJCCTStageDescriptorListView, LookupAJCCNStageDescriptorListView,
    LookupAJCCMStageDescriptorListView, LookupStageDescriptorListView,
    LookupDiagnosticModalityListView, LookupSystemicTherapyTypeListView,
    LookupRadiotherapyVolumeTypeListView, LookupPathologyListView, LookupGradeListView,
    LookupPathologyDescriptorsListView, LookupMajorCancerCategoryListView,
    LookupRadiotherapyModalityListView, LookupRadiotherapyTypeListView,
    LookupRadiotherapyTechniqueListView, LookupClinicalSignificanceListView,
    LookupIHCResultListView, LookupIHCStainingIntensityListView, LookupMarginStatusListView,
    LookupTreatmentEffectListView, LookupStagingTypeListView, LookupSystemicTherapyRegimenListView,
    LookupRTLocationListView, LookupLaboratoryTestListView, LookupSymptomsListView,
    LookupSeverityListView, LookupIHCAntibodyListView, LookupComorbidityListView,
    LookupPerformanceStatusListView, LookupExpressionUnitsListView,
    LookupCytogeneticAbnormalityListView, LookupEpigeneticAbnormalityTypeListView,
    LookupSurgicalProceduresListView, LookupNodalAssessmentTypeListView
)

app_name = 'lookup'

urlpatterns = [
    path('laterality/', LookupLateralityListView.as_view(), name='laterality-list'),
    path('icd-code/', LookupICDCodeListView.as_view(), name='icd-code-list'),
    path('fma-code/', LookupFMACodeListView.as_view(), name='fma-code-list'),
    path('presentation/', LookupPresentationListView.as_view(), name='presentation-list'),
    path('outcome-type/', LookupOutcomeTypeListView.as_view(), name='outcome-type-list'),
    path('lesion-type/', LookupLesionTypeListView.as_view(), name='lesion-type-list'),
    path('response-type/', LookupResponseTypeListView.as_view(), name='response-type-list'),
    path('protein/', LookupProteinListView.as_view(), name='protein-list'),
    path('gene/', LookupGeneListView.as_view(), name='gene-list'),
    path('treatment-intent/', LookupTreatmentIntentListView.as_view(), name='treatment-intent-list'),
    path('treatment-sequence/', LookupTreatmentSequenceListView.as_view(), name='treatment-sequence-list'),
    path('systemic-agent/', LookupSystemicAgentListView.as_view(), name='systemic-agent-list'),
    path('volume-units/', LookupVolumeUnitsListView.as_view(), name='volume-units-list'),
    path('size-units/', LookupSizeUnitsListView.as_view(), name='size-units-list'),
    path('dose-units/', LookupDoseUnitsListView.as_view(), name='dose-units-list'),
    path('lab-results-units/', LookupLabResultsUnitsListView.as_view(), name='lab-results-units-list'),
    path('mass-units/', LookupMassUnitsListView.as_view(), name='mass-units-list'),
    path('drug-route/', LookupDrugRouteListView.as_view(), name='drug-route-list'),
    path('ctcae-grade/', LookupCTCAEGradeListView.as_view(), name='ctcae-grade-list'),
    path('outcome/', LookupOutcomeListView.as_view(), name='outcome-list'),
    path('staging-system/', LookupStagingSystemListView.as_view(), name='staging-system-list'),
    path('ajcc-stage-prefix/', LookupAJCCStagePrefixListView.as_view(), name='ajcc-stage-prefix-list'),
    path('ajcc-stage-suffix/', LookupAJCCStageSuffixListView.as_view(), name='ajcc-stage-suffix-list'),
    path('ajcc-t-stage-descriptor/', LookupAJCCTStageDescriptorListView.as_view(), name='ajcc-t-stage-descriptor-list'),
    path('ajcc-n-stage-descriptor/', LookupAJCCNStageDescriptorListView.as_view(), name='ajcc-n-stage-descriptor-list'),
    path('ajcc-m-stage-descriptor/', LookupAJCCMStageDescriptorListView.as_view(), name='ajcc-m-stage-descriptor-list'),
    path('stage-descriptor/', LookupStageDescriptorListView.as_view(), name='stage-descriptor-list'),
    path('diagnostic-modality/', LookupDiagnosticModalityListView.as_view(), name='diagnostic-modality-list'),
    path('systemic-therapy-type/', LookupSystemicTherapyTypeListView.as_view(), name='systemic-therapy-type-list'),
    path('radiotherapy-volume-type/', LookupRadiotherapyVolumeTypeListView.as_view(), name='radiotherapy-volume-type-list'),
    path('pathology/', LookupPathologyListView.as_view(), name='pathology-list'),
    path('grade/', LookupGradeListView.as_view(), name='grade-list'),
    path('pathology-descriptors/', LookupPathologyDescriptorsListView.as_view(), name='pathology-descriptors-list'),
    path('major-cancer-category/', LookupMajorCancerCategoryListView.as_view(), name='major-cancer-category-list'),
    path('radiotherapy-modality/', LookupRadiotherapyModalityListView.as_view(), name='radiotherapy-modality-list'),
    path('radiotherapy-type/', LookupRadiotherapyTypeListView.as_view(), name='radiotherapy-type-list'),
    path('radiotherapy-technique/', LookupRadiotherapyTechniqueListView.as_view(), name='radiotherapy-technique-list'),
    path('clinical-significance/', LookupClinicalSignificanceListView.as_view(), name='clinical-significance-list'),
    path('ihc-result/', LookupIHCResultListView.as_view(), name='ihc-result-list'),
    path('ihc-staining-intensity/', LookupIHCStainingIntensityListView.as_view(), name='ihc-staining-intensity-list'),
    path('margin-status/', LookupMarginStatusListView.as_view(), name='margin-status-list'),
    path('treatment-effect/', LookupTreatmentEffectListView.as_view(), name='treatment-effect-list'),
    path('staging-type/', LookupStagingTypeListView.as_view(), name='staging-type-list'),
    path('systemic-therapy-regimen/', LookupSystemicTherapyRegimenListView.as_view(), name='systemic-therapy-regimen-list'),
    path('rt-location/', LookupRTLocationListView.as_view(), name='rt-location-list'),
    path('laboratory-test/', LookupLaboratoryTestListView.as_view(), name='laboratory-test-list'),
    path('symptoms/', LookupSymptomsListView.as_view(), name='symptoms-list'),
    path('severity/', LookupSeverityListView.as_view(), name='severity-list'),
    path('ihc-antibody/', LookupIHCAntibodyListView.as_view(), name='ihc-antibody-list'),
    path('comorbidity/', LookupComorbidityListView.as_view(), name='comorbidity-list'),
    path('performance-status/', LookupPerformanceStatusListView.as_view(), name='performance-status-list'),
    path('expression-units/', LookupExpressionUnitsListView.as_view(), name='expression-units-list'),
    path('cytogenetic-abnormality/', LookupCytogeneticAbnormalityListView.as_view(), name='cytogenetic-abnormality-list'),
    path('epigenetic-abnormality-type/', LookupEpigeneticAbnormalityTypeListView.as_view(), name='epigenetic-abnormality-type-list'),
    path('surgical-procedures/', LookupSurgicalProceduresListView.as_view(), name='surgical-procedures-list'),
    path('nodal-assessment-type/', LookupNodalAssessmentTypeListView.as_view(), name='nodal-assessment-type-list'),
]
