services:
  chaviclient-database:
    image: pgvector/pgvector:pg17
    restart: always
    container_name: chaviclient-database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  chaviclient-django:
    build: .
    container_name: chaviclient-django
    restart: always
    depends_on:
      chaviclient-database:
        condition: service_healthy
    env_file:
      - .env.docker      
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./logs:/app/logs
    command: ["./entrypoint.docker.sh"]

  chaviclient-dicom:
    build: .
    container_name: chaviclient-dicom
    restart: always
    depends_on:
      chaviclient-django:
        condition: service_started
    env_file:
      - .env.docker
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    ports:
      - "11112:11112"
    command: ["python", "-m", "dicom_server"]

  chaviclient-proxy:
    image: nginx:latest
    container_name: chaviclient-proxy
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - chaviclient-django
volumes:
  postgres_data: