# Generated by Django 5.1.4 on 2025-02-09 09:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupAJCCMStageDescriptor',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupAJCCNStageDescriptor',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupAJCCStagePrefix',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupAJCCStageSuffix',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupAJCCTStageDescriptor',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupClinicalSignificance',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clinical Significance',
            },
        ),
        migrations.CreateModel(
            name='LookupComorbidity',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Comorbidity',
            },
        ),
        migrations.CreateModel(
            name='LookupCTCAEGrade',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ctcae_term', models.CharField(max_length=255)),
                ('meddra_code', models.CharField(max_length=255)),
                ('ctcae_grade', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookupCytogeneticAbnormality',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cytogenetic Abnormality',
            },
        ),
        migrations.CreateModel(
            name='LookupDiagnosticModality',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnostic Modalities',
                'db_table': 'lookup_diagnostic_modality',
            },
        ),
        migrations.CreateModel(
            name='LookupDoseUnits',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_abbreviation', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupDrugRoute',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupEpigeneticAbnormalityType',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Epigenetic Abnormality Type',
            },
        ),
        migrations.CreateModel(
            name='LookupExpressionUnits',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Expression Units',
            },
        ),
        migrations.CreateModel(
            name='LookupFMACode',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupGene',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupGrade',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Grade',
            },
        ),
        migrations.CreateModel(
            name='LookupICDCode',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icd_version', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupIHCAntibody',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHCAntibody',
            },
        ),
        migrations.CreateModel(
            name='LookupIHCResult',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC Results',
            },
        ),
        migrations.CreateModel(
            name='LookupIHCStainingIntensity',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC Staining Intensities',
            },
        ),
        migrations.CreateModel(
            name='LookupLaboratoryTest',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lookup Laboratory Tests',
            },
        ),
        migrations.CreateModel(
            name='LookupLabResultsUnits',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_abbreviation', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupLaterality',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupLesionType',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupMajorCancerCategory',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Major Cancer Category',
            },
        ),
        migrations.CreateModel(
            name='LookupMarginStatus',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Margin Status',
            },
        ),
        migrations.CreateModel(
            name='LookupMassUnits',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_abbreviation', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupOutcome',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupOutcomeType',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupPathology',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lookup Pathology',
            },
        ),
        migrations.CreateModel(
            name='LookupPathologyDescriptors',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pathology Descriptors',
            },
        ),
        migrations.CreateModel(
            name='LookupPerformanceStatus',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Performance Status',
            },
        ),
        migrations.CreateModel(
            name='LookupPresentation',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupProtein',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=500, null=True)),
                ('uniport_id', models.CharField(max_length=500, null=True)),
                ('protein_name', models.CharField(max_length=3500, null=True)),
                ('all_gene_names', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookupRadiotherapyModality',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Modality',
            },
        ),
        migrations.CreateModel(
            name='LookupRadiotherapyTechnique',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Techniques',
            },
        ),
        migrations.CreateModel(
            name='LookupRadiotherapyType',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Type',
            },
        ),
        migrations.CreateModel(
            name='LookupRadiotherapyVolumeType',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Volume Types',
            },
        ),
        migrations.CreateModel(
            name='LookupResponseType',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupRTLocation',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Anatomical Location',
            },
        ),
        migrations.CreateModel(
            name='LookupSeverity',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Severity',
            },
        ),
        migrations.CreateModel(
            name='LookupSizeUnits',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_abbreviation', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupStageDescriptor',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupStagingSystem',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staging_system_version', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupStagingType',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Staging Type',
            },
        ),
        migrations.CreateModel(
            name='LookupSymptoms',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Symptoms',
            },
        ),
        migrations.CreateModel(
            name='LookupSystemicAgent',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupSystemicTherapyRegimen',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Systemic Therapy Regimen',
            },
        ),
        migrations.CreateModel(
            name='LookupSystemicTherapyType',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Systemic Therapy Types',
                'db_table': 'lookup_systemic_therapy_type',
            },
        ),
        migrations.CreateModel(
            name='LookupTreatmentEffect',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Treatment Effect',
            },
        ),
        migrations.CreateModel(
            name='LookupTreatmentIntent',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupTreatmentSequence',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupVolumeUnits',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_abbreviation', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
