# Generated by Django 5.1.4 on 2025-01-11 16:50
import csv
from django.db import migrations
from pathlib import Path
import pandas as pd

def import_csv_data(apps, schema_editor):
    # Get the model
    LookupLaterality = apps.get_model('lookup', 'LookupLaterality')
    
    # Read CSV and create objects

    url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/d61d4f5519eb6924737bbb592195d3a82ee8710b/lookup_datasets/laterality.csv?inline=false'

    df = pd.read_csv(url)
    df = df.drop_duplicates(subset=['code'], keep='first')       
        
    # Create objects in bulk for better performance
    objects_to_create = [
        LookupLaterality(
            code=row['code'],
            label=row['label']
        ) for _, row in df.iterrows()
    ]
        
        # Bulk create all objects
    LookupLaterality.objects.bulk_create(objects_to_create)  


def reverse_migration(apps, schema_editor):
    # Get the model
    LookupLaterality = apps.get_model('lookup', 'LookupLaterality')
    # Delete all objects created by this migration
    LookupLaterality.objects.all().delete()        



class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration),        
    ]
