# Generated by Django 5.1.4 on 2025-01-12 04:21

from django.db import migrations
import pandas as pd

def import_csv_data(apps, schema_editor):
    # Get the model
    LookupOutcomeType = apps.get_model('lookup', 'LookupOutcomeType')
    
    # Read CSV and create objects
    url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/disease_outcome.csv?inline=false'

    df = pd.read_csv(url)
    df = df.drop_duplicates(subset=['code'], keep='first')        
    
    # Create objects in bulk for better performance
    objects_to_create = [
        LookupOutcomeType(
            code=row['code'],
            label=row['outcome_type']
        ) for _, row in df.iterrows()
    ]
        
        # Bulk create all objects
    LookupOutcomeType.objects.bulk_create(objects_to_create)  

def reverse_migration(apps, schema_editor):
    # Get the model
    LookupOutcomeType = apps.get_model('lookup', 'LookupOutcomeType')
    # Delete all objects created by this migration
    LookupOutcomeType.objects.all().delete()        


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0006_lookup_presentation'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration), 
    ]
