# Generated by Django 5.1.4 on 2025-01-12 04:24

from django.db import migrations
import pandas as pd

def import_csv_data(apps, schema_editor):
    # Get the model
    LookupLesionType = apps.get_model('lookup', 'LookupLesionType')
    
    # Read CSV and create objects
    url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/lesion_location_type.csv?inline=false'

    df = pd.read_csv(url)
    df = df.drop_duplicates(subset=['code'], keep='first')        
    
    # Create objects in bulk for better performance
    objects_to_create = [
        LookupLesionType(
            code=row['code'],
            label=row['lesion_location_type']
        ) for _, row in df.iterrows()
    ]
        
        # Bulk create all objects
    LookupLesionType.objects.bulk_create(objects_to_create)  

def reverse_migration(apps, schema_editor):
    # Get the model
    LookupLesionType = apps.get_model('lookup', 'LookupLesionType')
    # Delete all objects created by this migration
    LookupLesionType.objects.all().delete()        



class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0007_lookup_outcome_type'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration), 
    ]
