# Generated by Django 5.1.4 on 2025-01-12 09:10

from django.db import migrations
import pandas as pd
def import_csv_data(apps, schema_editor):
    # Get the model
    LookupSystemicTherapyType = apps.get_model('lookup', 'LookupSystemicTherapyType')
    
    try:
        
        # Read CSV and create objects
        url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/systemic_therapy_type.csv?inline=false'
        df = pd.read_csv(url) 
        df = df.drop_duplicates(subset=['code'], keep='first')        

        
        # Create objects in bulk for better performance
        objects_to_create = [
            LookupSystemicTherapyType(
                code=row['code'],
                label = row['systemic_therapy_type'] 
            ) for _, row in df.iterrows()
        ]
        
        # Bulk create all objects in smaller chunks to prevent memory issues
        batch_size = 200
        while objects_to_create:
            batch = objects_to_create[:batch_size]
            LookupSystemicTherapyType.objects.bulk_create(batch)
            objects_to_create = objects_to_create[batch_size:]
            
    except Exception as e:
        raise Exception(f"Failed to import data: {str(e)}")
def reverse_migration(apps, schema_editor):
    # Get the model
    LookupSystemicTherapyType = apps.get_model('lookup', 'LookupSystemicTherapyType')
    # Delete all objects created by this migration
    LookupSystemicTherapyType.objects.all().delete() 




class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0025_lookup_diagnostic_modality'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration),
    ]
