# Generated by Django 5.1.4 on 2025-01-26 14:23

from django.db import migrations
import pandas as pd
def import_csv_data(apps, schema_editor):
    # Get the model
    LookupIHCStainingIntensity = apps.get_model('lookup', 'LookupIHCStainingIntensity')
    
    try:
        
        # Read CSV and create objects
        url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/ihc_staining_intensity.csv?ref_type=heads&inline=false'
        df = pd.read_csv(url) 
        df = df.drop_duplicates(subset=['code'], keep='first')        

        
        # Create objects in bulk for better performance
        objects_to_create = [
            LookupIHCStainingIntensity(
                code=row['code'],
                label = row['label'] 
            ) for _, row in df.iterrows()
        ]
        
        # Bulk create all objects in smaller chunks to prevent memory issues
        batch_size = 200
        while objects_to_create:
            batch = objects_to_create[:batch_size]
            LookupIHCStainingIntensity.objects.bulk_create(batch)
            objects_to_create = objects_to_create[batch_size:]
    except Exception as e:
        raise Exception(f"Failed to import data: {str(e)}")
    
def reverse_migration(apps, schema_editor):
    # Get the model
    LookupIHCStainingIntensity = apps.get_model('lookup', 'LookupIHCStainingIntensity')
    # Delete all objects created by this migration
    LookupIHCStainingIntensity.objects.all().delete() 

class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0037_lookup_ihc_result'),
    ]

    operations = [
       migrations.RunPython(import_csv_data, reverse_code=reverse_migration),             
    ]
