# Generated by Django 5.1.4 on 2025-02-09 06:55

from django.db import migrations
import pandas as pd
def import_csv_data(apps, schema_editor):
    # Get the model
    LookupExpressionUnits = apps.get_model('lookup', 'LookupExpressionUnits')
    
    try:
        
        # Read CSV and create objects
        url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/gene_expression_units.csv?ref_type=heads&inline=false'
        df = pd.read_csv(url)

        df = df.drop_duplicates(subset=['code'], keep='first')        
        
        # Create objects in bulk for better performance
        objects_to_create = [
            LookupExpressionUnits(
                code=row['code'],
                label = row['label']
            ) for _, row in df.iterrows()
        ]
        
        # Bulk create all objects in smaller chunks to prevent memory issues
        batch_size = 200
        while objects_to_create:
            batch = objects_to_create[:batch_size]
            LookupExpressionUnits.objects.bulk_create(batch)
            objects_to_create = objects_to_create[batch_size:]
            
    except Exception as e:
        raise Exception(f"Failed to import data: {str(e)}")
    
def reverse_migration(apps, schema_editor):
    # Get the model
    LookupExpressionUnits = apps.get_model('lookup', 'LookupExpressionUnits')
    # Delete all objects created by this migration
    LookupExpressionUnits.objects.all().delete() 


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0053_lookup_performance_status'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration),
    ]
