# Generated by Django 5.1.4 on 2025-02-23 02:54

from django.db import migrations
import pandas as pd

def import_csv_data(apps, schema_editor):
    # Get the model
    LookupSurgicalProcedures = apps.get_model('lookup', 'LookupSurgicalProcedures')
    
    try:
        
        # Read CSV and create objects
        url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/lookup_surgical_procedures.csv?ref_type=heads&inline=false'
        df = pd.read_csv(url)

        df = df.drop_duplicates(subset=['code'], keep='first')        
        
        # Create objects in bulk for better performance
        objects_to_create = [
            LookupSurgicalProcedures(
                code=row['code'],
                label = row['label'],
                description = row['description'],
            ) for _, row in df.iterrows()
        ]
        
        # Bulk create all objects in smaller chunks to prevent memory issues
        batch_size = 200
        while objects_to_create:
            batch = objects_to_create[:batch_size]
            LookupSurgicalProcedures.objects.bulk_create(batch)
            objects_to_create = objects_to_create[batch_size:]
            
    except Exception as e:
        raise Exception(f"Failed to import data: {str(e)}")
    
def reverse_migration(apps, schema_editor):
    # Get the model
    LookupSurgicalProcedures = apps.get_model('lookup', 'LookupSurgicalProcedures')
    # Delete all objects created by this migration
    LookupSurgicalProcedures.objects.all().delete() 

class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0056_lookup_epigenetic_abnormality_type'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration),
    ]
