# Generated by Django 6.0.6 on 2026-08-15 18:50

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0024_alter_taskrun_task_type_dicomseries_dicominstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeidentificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PARTIAL', 'Partial Success')], default='PENDING', max_length=20)),
                ('output_path', models.CharField(blank=True, help_text='Relative path from MEDIA_ROOT to the deidentified output directory.', max_length=500, null=True)),
                ('total_file_count', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('failed_series_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('study', models.ForeignKey(help_text='The DICOM study being deidentified.', on_delete=django.db.models.deletion.CASCADE, related_name='deid_jobs', to='client_app.dicomstudy')),
                ('task_run', models.ForeignKey(blank=True, help_text='Associated Celery TaskRun for progress tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deid_jobs', to='client_app.taskrun')),
            ],
            options={
                'verbose_name': 'Deidentification Job',
                'verbose_name_plural': 'Deidentification Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeidPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deidentified_patient_id', encrypted_model_fields.fields.EncryptedCharField(help_text='Deidentified patient ID (UUID-based, encrypted at rest).')),
                ('date_shift_value', encrypted_model_fields.fields.EncryptedIntegerField(help_text='Number of days shifted for date deidentification (-100 to +100, encrypted).')),
                ('deidentified_date_of_birth', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Deidentified date of birth in YYYYMMDD format (encrypted).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(help_text='FK to the original patient record (plaintext patient_id is the PK).', on_delete=django.db.models.deletion.CASCADE, related_name='deid_record', to='client_app.patient')),
            ],
            options={
                'verbose_name': 'Deidentified Patient',
                'verbose_name_plural': 'Deidentified Patients',
            },
        ),
        migrations.CreateModel(
            name='DeidSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deidentified_series_instance_uid', encrypted_model_fields.fields.EncryptedCharField(help_text='Deidentified Series Instance UID (encrypted at rest).')),
                ('deidentified_series_date', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Deidentified series date in YYYYMMDD format (encrypted).', null=True)),
                ('deidentified_frame_of_reference_uid', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Deidentified Frame of Reference UID (encrypted at rest).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.OneToOneField(help_text='FK to the original DICOM series (plaintext series_instance_uid is the PK).', on_delete=django.db.models.deletion.CASCADE, related_name='deid_record', to='client_app.dicomseries')),
            ],
            options={
                'verbose_name': 'Deidentified Series',
                'verbose_name_plural': 'Deidentified Series',
            },
        ),
        migrations.CreateModel(
            name='DeidInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deidentified_sop_instance_uid', encrypted_model_fields.fields.EncryptedCharField(help_text='Deidentified SOP Instance UID (encrypted at rest).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.OneToOneField(help_text='FK to the original DICOM instance (plaintext sop_instance_uid is the PK).', on_delete=django.db.models.deletion.CASCADE, related_name='deid_record', to='client_app.dicominstance')),
                ('deid_series', models.ForeignKey(help_text='FK to the deidentified series record.', on_delete=django.db.models.deletion.CASCADE, related_name='deid_instances', to='deidentification.deidseries')),
            ],
            options={
                'verbose_name': 'Deidentified Instance',
                'verbose_name_plural': 'Deidentified Instances',
            },
        ),
        migrations.CreateModel(
            name='DeidStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deidentified_study_instance_uid', encrypted_model_fields.fields.EncryptedCharField(help_text='Deidentified Study Instance UID (encrypted at rest).')),
                ('deidentified_study_date', encrypted_model_fields.fields.EncryptedCharField(help_text='Deidentified study date in YYYYMMDD format (encrypted).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deid_patient', models.ForeignKey(help_text='FK to the deidentified patient record.', on_delete=django.db.models.deletion.CASCADE, related_name='deid_studies', to='deidentification.deidpatient')),
                ('study', models.OneToOneField(help_text='FK to the original DICOM study (plaintext study_instance_uid is the PK).', on_delete=django.db.models.deletion.CASCADE, related_name='deid_record', to='client_app.dicomstudy')),
            ],
            options={
                'verbose_name': 'Deidentified Study',
                'verbose_name_plural': 'Deidentified Studies',
            },
        ),
        migrations.AddField(
            model_name='deidseries',
            name='deid_study',
            field=models.ForeignKey(help_text='FK to the deidentified study record.', on_delete=django.db.models.deletion.CASCADE, related_name='deid_series', to='deidentification.deidstudy'),
        ),
        migrations.CreateModel(
            name='PixelRedactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the deidentified file.', max_length=500)),
                ('bboxes', models.JSONField(help_text='Bounding box coordinates of redacted regions, stored as JSON.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(help_text='The deidentification job this log belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='pixel_redaction_logs', to='deidentification.deidentificationjob')),
            ],
            options={
                'verbose_name': 'Pixel Redaction Log',
                'verbose_name_plural': 'Pixel Redaction Logs',
            },
        ),
    ]
