# Generated by Django 6.0.6 on 2026-06-08 02:37

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0021_bulkdicomuploadsession_bulkdicomstudymatch'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_model_name', models.CharField(help_text='Name of the LLM model to use', max_length=100)),
                ('model_provider', models.CharField(help_text='Provider of the LLM model', max_length=100)),
                ('model_api_key', encrypted_model_fields.fields.EncryptedCharField(help_text='API key for the LLM model')),
                ('model_api_key_expires', models.BooleanField(default=False, help_text='Whether the API key expires')),
                ('model_api_key_validity', models.DateTimeField(blank=True, help_text='Validity date of the API key', null=True)),
                ('model_api_refresh_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Refresh key for the API key', null=True)),
                ('model_base_url', models.CharField(max_length=255, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientapp_table_pk_field_name', models.CharField(help_text='This is the name of field which has the primary key for the table.', max_length=512)),
                ('clientapp_table_fk_fields', models.JSONField(blank=True, help_text='This a JSON representation of the FK field relationships for the table. It stores the FK relationship between the table and the patient table. Note that the FK relationship can traverse multiple intermediate tables. However the Patient table is the primary table.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clientapp_content_type', models.ForeignKey(help_text='The client_app model to which this table refers', limit_choices_to={'app_label': 'client_app'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Entity Table (Database Table)',
                'verbose_name_plural': 'Entity Tables (Database Tables)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientapp_field_name', models.CharField(help_text='Select the client app Field which is to be extracted', max_length=512)),
                ('field_type', models.CharField(choices=[('str', 'string'), ('bool', 'boolean'), ('float', 'float'), ('int', 'integer'), ('dict', 'dict'), ('tuple', 'tuple'), ('list', 'list'), ('datetime.date', 'date'), ('datetime.datetime', 'datetime'), ('datetime.timedelta', 'timedelta'), ('datetime.time', 'time')], help_text='Select the type of Field value which is stored in the database', max_length=512)),
                ('field_validation', models.JSONField(blank=True, help_text='This field will store any additional validation that has been defined for the CHAVI field. This would be converted to pydantic format and used for validating the model output.', null=True)),
                ('lookup_field', models.BooleanField(default=False, help_text='The client app database has an extensive number of fields which are linked to lookup tables. These fields need to be extracted with the lookup table data being provided as an enumerated list or a related table in the instructor extraction system.')),
                ('lookup_table_value_field_name', models.CharField(blank=True, help_text='The field containing the value which is to be matched / extracted using Instructor', max_length=512, null=True)),
                ('lookup_table_pk_field_name', models.CharField(blank=True, help_text='The field containing the primary key to which the data will be linked', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lookup_content_type', models.ForeignKey(blank=True, help_text='The lookup table to which this field is linked', limit_choices_to={'app_label': 'lookup'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('clientapp_database_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.databasetable')),
            ],
            options={
                'verbose_name': 'Database Table Field',
                'verbose_name_plural': 'Database Table Fields',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_file_chunked', models.BooleanField(default=False, help_text='Whether the processed file has been chunked')),
                ('extraction_start_datetime', models.DateTimeField(blank=True, help_text='When the extraction started', null=True)),
                ('extraction_end_datetime', models.DateTimeField(blank=True, help_text='When the extraction ended', null=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('extraction_error', models.TextField(blank=True, help_text='Error message if extraction failed', null=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, help_text='Number of tokens used for extraction', null=True)),
                ('raw_llm_response', models.JSONField(blank=True, help_text='Raw LLM response as JSON. To be stored in database only for debugging', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracted_by', models.ForeignKey(help_text='User who performed the extraction', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_data', encrypted_model_fields.fields.EncryptedTextField(help_text='Extracted data after Instructor parses the text. This will be stored as an encrypted text.')),
                ('data_accuracy', models.CharField(choices=[('accurate', 'Accurate'), ('partial', 'Partial'), ('inaccurate', 'Inaccurate')], default='accurate', max_length=50)),
                ('data_edited', models.BooleanField(default=False, help_text='Whether the data was edited by the user')),
                ('edited_data', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Edited data after user edits the extracted data. This will be stored as an encrypted text.', null=True)),
                ('verification_date_time', models.DateTimeField(blank=True, help_text='Date and time when the data was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_field', models.ForeignKey(help_text='Database table field for which the data has been extracted', on_delete=django.db.models.deletion.CASCADE, to='extractor.databasefield')),
                ('extraction_job', models.ForeignKey(help_text='Extraction job for which the data has been extracted', on_delete=django.db.models.deletion.CASCADE, to='extractor.extractionjob')),
                ('verified_by', models.ForeignKey(help_text='User who verified the data', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'csv', 'xlsx'])])),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel')], max_length=100)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(blank=True, help_text='Please select the patient for whose data is being extracted.', null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.fileupload')),
                ('processed_by_user', models.ForeignKey(blank=True, help_text='The user who processed this file.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='processed_file',
            field=models.ForeignKey(help_text='The processed text from which the data has been extracted', on_delete=django.db.models.deletion.CASCADE, to='extractor.processedtext'),
        ),
        migrations.CreateModel(
            name='RecordCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_record_pk', models.CharField(help_text='The actual primary key of the created/updated record in client_app', max_length=255)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update')], default='create', help_text='Whether this was a create or update operation', max_length=20)),
                ('record_created', models.BooleanField(default=False, help_text='Whether the record operation was successful')),
                ('record_created_at', models.DateTimeField(auto_now_add=True, help_text='When the record operation was performed')),
                ('record_created_error', models.TextField(blank=True, help_text='Error message if record operation failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_table', models.ForeignKey(help_text='The table for which the record was created', on_delete=django.db.models.deletion.CASCADE, to='extractor.databasetable')),
                ('extraction_job', models.ForeignKey(help_text='Extraction job that produced this record', on_delete=django.db.models.deletion.CASCADE, to='extractor.extractionjob')),
                ('record_created_by', models.ForeignKey(help_text='User who performed the record operation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordCreationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.TextField(blank=True, help_text='Previous value before update (for update operations)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extraction_result', models.ForeignKey(help_text='The extracted field value', on_delete=django.db.models.deletion.CASCADE, to='extractor.extractionresult')),
                ('record_creation', models.ForeignKey(help_text='The record creation this field belongs to', on_delete=django.db.models.deletion.CASCADE, to='extractor.recordcreation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the response model', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client configuration used for data extraction', on_delete=django.db.models.deletion.CASCADE, to='extractor.clientconfiguration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User')], default='system', help_text='Role of the message sender. The default value is system.', max_length=10)),
                ('prompt', models.JSONField(help_text='The prompt to be used for data extraction to be passed onto Instructor. Stored as JSON in database.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_model', models.ForeignKey(help_text='Response model for which the message is defined', on_delete=django.db.models.deletion.CASCADE, to='extractor.responsemodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='response_model',
            field=models.ForeignKey(help_text='Response model for which the extraction is being performed', on_delete=django.db.models.deletion.CASCADE, to='extractor.responsemodel'),
        ),
        migrations.CreateModel(
            name='ResponseModelTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_table', models.ForeignKey(help_text='Database table for which the response model is defined', on_delete=django.db.models.deletion.CASCADE, to='extractor.databasetable')),
                ('response_model', models.ForeignKey(help_text='Response model for which the fields are defined', on_delete=django.db.models.deletion.CASCADE, to='extractor.responsemodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseModelTableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the field in the response model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(help_text='Database field for which the response model is defined', on_delete=django.db.models.deletion.CASCADE, to='extractor.databasefield')),
                ('response_model_table', models.ForeignKey(help_text='Response model table for which the fields are defined', on_delete=django.db.models.deletion.CASCADE, to='extractor.responsemodeltable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='databasetable',
            constraint=models.UniqueConstraint(fields=('clientapp_content_type',), name='unique_clientapp_content_type'),
        ),
        migrations.AddConstraint(
            model_name='databasefield',
            constraint=models.UniqueConstraint(fields=('clientapp_database_table', 'clientapp_field_name'), name='unique_entity_per_table'),
        ),
        migrations.AddConstraint(
            model_name='recordcreation',
            constraint=models.UniqueConstraint(fields=('extraction_job', 'database_table', 'created_record_pk', 'operation'), name='unique_record_operation_per_extraction'),
        ),
        migrations.AddConstraint(
            model_name='recordcreationfield',
            constraint=models.UniqueConstraint(fields=('record_creation', 'extraction_result'), name='unique_field_per_record_creation'),
        ),
        migrations.AddConstraint(
            model_name='responsemodeltable',
            constraint=models.UniqueConstraint(fields=('response_model', 'database_table'), name='unique_response_model_database_table'),
        ),
        migrations.AddConstraint(
            model_name='responsemodeltablefield',
            constraint=models.UniqueConstraint(fields=('response_model_table', 'field'), name='unique_response_model_table_field'),
        ),
    ]
