# Generated by Django 6.0.6 on 2026-06-08 10:29

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extractor', '0002_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="Name of the embedding model (e.g., 'all-MiniLM-L6-v2', 'BioBERT')", max_length=255)),
                ('model_provider', models.CharField(default='sentence-transformers', help_text="Provider: 'sentence-transformers', 'openai', 'huggingface'", max_length=100)),
                ('embedding_dimension', models.IntegerField(help_text='Dimension of the embedding vectors (e.g., 384, 768, 1536)')),
                ('api_key', models.CharField(blank=True, help_text='API key if using a cloud provider like OpenAI', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('similarity_threshold', models.FloatField(default=0.7, help_text='Minimum similarity score (0-1) for considering a match valid')),
                ('top_k_results', models.IntegerField(default=5, help_text='Number of top similar results to show to LLM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Embedding Configuration',
                'verbose_name_plural': 'Embedding Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LookupEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(help_text='Primary key of the lookup record', max_length=255)),
                ('field_name', models.CharField(help_text="Field name that was embedded (e.g., 'icd_description')", max_length=255)),
                ('text_value', models.TextField(help_text='The original text that was embedded')),
                ('embedding', pgvector.django.vector.VectorField(help_text='Vector embedding of the text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='The lookup table this embedding belongs to', limit_choices_to={'app_label': 'lookup'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('embedding_config', models.ForeignKey(help_text='Configuration used to generate this embedding', on_delete=django.db.models.deletion.CASCADE, to='extractor.embeddingconfiguration')),
            ],
            options={
                'verbose_name': 'Lookup Embedding',
                'verbose_name_plural': 'Lookup Embeddings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'field_name'], name='extractor_l_content_917ab2_idx'), models.Index(fields=['object_id'], name='extractor_l_object__b159af_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'field_name', 'embedding_config'), name='unique_lookup_embedding')],
            },
        ),
    ]
