# Generated by Django 6.0.8 on 2026-09-20 09:32

import django.core.validators
import extractor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0004_backgroundtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Filename as uploaded; stored for display only.', max_length=512),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='content_length',
            field=models.IntegerField(default=0, help_text='Length of the extracted text content in characters.'),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='is_source_alias',
            field=models.BooleanField(default=False, help_text='True when this row points at the original upload rather than a derived file.'),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='processing_warning',
            field=models.CharField(blank=True, help_text="Non-fatal processing caveat, e.g. 'no_text' or 'encoding_fallback'.", max_length=255),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='source_sheet',
            field=models.CharField(blank=True, help_text='Worksheet name when derived from an Excel workbook.', max_length=255),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='version',
            field=models.IntegerField(default=1, help_text='Processing version; increments on reprocessing.'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=extractor.models.file_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'csv', 'xlsx'])]),
        ),
    ]
