# Generated by Django 6.0.8 on 2026-09-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0005_fileupload_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructormessage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='databasefield',
            name='help_text',
            field=models.CharField(blank=True, help_text='Help text captured from the source model field; shown to the LLM at extraction time.', max_length=512),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False when the field no longer exists on the source model after re-discovery.'),
        ),
        migrations.AddField(
            model_name='instructormessage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Explicit ordering of messages; lower numbers are sent first.'),
        ),
        migrations.CreateModel(
            name='ExtractedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_index', models.PositiveIntegerField(default=0, help_text="Position of this record within the table's extracted list")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_table', models.ForeignKey(help_text='The table this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='extractor.databasetable')),
                ('extraction_job', models.ForeignKey(help_text='Extraction job that produced this record', on_delete=django.db.models.deletion.CASCADE, related_name='extracted_records', to='extractor.extractionjob')),
            ],
            options={
                'ordering': ['database_table', 'record_index'],
            },
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='record',
            field=models.ForeignKey(blank=True, help_text='The extracted record this value belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='extractor.extractedrecord'),
        ),
    ]
