# Generated by Django 6.0.8 on 2026-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0006_alter_instructormessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetable',
            name='date_validation_pairs',
            field=models.JSONField(blank=True, help_text="Pairs of (start_date_field, end_date_field) captured from the source model's date_validation_pairs; enforced on extracted records.", null=True),
        ),
    ]
