# Generated by Django 6.0.8 on 2026-09-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0007_databasetable_date_validation_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasefield',
            name='lookup_config_source',
            field=models.CharField(choices=[('auto', 'Auto-discovered'), ('manual', 'Manual')], default='auto', help_text="'auto' = schema discovery may update the lookup field choices; 'manual' = a human set them and discovery must not overwrite.", max_length=10),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='lookup_label_fields',
            field=models.JSONField(blank=True, help_text="Ordered list of lookup fields joined into the display label (e.g. ['ctcae_grade','ctcae_description'] -> 'Grade 3 — Severe'). Empty means use lookup_table_value_field_name alone.", null=True),
        ),
        migrations.AddField(
            model_name='embeddingconfiguration',
            name='base_url',
            field=models.CharField(blank=True, help_text='Base URL for OpenAI-compatible embedding endpoints (leave blank for api.openai.com)', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='embeddingconfiguration',
            name='candidate_threshold',
            field=models.FloatField(default=0.5, help_text='Minimum similarity (0-1) when picking candidate options to show the LLM — looser than match threshold'),
        ),
        migrations.AddField(
            model_name='embeddingconfiguration',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Index generation. New builds write under version+1 and only become live when the build succeeds.'),
        ),
        migrations.AddField(
            model_name='lookupembedding',
            name='index_version',
            field=models.PositiveIntegerField(default=1, help_text="Index generation this embedding belongs to; queries only use rows matching the config's live version"),
        ),
        migrations.AddField(
            model_name='lookupembedding',
            name='is_current',
            field=models.BooleanField(default=True, help_text='False when the lookup record was deleted or its text changed since the embedding was computed'),
        ),
    ]
