# Generated by Django 6.0.8 on 2026-09-20 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0008_databasefield_lookup_config_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconfiguration',
            name='context_size',
            field=models.PositiveIntegerField(default=8192, help_text='Model context window in tokens; prompts larger than this are refused rather than silently truncated'),
        ),
        migrations.AddField(
            model_name='clientconfiguration',
            name='request_timeout',
            field=models.PositiveIntegerField(default=60, help_text='Seconds to wait for a provider response before failing'),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='config_snapshot',
            field=models.JSONField(blank=True, help_text='Provider/model/schema version frozen at dispatch', null=True),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='input_content_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of the processed text this job ran on', max_length=64),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='prompt_snapshot',
            field=models.TextField(blank=True, help_text='The exact messages sent to the model (frozen at dispatch)'),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='How many instructor retries the provider call used'),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='result_state',
            field=models.CharField(choices=[('extracted', 'Extracted'), ('not_found', 'Not found'), ('unresolved', 'Unresolved lookup')], default='extracted', help_text='extracted / not_found / unresolved-lookup', max_length=20),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='revision_history',
            field=models.JSONField(blank=True, default=list, help_text='Audit trail of review actions: [{action, old, new, user, at}]'),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='is_complete',
            field=models.BooleanField(default=True, help_text='False while the model is mid-wizard (tables/fields not yet chosen); incomplete models are hidden from extraction lists'),
        ),
        migrations.AlterField(
            model_name='extractionjob',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('partial', 'Partial')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='extractionresult',
            name='data_accuracy',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('accurate', 'Accurate'), ('partial', 'Partial'), ('inaccurate', 'Inaccurate')], default='unreviewed', max_length=50),
        ),
        migrations.AlterField(
            model_name='extractionresult',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified the data', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
