# Generated by Django 6.0.8 on 2026-09-20 11:56

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0009_clientconfiguration_context_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingconfiguration',
            name='api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='API key if using a cloud provider like OpenAI', null=True),
        ),
    ]
