# Generated by Django 6.0.8 on 2026-09-20 13:13

import django.db.models.deletion
import encrypted_model_fields.fields
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extractor', '0010_alter_embeddingconfiguration_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasefield',
            name='relation_content_type',
            field=models.ForeignKey(blank=True, help_text='For non-lookup relationship fields: the model this FK points at (e.g. diagnosis for pathology.diagnosis)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractor_field_relations', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='relation_pk_field',
            field=models.CharField(blank=True, help_text='Primary key field on the related model this FK links to', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='ocr_applied',
            field=models.BooleanField(default=False, help_text="True when this version's text was produced by OCR rather than direct text extraction."),
        ),
        migrations.AddField(
            model_name='recordcreation',
            name='extracted_record',
            field=models.ForeignKey(blank=True, help_text='The extracted record that was written back', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_creations', to='extractor.extractedrecord'),
        ),
        migrations.AlterField(
            model_name='extractionjob',
            name='raw_llm_response',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Raw LLM response as a JSON string, encrypted like extracted_data. For debugging only.', null=True),
        ),
        migrations.AlterField(
            model_name='lookupembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, help_text='Vector embedding of the text'),
        ),
        migrations.AddIndex(
            model_name='lookupembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='lookupembedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
