# Generated by Django 6.0.8 on 2026-09-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0011_databasefield_relation_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetable',
            name='match_fields',
            field=models.JSONField(blank=True, help_text="Ordered key-sets for duplicate detection before write-back, e.g. [['diagnosis','diagnosis_date']]. Populated from defaults; admin-editable.", null=True),
        ),
    ]
