# Generated by Django 6.0.8 on 2026-09-20 15:17

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0012_databasetable_match_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionresult',
            name='evidence',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text="Source-text snippet where this value was found in the processed document; encrypted like extracted_data. Empty when the value couldn't be located verbatim.", null=True),
        ),
    ]
