# Generated by Django 6.0.8 on 2026-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0013_extractionresult_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconfiguration',
            name='model_max_tokens',
            field=models.PositiveIntegerField(default=4096, help_text='Maximum tokens in a single provider response'),
        ),
    ]
