# Generated by Django 6.0.8 on 2026-09-21 08:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0014_clientconfiguration_model_max_tokens'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lookupembedding',
            name='lookupembedding_hnsw',
        ),
        migrations.AlterField(
            model_name='lookupembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(help_text='Vector embedding of the text'),
        ),
    ]
