# Generated by Django 6.0.8 on 2026-09-21 08:16

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0015_remove_lookupembedding_lookupembedding_hnsw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingconfiguration',
            name='api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Provider credential: API key for OpenAI endpoints, or a Hugging Face token (hf_...) for local sentence-transformers models', null=True),
        ),
    ]
