# Generated by Django 6.0.8 on 2026-09-21 08:17

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0016_alter_embeddingconfiguration_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingconfiguration',
            name='api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Provider credential: API key for OpenAI endpoints, or a Hugging Face access token (hf_..., created at hf.co/settings/tokens) for local sentence-transformers models', null=True),
        ),
    ]
