# Generated by Django 6.0.8 on 2026-09-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0017_alter_embeddingconfiguration_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedrecord',
            name='parent_record',
            field=models.ForeignKey(blank=True, help_text='The extracted parent record this record belongs to (nested extraction)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_records', to='extractor.extractedrecord'),
        ),
        migrations.AddField(
            model_name='responsemodeltable',
            name='auto_added',
            field=models.BooleanField(default=False, help_text='True when this table was auto-included as a required ancestor of a selected table'),
        ),
    ]
