# Generated by Django 6.0.8 on 2026-09-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0018_extractedrecord_parent_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='stage_trace',
            field=models.JSONField(blank=True, default=list, help_text='Ordered stage artifacts: prompt/result entries shown on the job detail page'),
        ),
        migrations.AlterField(
            model_name='extractionjob',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('awaiting_mining', 'Awaiting approval: lookup mining'), ('awaiting_extraction', 'Awaiting approval: extraction'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('partial', 'Partial')], default='pending', max_length=50),
        ),
    ]
