# Generated by Django 6.0.8 on 2026-09-22 02:08

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0019_extractionjob_stage_trace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionReviewBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('superseded', 'Superseded'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('request_key', models.UUIDField()),
                ('source_revision', models.PositiveIntegerField(default=0)),
                ('payload_digest', models.CharField(max_length=64)),
                ('snapshot', encrypted_model_fields.fields.EncryptedTextField()),
                ('receipt', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='recordcreation',
            name='unique_record_operation_per_extraction',
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='review_revision',
            field=models.PositiveIntegerField(default=0, help_text='Incremented after each approved extraction review'),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='review_change',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted unchanged'), ('edited', 'Edited extracted value'), ('filled_missing', 'Filled missing value'), ('cleared', 'Cleared value'), ('omitted_unresolved', 'Omitted unresolved value')], default='', help_text='Type of change made by the latest approved review', max_length=30),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='source_kind',
            field=models.CharField(choices=[('llm', 'LLM extraction'), ('manual_supplement', 'Manual addition')], default='llm', help_text='Whether this value came from the LLM or was manually supplied', max_length=20),
        ),
        migrations.AlterField(
            model_name='recordcreation',
            name='operation',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('link', 'Link')], default='create', help_text='Whether this was a create or update operation', max_length=20),
        ),
        migrations.AddField(
            model_name='extractionreviewbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extraction_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extractionreviewbatch',
            name='extraction_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_batches', to='extractor.extractionjob'),
        ),
        migrations.AddField(
            model_name='extractionreviewbatch',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_extraction_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recordcreation',
            name='review_batch',
            field=models.ForeignKey(blank=True, help_text='Approved review that performed this operation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record_operations', to='extractor.extractionreviewbatch'),
        ),
        migrations.AddConstraint(
            model_name='recordcreation',
            constraint=models.UniqueConstraint(condition=models.Q(('review_batch__isnull', True)), fields=('extraction_job', 'database_table', 'created_record_pk', 'operation'), name='unique_record_operation_per_extraction'),
        ),
        migrations.AddConstraint(
            model_name='recordcreation',
            constraint=models.UniqueConstraint(condition=models.Q(('review_batch__isnull', False)), fields=('review_batch', 'extracted_record'), name='unique_record_operation_per_review'),
        ),
        migrations.AddConstraint(
            model_name='extractionreviewbatch',
            constraint=models.UniqueConstraint(fields=('extraction_job', 'prepared_by', 'request_key'), name='unique_review_request'),
        ),
        migrations.AddConstraint(
            model_name='extractionreviewbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', False), ('status', 'approved')), models.Q(models.Q(('status', 'approved'), _negated=True), ('approved_at__isnull', True)), _connector='OR'), name='review_approval_time_consistent'),
        ),
        migrations.AddConstraint(
            model_name='extractionreviewbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('receipt__isnull', False), ('status', 'approved')), models.Q(('status', 'approved'), _negated=True), _connector='OR'), name='approved_review_has_receipt'),
        ),
    ]
