# Generated by Django 6.0.8 on 2026-09-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extractor', '0021_extractionresult_inference_metadata'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lookupembedding',
            name='unique_lookup_embedding',
        ),
        migrations.AddConstraint(
            model_name='lookupembedding',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'field_name', 'embedding_config', 'index_version'), name='unique_lookup_embedding'),
        ),
    ]
