# Generated by Django 6.0.8 on 2026-09-26 07:43

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0022_remove_lookupembedding_unique_lookup_embedding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtext',
            name='deid_csv_columns_flagged',
            field=models.JSONField(blank=True, default=list, help_text='CSV headers mapped to PHI types by the column-map pass (CSV inputs only).'),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='deid_date_shift_days',
            field=encrypted_model_fields.fields.EncryptedIntegerField(blank=True, help_text='Random per-document day offset applied to DATE_TIME entities; subtracted during extraction to restore real dates.', null=True),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='deid_engine',
            field=models.CharField(blank=True, help_text="'full' (all recognizers incl. HF model) or 'degraded' (spaCy+rules only).", max_length=20),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='deid_entities',
            field=models.JSONField(blank=True, default=dict, help_text="Detected-entity counts by type, e.g. {'PERSON': 4, 'DATE_TIME': 12}."),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='deid_manual_edits',
            field=models.PositiveIntegerField(default=0, help_text='Number of manual save/redact edits applied on the review page.'),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='deid_model',
            field=models.CharField(blank=True, help_text='HF NER model used for this run (empty in degraded mode).', max_length=255),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='deid_reviewed',
            field=models.BooleanField(default=False, help_text='User has reviewed the deidentified text; required before extraction when EXTRACTOR_DEID_REQUIRE_REVIEW.'),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='deid_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='deid_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deid_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='deidentified',
            field=models.BooleanField(default=False, help_text="True when this version's content was produced by the deidentification pipeline."),
        ),
        migrations.AddField(
            model_name='processedtext',
            name='deidentified_source',
            field=models.ForeignKey(blank=True, help_text='The ProcessedText version this deidentified version was derived from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deid_derivatives', to='extractor.processedtext'),
        ),
    ]
