# Generated by Django 6.0.8 on 2026-09-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0023_processedtext_deid_csv_columns_flagged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtext',
            name='deid_map',
            field=models.JSONField(blank=True, default=list, help_text='Replacement map for review: [{tag, type, original, count}] — lets a reviewer see and restore what each tag replaced.'),
        ),
    ]
