# Generated by Django 6.0.8 on 2026-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0024_processedtext_deid_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconfiguration',
            name='context_size',
            field=models.PositiveIntegerField(default=8192, help_text="Total token budget shared by the prompt and the response. Prompts estimated larger than this are refused before the provider is called. Examples: 8192 for gemma/gpt-4o-mini class models, 32768 for gpt-oss:120b or long documents. For Ollama, this should match the server's num_ctx (OLLAMA_CONTEXT_LENGTH) — it is a budget check here, it does not change the server's window."),
        ),
        migrations.AlterField(
            model_name='clientconfiguration',
            name='model_max_tokens',
            field=models.PositiveIntegerField(default=4096, help_text="Maximum tokens in a single provider response. If extraction output is cut off mid-response ('output is incomplete due to a max_token length limit'), raise this. Reasoning models (gpt-oss, o-series, deepseek-r1) spend part of this budget on hidden thinking tokens, so use 8192-16384; non-reasoning models are usually fine at 4096."),
        ),
        migrations.AlterField(
            model_name='clientconfiguration',
            name='request_timeout',
            field=models.PositiveIntegerField(default=60, help_text='Seconds to wait for a single provider response before failing. Small chat models are fine at 60; reasoning models (gpt-oss, o-series, deepseek-r1) or large responses may need 300-600.'),
        ),
    ]
