# Generated by Django 5.2.7 on 2025-11-06 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0021_bulkdicomuploadsession_bulkdicomstudymatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImportSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('import_session_name', models.CharField(blank=True, help_text='Enter a name for this import session. Limit 255 characters', max_length=255, null=True, verbose_name='Import Session Name')),
                ('csv_file', models.FileField(help_text='Upload a CSV file to import patient data.', upload_to='import_sessions/', validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='CSV File')),
                ('import_session_step', models.CharField(choices=[('Step 1', 'Step1'), ('Step 2', 'Step2'), ('Step 3', 'Step3'), ('Step 4', 'Step4'), ('Step 5', 'Step5'), ('Step 6', 'Step6'), ('Step 7', 'Step7'), ('Step 8', 'Step8'), ('Step 9', 'Step9'), ('Step 10', 'Step10')], default='Step 1', help_text='The step of the import session.', max_length=255, verbose_name='Import Session Step')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this import session was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this import session was last updated.', verbose_name='Updated At')),
                ('project_name', models.ManyToManyField(help_text='Select the name of the Projects for which this patient data is being imported. Please note that multiple projects may be selected here.', to='client_app.project', verbose_name='Select Project(s) for the Data Import')),
            ],
            options={
                'verbose_name': 'File Import Session',
                'verbose_name_plural': 'File Import Sessions',
            },
        ),
        migrations.CreateModel(
            name='FileImportJSON',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('json_data', models.JSONField(blank=True, help_text='Enter the JSON data for the import session.', null=True, verbose_name='JSON Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this import session was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this import session was last updated.', verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_import_json', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File Import JSON',
                'verbose_name_plural': 'File Import JSONs',
            },
        ),
        migrations.CreateModel(
            name='FileDurationDateMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csv_duration_field', models.CharField(blank=True, help_text='Select the duration field (e.g. age, disease free survival, duration to relapse, etc.) from the list of fields in the csv file.', max_length=255, null=True, verbose_name='Duration Field in CSV file')),
                ('duration', models.CharField(blank=True, help_text='Enter the duration for the CSV column.', max_length=255, null=True, verbose_name='Duration')),
                ('duration_unit', models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('fortnight', 'Fortnight'), ('week', 'Week'), ('day', 'Day'), ('hour', 'Hour'), ('minute', 'Minute'), ('second', 'Second'), ('millisecond', 'Millisecond'), ('microsecond', 'Microsecond'), ('nanosecond', 'Nanosecond')], help_text='Select unit in which the duration has been specified', max_length=255, null=True, verbose_name='Duration Unit')),
                ('reference_date', models.CharField(blank=True, help_text='Select the reference date field (e.g. diagnosis date, etc.) from the list of fields in the csv file or provide your own default. Note that the default value will be used for ALL patients.', max_length=255, null=True, verbose_name='Reference Date')),
                ('reference_date_type', models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End')], help_text='Select the type of reference date (start or end)', max_length=255, null=True, verbose_name='Reference Date Type')),
                ('reference_date_format', models.CharField(blank=True, choices=[('iso_8601', 'ISO 8601'), ('ddmmyyyy', 'DDMMYYYY'), ('mmddyyyy', 'MMDDYYYY'), ('yyyymmdd', 'YYYYMMDD'), ('dmy', 'DMY'), ('mdy', 'MDY'), ('ymd', 'YMD'), ('ddmmyy', 'DDMMYY'), ('mmddyy', 'MMDDYY'), ('yymmdd', 'YYMMDD')], help_text='Select the format of the reference date', max_length=255, null=True, verbose_name='Reference Date Format')),
                ('client_app_date_field', models.CharField(blank=True, help_text='Select the date field in the client_app model to which the duration will be added.', max_length=255, null=True, verbose_name='Client App Date Field')),
                ('client_app_date_field_value', models.CharField(blank=True, help_text='The calculated value for the date field in the client_app model.This will be calculated based on the duration and the reference date.', max_length=255, null=True, verbose_name='Client App Date Field Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this import session was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this import session was last updated.', verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_duration_date_mappings', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File Duration Date Mapping',
                'verbose_name_plural': 'File Duration Date Mappings',
            },
        ),
        migrations.CreateModel(
            name='FileDateFieldMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csv_column_name', models.JSONField(blank=True, help_text='Enter the name of the CSV column to be mapped to the corresponding field in the client_app models.', null=True, verbose_name='Select the CSV Column Name')),
                ('date_format', models.CharField(blank=True, choices=[('iso_8601', 'ISO 8601'), ('ddmmyyyy', 'DDMMYYYY'), ('mmddyyyy', 'MMDDYYYY'), ('yyyymmdd', 'YYYYMMDD'), ('dmy', 'DMY'), ('mdy', 'MDY'), ('ymd', 'YMD'), ('ddmmyy', 'DDMMYY'), ('mmddyy', 'MMDDYY'), ('yymmdd', 'YYMMDD')], help_text='Enter the date format for the CSV column.', max_length=255, null=True, verbose_name='Date Format')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this import session was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this import session was last updated.', verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_date_field_mappings', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File Date Field Mapping',
                'verbose_name_plural': 'File Date Field Mappings',
            },
        ),
        migrations.CreateModel(
            name='FileColumnFieldValueMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csv_column_name', models.JSONField(blank=True, help_text='Enter the name of the CSV column to be mapped to the corresponding field in the client_app models.', null=True, verbose_name='Select the CSV Column Name')),
                ('mapped_client_app_field_name', models.JSONField(blank=True, help_text='select the client app field name which will store the value corresponding to the column', null=True)),
                ('mapped_client_app_field_value', models.JSONField(blank=True, help_text='define the client app field value which will store the value corresponding to the column', null=True)),
                ('mapped_client_app_additional_field_names', models.JSONField(blank=True, help_text='define the additional client app field names which will be created along with this data when the import is started', null=True)),
                ('mapped_client_app_additional_field_values', models.JSONField(blank=True, help_text='define the additional client app field values which will be created along with this data when the import is started', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this import session was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this import session was last updated.', verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_column_field_value_mappings', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File Column Field Value Mapping',
                'verbose_name_plural': 'File Column Field Value Mappings',
            },
        ),
        migrations.CreateModel(
            name='FieldLookupValues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csv_column_name', models.CharField(blank=True, help_text='Select the column name from the csv file.', max_length=255, null=True, verbose_name='CSV Column Name')),
                ('lookup_value', models.CharField(blank=True, help_text='Enter the lookup value for the CSV column.', max_length=255, null=True, verbose_name='Lookup Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this import session was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this import session was last updated.', verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lookup_values', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File Lookup Value',
                'verbose_name_plural': 'File Lookup Values',
            },
        ),
        migrations.CreateModel(
            name='FileImportUUIDValues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_app_model_name', models.CharField(blank=True, help_text='Select the client_app model name.', max_length=255, null=True, verbose_name='Client App Model Name')),
                ('client_app_model_pk', models.CharField(blank=True, help_text='Select the client_app model primary key name.', max_length=255, null=True, verbose_name='Client App Model Primary Key Name')),
                ('client_app_model_pk_uuid_value', models.CharField(blank=True, help_text='Enter the UUID value for the CSV column.', max_length=255, null=True, verbose_name='UUID Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this import session was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this import session was last updated.', verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_import_uuid_values', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File UUID Value',
                'verbose_name_plural': 'File UUID Values',
            },
        ),
        migrations.CreateModel(
            name='FileMappedField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csv_field_names', models.JSONField(blank=True, help_text='Select the names of the CSV fields to be mapped to the corresponding fields in the client_app models.', null=True, verbose_name='Select the Field Names in the CSV file')),
                ('mapped_client_app_field_name', models.CharField(blank=True, help_text='Enter the name of the client_app field to be mapped to the CSV field.', max_length=255, null=True, verbose_name='Select the Client App Field')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this import session was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this import session was last updated.', verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_mapped_fields', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File Mapped Field',
                'verbose_name_plural': 'File Mapped Fields',
            },
        ),
        migrations.CreateModel(
            name='FileMappedModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_app_model_name', models.JSONField(blank=True, help_text='Enter the name of the client_app models to which the data should be imported.', null=True, verbose_name='Client App Model Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this import session was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this import session was last updated.', verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_mapped_models', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File Mapped Model',
                'verbose_name_plural': 'File Mapped Models',
            },
        ),
        migrations.CreateModel(
            name='FileMissingRelations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_app_model_name', models.CharField(blank=True, help_text='Select the client_app model name.', max_length=255, null=True, verbose_name='Client App Model Name')),
                ('client_app_field_name', models.CharField(blank=True, help_text='Select the client_app field name.', max_length=255, null=True, verbose_name='Client App Field Name')),
                ('client_app_field_value', models.CharField(blank=True, help_text='Select the client_app field value.', max_length=255, null=True, verbose_name='Client App Field Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this import session was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this import session was last updated.', verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_missing_relations', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File Missing Relation',
                'verbose_name_plural': 'File Missing Relations',
            },
        ),
        migrations.CreateModel(
            name='FilePatientID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, help_text='The patient ID from the CSV file.', max_length=255, null=True, verbose_name='Patient ID')),
                ('exists_in_client_app_database', models.BooleanField(default=False, help_text='The patient ID exists in the client_app database.', verbose_name='Exists in Client App Database')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this import session was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this import session was last updated.', verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_patient_ids', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File Patient ID',
                'verbose_name_plural': 'File Patient IDs',
            },
        ),
    ]
