# Generated by Django 5.2.7 on 2025-11-03 16:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0021_bulkdicomuploadsession_bulkdicomstudymatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFieldConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_field_name', models.CharField(blank=True, help_text='The field name in the file.', max_length=255, null=True)),
                ('field_data_type', models.CharField(choices=[('String', 'String'), ('Integer', 'Integer'), ('Float', 'Float'), ('Boolean', 'Boolean'), ('Date', 'Date'), ('DateTime', 'DateTime'), ('Time', 'Time'), ('JSON', 'JSON')], help_text='The data type of the field.', max_length=50)),
                ('client_app_table_name', models.CharField(blank=True, help_text='The table name in the client_app models.', max_length=255, null=True)),
                ('client_app_field_name', models.CharField(blank=True, help_text='The field name in the client_app models.', max_length=255, null=True)),
                ('client_app_field_type', models.CharField(choices=[('Standard', 'Standard'), ('Foreign Key', 'Foreign Key'), ('Many to Many', 'Many to Many')], help_text='The type of the field in the client_app models.A standard field will be a field that is storing data in the same table. A foreign key field type is used when there is a one-to-one or one-to-many relationship. A many-to-many field type is used when there is a many-to-many relationship.', max_length=50)),
                ('client_app_lookup_table_name', models.CharField(blank=True, help_text='The lookup table name if the field in the client app has a FK relationship to the lookup app.', max_length=255, null=True)),
                ('client_app_lookup_field_name', models.CharField(blank=True, help_text='The lookup field name if the field in the client app has a FK relationship to the lookup app.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Field',
                'verbose_name_plural': 'Data Fields',
                'db_table': 'data_field',
            },
        ),
        migrations.CreateModel(
            name='FieldLookupConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_value', models.CharField(blank=True, help_text='The value of the string in the field.', max_length=255, null=True)),
                ('lookup_value', models.CharField(blank=True, help_text='The lookup value mapped to the string in the data file', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_field_configuration', models.ForeignKey(help_text='The data field to which the lookup configuration belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='field_lookup_configurations', to='data_import.datafieldconfiguration')),
            ],
            options={
                'verbose_name': 'Field Lookup Configuration',
                'verbose_name_plural': 'Field Lookup Configurations',
                'db_table': 'field_lookup_configuration',
            },
        ),
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('JSON', 'JSON'), ('CSV', 'CSV')], help_text='The type of file to be imported.', max_length=10)),
                ('file', models.FileField(blank=True, help_text='The file to be imported.', null=True, upload_to='import_data/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json', 'csv'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ManyToManyField(help_text='The project(s) to which the data belongs.', to='client_app.project')),
            ],
            options={
                'verbose_name': 'Import Data',
                'verbose_name_plural': 'Import Data',
                'db_table': 'import_data',
            },
        ),
        migrations.AddField(
            model_name='datafieldconfiguration',
            name='import_data',
            field=models.ForeignKey(help_text='The import data to which the field belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='data_fields', to='data_import.importdata'),
        ),
        migrations.CreateModel(
            name='UUIDMappings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_app_table_name', models.CharField(blank=True, help_text='The table name in the client_app models.', max_length=255, null=True)),
                ('client_app_primary_key_name', models.CharField(blank=True, help_text='The primary key name in the client_app models.', max_length=255, null=True)),
                ('client_app_primary_key_value', models.CharField(blank=True, help_text='The primary key value in the client_app models.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_field_configuration_fields', models.ManyToManyField(help_text='The combination of fields in the data file that are used to create or link the existing UUID in the client_app models.', related_name='data_field_configuration_fields', to='data_import.datafieldconfiguration')),
                ('import_data', models.ForeignKey(help_text='The import data to which the UUID mapping belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='uuid_mappings', to='data_import.importdata')),
            ],
            options={
                'verbose_name': 'UUID Mapping',
                'verbose_name_plural': 'UUID Mappings',
                'db_table': 'uuid_mapping',
            },
        ),
    ]
