# Generated by Django 5.2.7 on 2025-11-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimportsession',
            name='data_imported',
            field=models.BooleanField(default=False, help_text='Indicates if data has been successfully imported'),
        ),
        migrations.AddField(
            model_name='fileimportsession',
            name='uuids_generated',
            field=models.BooleanField(default=False, help_text='Indicates if UUIDs have been generated for this session'),
        ),
    ]
