# Generated by Django 5.2.7 on 2025-11-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0021_bulkdicomuploadsession_bulkdicomstudymatch'),
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importdata',
            options={'ordering': ['-created_at'], 'verbose_name': 'Import Data', 'verbose_name_plural': 'Import Data'},
        ),
        migrations.AddField(
            model_name='importdata',
            name='error_log',
            field=models.TextField(blank=True, help_text='Detailed error log if import fails.', null=True),
        ),
        migrations.AddField(
            model_name='importdata',
            name='import_summary',
            field=models.JSONField(blank=True, help_text='Summary of the import process including statistics and results (JSON format).', null=True),
        ),
        migrations.AddField(
            model_name='importdata',
            name='processed_rows',
            field=models.PositiveIntegerField(default=0, help_text='Number of rows successfully processed.'),
        ),
        migrations.AddField(
            model_name='importdata',
            name='row_count',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of rows in the imported file.', null=True),
        ),
        migrations.AddField(
            model_name='importdata',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('field_mapping', 'Field Mapping'), ('validating', 'Validating'), ('lookup_matching', 'Lookup Matching'), ('uuid_mapping', 'UUID Mapping'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', help_text='Current status of the import process.', max_length=20),
        ),
        migrations.AddField(
            model_name='importdata',
            name='validation_errors',
            field=models.JSONField(blank=True, help_text='Validation errors encountered during import (JSON format).', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fieldlookupconfiguration',
            unique_together={('data_field_configuration', 'field_value')},
        ),
        migrations.AlterUniqueTogether(
            name='uuidmappings',
            unique_together={('import_data', 'client_app_table_name', 'client_app_primary_key_value')},
        ),
        migrations.AddIndex(
            model_name='datafieldconfiguration',
            index=models.Index(fields=['import_data', 'file_field_name'], name='data_field_import__f766d8_idx'),
        ),
        migrations.AddIndex(
            model_name='datafieldconfiguration',
            index=models.Index(fields=['client_app_table_name', 'client_app_field_name'], name='data_field_client__5a33ed_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldlookupconfiguration',
            index=models.Index(fields=['data_field_configuration', 'field_value'], name='field_looku_data_fi_668538_idx'),
        ),
        migrations.AddIndex(
            model_name='importdata',
            index=models.Index(fields=['status', '-created_at'], name='import_data_status_7f2165_idx'),
        ),
        migrations.AddIndex(
            model_name='importdata',
            index=models.Index(fields=['data_type', 'status'], name='import_data_data_ty_1a986a_idx'),
        ),
        migrations.AddIndex(
            model_name='uuidmappings',
            index=models.Index(fields=['import_data', 'client_app_table_name'], name='uuid_mappin_import__477780_idx'),
        ),
        migrations.AddIndex(
            model_name='uuidmappings',
            index=models.Index(fields=['client_app_primary_key_value'], name='uuid_mappin_client__c56ae1_idx'),
        ),
    ]
