# Generated by Django 5.2.7 on 2025-11-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_fileimportsession_data_imported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimportsession',
            name='patient_id_column',
            field=models.CharField(blank=True, help_text='The CSV column name used for patient ID', max_length=255, null=True, verbose_name='Patient ID Column'),
        ),
    ]
