# Generated by Django 5.2.7 on 2025-11-05 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_alter_importdata_options_importdata_error_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdata',
            name='data_format_type',
            field=models.CharField(blank=True, choices=[('Single Instance Per Patient', 'Single Instance Per Patient'), ('Multiple Instances Per Patient', 'Multiple Instances or Repeating Instances Per Patient')], default='Single Instance Per Patient', help_text='The format of the data in the file.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ImportDateFormatConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_format', models.CharField(blank=True, choices=[('YearMonthDay', 'YearMonthDay'), ('MonthDayYear', 'MonthDayYear'), ('DayMonthYear', 'DayMonthYear')], help_text='The date format of the date in the data file.', max_length=255, null=True)),
                ('date_separator', models.CharField(blank=True, choices=[('Hyphen', 'Hyphen (-)'), ('ForwardSlash', 'ForwardSlash (/)'), ('Dash', 'Dash (-)'), ('Space', 'Space ( )'), ('Comma', 'Comma (,)'), ('Dot', 'Dot (.)')], help_text='The separator used in the date in the data file.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_field_configuration', models.ForeignKey(help_text='The data field to which the date format configuration belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='date_format_configurations', to='data_import.datafieldconfiguration')),
            ],
            options={
                'verbose_name': 'Date Format Configuration',
                'verbose_name_plural': 'Date Format Configurations',
            },
        ),
        migrations.CreateModel(
            name='ImportDateIntervalFieldConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interval_field', models.CharField(blank=True, help_text='The interval field in the data file.', max_length=255, null=True)),
                ('calculation_date', models.CharField(blank=True, help_text='The date used for calculating the other date from the interval provided in the file. This can be a field in th data file or a user provided date.', max_length=255, null=True)),
                ('calculation_date_type', models.CharField(choices=[('Start Date', 'Start Date'), ('End Date', 'End Date')], help_text='The type of the calculation date. If start date then then the interval will be added to the start date to get the end date. If end date then the interval will be subtracted from the end date to get the start date.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_data', models.ForeignKey(help_text='The import data to which the date interval field configuration belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='date_interval_field_configurations', to='data_import.importdata')),
            ],
            options={
                'verbose_name': 'Date Interval Field Configuration',
                'verbose_name_plural': 'Date Interval Field Configurations',
            },
        ),
    ]
