# Generated by Django 5.2.7 on 2025-11-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_fileimportsession_patient_id_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldlookupvalues',
            name='csv_value',
            field=models.CharField(blank=True, help_text='The value in the CSV that needs to be mapped.', max_length=255, null=True, verbose_name='CSV Value'),
        ),
        migrations.AlterField(
            model_name='fieldlookupvalues',
            name='lookup_value',
            field=models.CharField(blank=True, help_text='Enter the lookup code for the CSV value.', max_length=255, null=True, verbose_name='Lookup Code'),
        ),
        migrations.AlterField(
            model_name='fileimportsession',
            name='import_session_step',
            field=models.CharField(choices=[('upload_csv', 'Upload'), ('patient_id_mapping', 'Patient Id'), ('model_selection', 'Model Selection'), ('field_mapping', 'Field Mapping'), ('column_value_mapping', 'Column Value'), ('date_format', 'Date Format'), ('duration_date', 'Duration Date'), ('lookup_mapping', 'Lookup Mapping'), ('missing_relations', 'Missing Relations'), ('review', 'Review'), ('execute_import', 'Execute')], default='upload_csv', help_text='The step of the import session.', max_length=255, verbose_name='Import Session Step'),
        ),
    ]
