# Generated by Django 5.2.7 on 2025-11-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_importdata_data_format_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdata',
            name='import_data_title',
            field=models.CharField(blank=True, help_text='The title of the import data.', max_length=255, null=True),
        ),
    ]
