# Generated by Django 5.2.7 on 2025-11-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0004_importdata_import_data_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdateintervalfieldconfiguration',
            name='interval_units',
            field=models.CharField(blank=True, choices=[('Seconds', 'Seconds'), ('Minutes', 'Minutes'), ('Hour', 'Hour'), ('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], help_text='The units of the interval.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('field_mapping', 'Field Mapping'), ('date_format_config', 'Date Format Configuration'), ('date_interval_config', 'Date Interval Configuration'), ('validating', 'Validating'), ('lookup_matching', 'Lookup Matching'), ('uuid_mapping', 'UUID Mapping'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', help_text='Current status of the import process.', max_length=20),
        ),
        migrations.AlterField(
            model_name='importdateintervalfieldconfiguration',
            name='calculation_date_type',
            field=models.CharField(blank=True, choices=[('Start Date', 'Start Date'), ('End Date', 'End Date')], help_text='The type of the calculation date. If start date then then the interval will be added to the start date to get the end date. If end date then the interval will be subtracted from the end date to get the start date.', max_length=50, null=True),
        ),
    ]
