# Generated by Django 5.2.7 on 2025-11-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0004_fieldlookupvalues_csv_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimportsession',
            name='import_session_step',
            field=models.CharField(choices=[('upload_csv', 'Upload'), ('patient_id_mapping', 'Patient Id'), ('model_selection', 'Model Selection'), ('field_mapping', 'Field Mapping'), ('column_value_mapping', 'Column Value'), ('date_format', 'Date Format'), ('duration_date', 'Duration Date'), ('lookup_mapping', 'Lookup Mapping'), ('default_values', 'Default Values'), ('missing_relations', 'Missing Relations'), ('review', 'Review'), ('execute_import', 'Execute')], default='upload_csv', help_text='The step of the import session.', max_length=255, verbose_name='Import Session Step'),
        ),
        migrations.CreateModel(
            name='FileDefaultValues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_app_model_name', models.CharField(blank=True, help_text='Select the client_app model name.', max_length=255, null=True, verbose_name='Client App Model Name')),
                ('client_app_field_name', models.CharField(blank=True, help_text='Select the client_app field name.', max_length=255, null=True, verbose_name='Client App Field Name')),
                ('client_app_field_value', models.CharField(blank=True, help_text='The default value for this field.', max_length=255, null=True, verbose_name='Default Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this was last updated.', verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_default_values', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File Default Value',
                'verbose_name_plural': 'File Default Values',
            },
        ),
    ]
