# Generated by Django 5.2.7 on 2025-11-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0005_importdateintervalfieldconfiguration_interval_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdateintervalfieldconfiguration',
            name='target_date_field',
            field=models.CharField(blank=True, help_text='The CHAVI date field (table.field) where the calculated date will be stored.', max_length=255, null=True),
        ),
    ]
