# Generated by Django 5.2.7 on 2025-11-07 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0005_alter_fileimportsession_import_session_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileParentRecordMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_model_name', models.CharField(help_text="The child model name (e.g., 'Radiotherapy')", max_length=255, verbose_name='Child Model Name')),
                ('parent_fk_field', models.CharField(help_text="The FK field name in child model (e.g., 'diagnosis')", max_length=255, verbose_name='Parent FK Field')),
                ('parent_model_name', models.CharField(help_text="The parent model name (e.g., 'Diagnosis')", max_length=255, verbose_name='Parent Model Name')),
                ('link_to_existing', models.BooleanField(default=False, help_text='If True, link to an existing parent record', verbose_name='Link to Existing')),
                ('existing_record_id', models.CharField(blank=True, help_text='UUID/ID of existing parent record to link to', max_length=255, null=True, verbose_name='Existing Record ID')),
                ('create_new_parent', models.BooleanField(default=False, help_text='If True, create a new parent record during import', verbose_name='Create New Parent')),
                ('parent_field_values', models.JSONField(blank=True, help_text='Field values for new parent record {field: value}', null=True, verbose_name='Parent Field Values')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('file_import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_parent_record_mappings', to='data_import.fileimportsession')),
            ],
            options={
                'verbose_name': 'File Parent Record Mapping',
                'verbose_name_plural': 'File Parent Record Mappings',
                'unique_together': {('file_import_session', 'child_model_name', 'parent_fk_field')},
            },
        ),
    ]
