# Generated by Django 5.2.7 on 2025-11-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0006_importdateintervalfieldconfiguration_target_date_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticFieldMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chavi_field', models.CharField(blank=True, help_text='The CHAVI field (table.field) where the static mapping will be stored.', max_length=255, null=True)),
                ('static_value', models.CharField(blank=True, help_text='The static value to be mapped to the CHAVI field.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_data', models.ForeignKey(help_text='The import data to which the static field mapping belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='static_field_mappings', to='data_import.importdata')),
            ],
            options={
                'verbose_name': 'Static Field Mapping',
                'verbose_name_plural': 'Static Field Mappings',
            },
        ),
    ]
