# Generated by Django 5.2.7 on 2025-11-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0007_staticfieldmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDFieldConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(help_text="The table name in the client_app models (e.g., 'patient', 'diagnosis').", max_length=255)),
                ('uuid_fields', models.TextField(help_text="JSON array of field names from the file that will be used to determine uniqueness (e.g., ['patient_id', 'diagnosis_date']).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_data', models.ForeignKey(help_text='The import data to which this UUID field configuration belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='uuid_field_configurations', to='data_import.importdata')),
            ],
            options={
                'verbose_name': 'UUID Field Configuration',
                'verbose_name_plural': 'UUID Field Configurations',
                'unique_together': {('import_data', 'table_name')},
            },
        ),
    ]
