# Generated by Django 5.2.7 on 2025-11-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0008_uuidfieldconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDataJSON',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('json_data', models.JSONField(help_text='The JSON data from the data file.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_data', models.ForeignKey(help_text='The import data to which the import data json belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='import_data_json', to='data_import.importdata')),
            ],
            options={
                'verbose_name': 'Import Data JSON',
                'verbose_name_plural': 'Import Data JSONs',
            },
        ),
    ]
