# Generated by Django 5.2.7 on 2025-11-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0009_importdatajson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdata',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('field_mapping', 'Field Mapping'), ('date_format_config', 'Date Format Configuration'), ('date_interval_config', 'Date Interval Configuration'), ('validating', 'Validating'), ('lookup_matching', 'Lookup Matching'), ('static_mapping', 'Static Mapping'), ('uuid_mapping', 'UUID Mapping'), ('json_preview', 'JSON Preview'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', help_text='Current status of the import process.', max_length=20),
        ),
    ]
