# Generated by Django 5.2.7 on 2025-11-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0010_alter_importdata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDMatchConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(help_text="Table name (e.g., 'diagnosis', 'pathology')", max_length=100)),
                ('patient_id', models.CharField(help_text='Patient ID this record belongs to', max_length=255)),
                ('generated_uuid', models.CharField(help_text='UUID generated in Step 8', max_length=255)),
                ('existing_uuid', models.CharField(blank=True, help_text='Existing UUID in database (if match found)', max_length=255, null=True)),
                ('match_action', models.CharField(choices=[('use_existing', 'Use Existing UUID'), ('use_new', 'Use New UUID (Create New Record)')], default='use_new', help_text='Action to take for this record', max_length=20)),
                ('import_record_data', models.JSONField(help_text='Data from import for this record')),
                ('existing_record_data', models.JSONField(blank=True, help_text='Existing record data from database', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_data', models.ForeignKey(help_text='The import data session', on_delete=django.db.models.deletion.CASCADE, related_name='uuid_matches', to='data_import.importdata')),
            ],
            options={
                'verbose_name': 'UUID Match Configuration',
                'verbose_name_plural': 'UUID Match Configurations',
                'db_table': 'uuid_match_configuration',
                'indexes': [models.Index(fields=['import_data', 'table_name', 'patient_id'], name='uuid_match__import__3ca080_idx'), models.Index(fields=['generated_uuid'], name='uuid_match__generat_fe61ec_idx')],
                'unique_together': {('import_data', 'generated_uuid')},
            },
        ),
    ]
