# Generated by Django 6.0.8 on 2026-09-23 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0025_taskrun_client_app__created_3c93a1_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMServerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae_title', models.CharField(default='CHAVI_CLIENT', help_text="This server's AE Title (max 16 chars). Remote PACS must route C-MOVE destinations to this AE title.", max_length=16)),
                ('port', models.PositiveIntegerField(default=11112)),
                ('bind_address', models.CharField(default='0.0.0.0', help_text='Interface to listen on. Use 0.0.0.0 to accept connections on all interfaces.', max_length=64)),
                ('max_pdu', models.PositiveIntegerField(default=16382)),
                ('qr_timeout', models.PositiveIntegerField(default=30, help_text='Seconds — association/DIMSE timeout for outbound Q/R requests.')),
                ('is_enabled', models.BooleanField(default=True, help_text='When unchecked the SCP still listens but rejects inbound C-STORE requests.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DICOM Server Configuration',
            },
        ),
        migrations.CreateModel(
            name='RemoteDICOMNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name, e.g. 'Hospital PACS'", max_length=100)),
                ('ae_title', models.CharField(help_text='Called AE Title of the remote node', max_length=16)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=104)),
                ('is_active', models.BooleanField(default=True)),
                ('prefer_c_get', models.BooleanField(default=False, help_text='Use C-GET instead of C-MOVE for retrieval. Required when the remote cannot open a connection back to this server (e.g. we are behind NAT).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remote DICOM Node',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RetrievalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('study_uids', models.JSONField(blank=True, help_text='Requested Study Instance UIDs (null = all studies found for the patient)', null=True)),
                ('studies_found', models.JSONField(blank=True, help_text='Study-level C-FIND results', null=True)),
                ('instances_received', models.IntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retrieval_jobs', to='dicom_server.remotedicomnode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retrieval_jobs', to='client_app.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundDICOMInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('calling_ae_title', models.CharField(blank=True, default='', max_length=16)),
                ('called_ae_title', models.CharField(blank=True, default='', max_length=16)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=64)),
                ('dicom_patient_id', models.CharField(blank=True, default='', max_length=255)),
                ('study_instance_uid', models.CharField(blank=True, default='', max_length=128)),
                ('series_instance_uid', models.CharField(blank=True, default='', max_length=128)),
                ('sop_instance_uid', models.CharField(blank=True, default='', max_length=128)),
                ('modality', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('STORED', 'Stored'), ('REJECTED', 'Rejected')], max_length=10)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('matched_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicom_inbound_instances', to='client_app.patient')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['study_instance_uid'], name='dicom_serve_study_i_277d36_idx'), models.Index(fields=['sop_instance_uid'], name='dicom_serve_sop_ins_bdf25b_idx'), models.Index(fields=['status'], name='dicom_serve_status_631050_idx')],
            },
        ),
    ]
