# Generated by Django 6.0.8 on 2026-09-24 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0026_studytyperule_dicomstudy_study_type_source'),
        ('dicom_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedicomnode',
            name='auto_retrieve_batch_size',
            field=models.PositiveIntegerField(default=50, help_text='Number of patients processed in one batch task during the periodic sweep.'),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='auto_retrieve_day_of_month',
            field=models.CharField(default='*', max_length=20),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='auto_retrieve_day_of_week',
            field=models.CharField(default='*', max_length=20),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='auto_retrieve_enabled',
            field=models.BooleanField(default=False, help_text='When checked, Celery Beat will periodically auto-retrieve studies for consented patients from this node.'),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='auto_retrieve_hour',
            field=models.CharField(default='22', max_length=20),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='auto_retrieve_min_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minimum minutes between auto-retrieval attempts for the same patient on this node.'),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='auto_retrieve_minute',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='auto_retrieve_month_of_year',
            field=models.CharField(default='*', max_length=20),
        ),
        migrations.CreateModel(
            name='AutoRetrievalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_known_study_uids', models.JSONField(blank=True, default=list)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_retrieval_states', to='dicom_server.remotedicomnode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_retrieval_states', to='client_app.patient')),
            ],
            options={
                'verbose_name': 'Auto-retrieval state',
                'verbose_name_plural': 'Auto-retrieval states',
                'unique_together': {('patient', 'node')},
            },
        ),
        migrations.CreateModel(
            name='PatientIDAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_patient_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_aliases', to='dicom_server.remotedicomnode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_patient_aliases', to='client_app.patient')),
            ],
            options={
                'verbose_name': 'Patient ID alias',
                'verbose_name_plural': 'Patient ID aliases',
                'unique_together': {('node', 'patient'), ('node', 'remote_patient_id')},
            },
        ),
    ]
