# Generated by Django 6.0.8 on 2026-09-27 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0002_remotedicomnode_auto_retrieve_batch_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomserverconfiguration',
            name='ae_title',
            field=models.CharField(default='CHAVI_CLIENT', help_text="This server's AE Title (max 16 chars). Remote PACS must route C-MOVE destinations to this AE title.", max_length=16, validators=[django.core.validators.RegexValidator('^[A-Z0-9_\\-]{1,16}$', 'AE titles must be 1-16 characters: A-Z, 0-9, underscore or hyphen.')]),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='ae_title',
            field=models.CharField(help_text='Called AE Title of the remote node', max_length=16, validators=[django.core.validators.RegexValidator('^[A-Z0-9_\\-]{1,16}$', 'AE titles must be 1-16 characters: A-Z, 0-9, underscore or hyphen.')]),
        ),
    ]
