# Generated by Django 6.0.8 on 2026-09-29 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0029_rbac_roles'),
        ('dicom_server', '0003_alter_dicomserverconfiguration_ae_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedicomnode',
            name='patient_id_transforms',
            field=models.JSONField(blank=True, default=list, help_text='Ordered transform rules applied to the local patient ID to generate remote-ID candidates for C-FIND. Each rule: {"pattern": "<regex>", "replacement": "<replacement>"} — e.g. {"pattern": "^MR/(\\d+)/(\\d+)$", "replacement": "\\1_\\2"} turns MR/25/004771 into 25_004771.'),
        ),
        migrations.AddField(
            model_name='retrievaljob',
            name='item_results',
            field=models.JSONField(blank=True, help_text='Per-study/series outcome log: [{study_instance_uid, series_instance_uid|null, status, completed, failed, ...}]', null=True),
        ),
        migrations.AddField(
            model_name='retrievaljob',
            name='selections',
            field=models.JSONField(blank=True, help_text='[{"study_instance_uid": ..., "series_instance_uids": [...]|null, "remote_patient_id": ...}] — null series list = whole study. Takes precedence over study_uids.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='patientidalias',
            unique_together={('node', 'patient', 'remote_patient_id'), ('node', 'remote_patient_id')},
        ),
        migrations.CreateModel(
            name='RetrievalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUERYING', 'Querying remote node'), ('AWAITING_SELECTION', 'Awaiting selection'), ('RETRIEVING', 'Retrieving'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='QUERYING', max_length=20)),
                ('extra_transforms', models.JSONField(blank=True, default=list, help_text='Ad-hoc transform rules applied to this query only (same {pattern, replacement} shape as node.patient_id_transforms).')),
                ('query_group_id', models.CharField(blank=True, default='', max_length=255)),
                ('retrieve_group_id', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.JSONField(blank=True, help_text='Aggregate counts + patient lists: {total, succeeded, partial, failed, skipped, instances}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retrieval_batches', to='dicom_server.remotedicomnode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='retrievaljob',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='dicom_server.retrievalbatch'),
        ),
        migrations.CreateModel(
            name='RetrievalBatchPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_patient_ids', models.JSONField(blank=True, default=list, help_text='Remote PatientIDs actually queried for this patient.')),
                ('query_status', models.CharField(choices=[('PENDING', 'Pending'), ('QUERYING', 'Querying'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('studies', models.JSONField(blank=True, help_text='Study->series tree: [{study_instance_uid, study_date, study_description, accession_number, modalities, instances, remote_patient_id, already_local, series_error?, series: [{series_instance_uid, series_description, modality, series_number, series_date, instances}]}]', null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('selected', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='dicom_server.retrievalbatch')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_rows', to='dicom_server.retrievaljob')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retrieval_batch_rows', to='client_app.patient')),
            ],
            options={
                'ordering': ['patient_id'],
                'unique_together': {('batch', 'patient')},
            },
        ),
    ]
