# Generated by Django 6.0.8 on 2026-09-29 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0004_remotedicomnode_patient_id_transforms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomserverconfiguration',
            name='ae_title',
            field=models.CharField(default='CHAVI_CLIENT', help_text="This server's AE Title — max 16 chars, uppercase letters, digits, underscore or hyphen only (e.g. CHAVI_CLIENT). Remote PACS must route C-MOVE destinations to this AE title.", max_length=16, validators=[django.core.validators.RegexValidator('^[A-Z0-9_\\-]{1,16}$', 'AE titles must be 1-16 characters: A-Z, 0-9, underscore or hyphen.')]),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='ae_title',
            field=models.CharField(help_text='Called AE Title of the remote node — max 16 chars, UPPERCASE letters, digits, underscore or hyphen only (e.g. DICOMSRVR, not dicomsrvr).', max_length=16, validators=[django.core.validators.RegexValidator('^[A-Z0-9_\\-]{1,16}$', 'AE titles must be 1-16 characters: A-Z, 0-9, underscore or hyphen.')]),
        ),
    ]
