# Generated by Django 6.0.8 on 2026-09-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0005_alter_dicomserverconfiguration_ae_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrievalbatchpatient',
            name='studies',
            field=models.JSONField(blank=True, help_text='Study->series tree: [{study_instance_uid, study_date, study_description, accession_number, modalities, instances, remote_patient_id, already_local, series_error?, series: [{series_instance_uid, series_description, modality, series_number, series_date, accession_number, instances, rt_error?, instances_error?, rt_instances?: [{sop_instance_uid, instance_number, structure_set_label, structure_set_name, rt_plan_label, rt_plan_name, approval_status}]}]}]', null=True),
        ),
    ]
