# Generated by Django 6.0.8 on 2026-09-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0006_alter_retrievalbatchpatient_studies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrievalbatchpatient',
            name='studies',
            field=models.JSONField(blank=True, help_text='Study->series tree: [{study_instance_uid, study_date, study_description, accession_number, modalities, instances, remote_patient_id, already_local, series_error?, series: [{series_instance_uid, series_description, modality, series_number, series_date, accession_number, instances, rt_error?, instances_error?, parent_series_uids?, unresolved_refs?, rt_instances?: [{sop_instance_uid, instance_number, structure_set_label, structure_set_name, rt_plan_label, rt_plan_name, approval_status, referenced_series_uids, referenced_structure_set_uids, referenced_plan_uids}]}]}]', null=True),
        ),
    ]
