[theme]
inherit = basic
stylesheet = css/chavi.css
pygments_style = sphinx

[options]
nosidebar = false
sidebarwidth = 280
body_min_width = 360
body_max_width = 900
navigation_with_keys = False
globaltoc_collapse = false
