"""
Django settings for chavi_client project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env_path = os.path.join(BASE_DIR, '.env')
load_dotenv(env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-%zvbz3$uzi$kvpd$2@5+6-=@7&8%l4^-lp!$(s#ysd9w8)fe!#')
 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')

# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'django.contrib.contenttypes',
    'grappelli.dashboard',    
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admindocs' ,
    'django_extensions',
    'client_app',
    'django_cleanup.apps.CleanupConfig',
    'import_export',
    'allauth_ui',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.mfa',
    'widget_tweaks',
    'slippers'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.admindocs.middleware.XViewMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'chavi_client.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chavi_client.wsgi.application'

# Authentication backends for Django AllAuth
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DJANGO_DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DJANGO_DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DJANGO_DB_USER', ''),
        'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', ''),
        'HOST': os.getenv('DJANGO_DB_HOST', ''),
        'PORT': os.getenv('DJANGO_DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#STATIC_URL = 'static/'
# Static paths added for Grapelli
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Added for Django Admin Index
# https://github.com/maykinmedia/django-admin-index?tab=readme-ov-file#readme


# Add Media file root
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# X_FRAME_OPTIONS = "SAMEORIGIN"
# SILENCED_SYSTEM_CHECKS = ["security.W019"]

# JAZZMIN_SETTINGS = {
#     'site_title': "CHAVI Client Application",
#     'site_header': "CHAVI Client Application", 
#     'welcome_sign': "Welcome to CHAVI Client Application",
#     'copyright': 'Tata Medical Center',
#     'show_ui_builder': False,
#     'changeform_format': 'vertical_tabs',
#     'usermenu_links': [
#         {'name': 'Account Settings', 'url': '/accounts/', 'icon': 'fas fa-user-cog'},
#         {'model': 'auth.user'},
#     ],
#     'topmenu_links': [
#         {'name': 'Home', 'url': '/admin/', 'icon': 'fas fa-home'},
#         {'app':'auth'},
#         {'model':'client_app.Project'},
#         {'model':'client_app.SiteConfiguration'},
#         {'model':'client_app.DICOMStudy'},
#         {'model':'client_app.PatientDicomFile'},
#     ],
#     'hide_models':[
#                    'auth.user',
#                    'auth.group', 
#                    'client_app.LookupFMACode',
#                    'client_app.LookupICDCode',
#                    'client_app.LookupLaboratoryTest',
#                    'client_app.LookupSystemicAgent',
#                    'client_app.LookupCTCAEGrade',
#                    'client_app.LookupStageDescriptor',
#                    'client_app.LookupPathology',
#                    'client_app.LookupProtein',
#                    'client_app.LookupGene',
#                    'client_app.LookupTreatmentIntent',
#                    'client_app.LookupTreatmentSequence',
#                    'client_app.LookupResponseType',
#                    'client_app.LookupLesionType',
#                    'client_app.LookupOutcomeType',
#                    'client_app.SiteConfiguration',
#                    'client_app.Project',
#                    'client_app.DICOMStudy',
#                    'client_app.PatientDicomFile',
#                    'client_app.LookupSystemicAgent',
#                    'account.emailaddress',
#                    'socialaccount.socialaccount',
#                    'socialaccount.socialtoken',
#                    'socialaccount.socialapp',
#                    'mfa.authenticator'
#                 ],
#     'order_with_respect_to': ['client_app.Patient',
#                               'client_app.Comorbidity',                              
#                               'client_app.Diagnosis',
#                               'client_app.Pathology',
#                               'client_app.StageInformation',
#                               'client_app.Lesion',
#                               'client_app.LesionResponse',
#                               'client_app.StageInformation',
#                               'client_app.Surgery',
#                               'client_app.Radiotherapy',
#                               'client_app.SystemicTherapy',
#                               'client_app.ConcomitantMedications',
#                               'client_app.OtherTreatment',
#                               'client_app.AdverseEffects',
#                               'client_app.PatientOutcome',
#                               'client_app.Outcome'
                              
#                             ],
                              
# }

# JAZZMIN_UI_TWEAKS = {
#     'theme': 'cosmo',
# }

# AllAuth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/admin/'
ACCOUNT_LOGIN_METHOD = 'username_email'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_USERNAME_MIN_LENGTH = 5
ACCOUNT_USERNAME_BLACKLIST = ['administrator', 'root', 'superuser']

# Grappelli Settings

GRAPPELLI_INDEX_DASHBOARD = 'chavi_client.dashboard.CustomIndexDashboard'
GRAPPELLI_ADMIN_TITLE = 'CHAVI Client Application'
