"""
Django settings for chavi_client project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env_path = os.path.join(BASE_DIR, '.env')
load_dotenv(env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-%zvbz3$uzi$kvpd$2@5+6-=@7&8%l4^-lp!$(s#ysd9w8)fe!#')
 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')

# External API settings for lookup data
LOOKUP_API_URL = os.environ.get('LOOKUP_API_URL', '')
LOOKUP_API_KEY = os.environ.get('LOOKUP_API_KEY', '')
LOOKUP_API_TIMEOUT = int(os.environ.get('LOOKUP_API_TIMEOUT', '30'))

# Proxy settings
HTTP_PROXY = os.environ.get('HTTP_PROXY', '')
HTTPS_PROXY = os.environ.get('HTTPS_PROXY', '')
NO_PROXY = os.environ.get('NO_PROXY', '')

# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    # "unfold.contrib.guardian",  # optional, if django-guardian package is used
    # "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    # "django.contrib.admin",  # required    # 'jazzmin',
    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'lookup',
    'client_app',
    'django_cleanup.apps.CleanupConfig',
    'import_export',
    'allauth_ui',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.mfa',
    'widget_tweaks',
    'slippers'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.admindocs.middleware.XViewMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'chavi_client.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': ['slippers.templatetags.slippers',],
        },
    },
]

WSGI_APPLICATION = 'chavi_client.wsgi.application'

# Authentication backends for Django AllAuth
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DJANGO_DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DJANGO_DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DJANGO_DB_USER', ''),
        'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', ''),
        'HOST': os.getenv('DJANGO_DB_HOST', ''),
        'PORT': os.getenv('DJANGO_DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#STATIC_URL = 'static/'
# Static paths added for Grapelli
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),
]

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message} [File: {pathname}:{lineno}]',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'debug.log'),
            'formatter': 'detailed',
        },
        'dicom_import': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'dicom_import.log'),
            'formatter': 'detailed',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'client_app': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'client_app.services.bulk_dicom_data_import': {
            'handlers': ['console', 'dicom_import'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Added for Django Admin Index
# https://github.com/maykinmedia/django-admin-index?tab=readme-ov-file#readme


# Add Media file root
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# AllAuth UI Theme
ALLAUTH_UI_THEME = "sunset"


# AllAuth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/admin/'
ACCOUNT_LOGIN_METHOD = 'username_email'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_USERNAME_MIN_LENGTH = 5
ACCOUNT_USERNAME_BLACKLIST = ['administrator', 'root', 'superuser']

# Grappelli Settings

# GRAPPELLI_INDEX_DASHBOARD = 'chavi_client.dashboard.CustomIndexDashboard'
# GRAPPELLI_ADMIN_TITLE = 'CHAVI Client Application'
# GRAPPELLI_CLEAN_INPUT_TYPES = True


# Unfold Settings
UNFOLD = {
    "SITE_HEADER": "CHAVI Client",
    "SITE_SUBHEADER": "Application for harmonization of data",
    "SITE_TITLE": "CHAVI Client Application",
    "SITE_BRAND": "CHAVI Client Application",

    "SITE_DROPDOWN": [
        {
            "icon": "book",
            "title": _("Documentation"),
            "link": "/docs",
            'target': '_blank',
        },
        {
            'icon': 'public',
            'title': _("CHAVI Website"),
            'link': "https://chavi.ai",
            'target': '_blank',
        },
        {
            'icon': 'groups',
            'title': _("Users"),
            'link': reverse_lazy("admin:auth_user_changelist"),
        },
        {
            'icon': 'diversity_4',
            'title': _("Groups"),
            'link': reverse_lazy("admin:auth_group_changelist"),
        },
        {
            'icon': 'tv_options_input_settings',
            'title': _("Site Configuration"),
            'link': reverse_lazy("admin:client_app_siteconfiguration_changelist"),
        },        


    ],

    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": False,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _(""),
                "collapsible": False,
                "separator": False,
                'items': [
                    {
                        "title": _("Patient Browser"),
                        "icon": "search",
                        "link": reverse_lazy("client_app:patient_search"),
                    },
                    {
                        "title": _("Documentation"),
                        "icon": "book",
                        "link": "/docs",
                    },
                    {
                        "title": _("Site Configuration"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:client_app_siteconfiguration_changelist"),
                    },
                    {
                        "title": _("Projects"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:client_app_project_changelist"),
                    }                    
                ]
            },
          
            {
                "title": _("Patient Data"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [

                    {
                        "title": _("Patient"),
                        "icon": "people",
                        "link": reverse_lazy("admin:client_app_patient_changelist"),
                    },
                    {
                        'title': _("Symptoms"),
                        'icon': 'symptoms',
                        'link': reverse_lazy("admin:client_app_symptom_changelist"),
                    },
                    {
                        'title': _("Patient Assessments"),
                        'icon': 'vital_signs',
                        'link': reverse_lazy("admin:client_app_patientassessment_changelist"),
                    },
                    {
                        'title': _("Laboratory Results"),
                        'icon': 'experiment',
                        'link': reverse_lazy("admin:client_app_laboratoryresults_changelist"),
                    },
                    {
                        'title': _("Comorbidities"),
                        'icon': 'heart_plus',
                        'link': reverse_lazy("admin:client_app_comorbidity_changelist"),
                    },
                    {
                        'title': _("Germline Mutation Data"),
                        'icon': 'genetics',
                        'link': reverse_lazy("admin:client_app_germlinegenomicalterations_changelist"),
                    },


                                        
                ],
            },

            {
                "title": _("Cancer Diagnostic Data"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Diagnosis"),
                        "icon": "diagnosis",
                        "link": reverse_lazy("admin:client_app_diagnosis_changelist"),
                    },
                    {
                        'title': _("Stage Information"),
                        'icon': 'clinical_notes',
                        'link': reverse_lazy("admin:client_app_stageinformation_changelist"),
                    },
                    {
                        'title': _("Pathology"),
                        'icon': 'biotech',
                        'link': reverse_lazy("admin:client_app_pathology_changelist"),
                    },
                    {
                        'title': _("Lesion Characteristics"),
                        'icon': 'token',
                        'link': reverse_lazy("admin:client_app_lesion_changelist"),
                    },                                   
                                        
                ],
            },

            {
                "title": _("Treatment Data"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Surgery"),
                        "icon": "surgical",
                        "link": reverse_lazy("admin:client_app_surgery_changelist"),
                    },
                    {
                        'title': _("Radiotherapy Courses"),
                        'icon': 'orbit',
                        'link': reverse_lazy("admin:client_app_radiotherapy_changelist"),
                    },
                    {
                        'title': _("Systemic Therapy Courses"),
                        'icon': 'vaccines',
                        'link': reverse_lazy("admin:client_app_systemictherapy_changelist"),
                    },
                    {
                        'title': _("Concomitant Medications"),
                        'icon': 'pill',
                        'link': reverse_lazy("admin:client_app_concomitantmedications_changelist"),
                    },
                    {
                        'title': _("Other Treatments"),
                        'icon': 'prescriptions',
                        'link': reverse_lazy("admin:client_app_othertreatment_changelist"),
                    },
                                        
                ],
            },
            {
                "title": _("Outomes & Adverse Effects"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Patient Outcome"),
                        "icon": "skull",
                        "link": reverse_lazy("admin:client_app_patientoutcome_changelist"),
                    },
                    {
                        'title': _("Cancer Outcomes"),
                        'icon': 'monitoring',
                        'link': reverse_lazy("admin:client_app_outcome_changelist"),
                    },
                    {
                        'title': _("Lesion Response Data"),
                        'icon': 'settings_heart',
                        'link': reverse_lazy("admin:client_app_lesionresponse_changelist"),
                    },
                    {
                        'title': _("Adverse Effects"),
                        'icon': 'crisis_alert',
                        'link': reverse_lazy("admin:client_app_adverseeffects_changelist"),
                    },
                    {
                        'title': _("Patient Reported Outcomes"),
                        'icon': 'voice_selection',
                        'link': reverse_lazy("admin:client_app_patientreportedoutcome_changelist"),
                    },
                                        
                ],
            },
            {
                "title": _("DICOM Studies"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("DICOM Study Data"),
                        "icon": "demography",
                        "link": reverse_lazy("admin:client_app_dicomstudy_changelist"),
                    },
                    {
                        'title': _("DICOM File Upload (Patient-wise)"),
                        'icon': 'upload_file',
                        'link': reverse_lazy("admin:client_app_patientdicomfile_changelist"),
                    },
                    {
                        'title': _("Bulk DICOM File Upload"),
                        'icon': 'folder_zip',
                        'link': reverse_lazy("admin:client_app_bulkdicomupload_changelist"),
                    },
                    {
                        'title': _("Associate DICOM Files to Project"),
                        'icon': 'settings',
                        'link': reverse_lazy("admin:client_app_dicomstudyproject_changelist"),
                    },
                    {
                        'title': _("Unprocessed DICOM Studies"),
                        'icon': 'settings',
                        'link': reverse_lazy("admin:client_app_unprocesseddicomstudies_changelist"),
                    },
                                        
                ],
            },                           

            {
                "title": _("Lookup Data"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Lookup Data"),
                        "icon": "settings",
                        "link": "/admin/lookup/",
                    }
                ],
            },  
            {
                "title": _("Data Imports for Other Tables"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                        {
                            "title": _("Immunohistochemistry"),
                            "icon": "settings",
                            "link": reverse_lazy("admin:client_app_immunohistochemistry_changelist"),
                        },
                        {
                            "title": _("Cytogenetics"),
                            "icon": "settings",
                            "link": reverse_lazy("admin:client_app_cytogenetics_changelist"),
                        },
                        {
                            "title": _("Somatic Genomic Alterations"),
                            "icon": "settings",
                            "link": reverse_lazy("admin:client_app_somaticgenomicalterations_changelist"),
                        },
                        {
                            "title": _("Gene Expression Data"),
                            "icon": "settings",
                            "link": reverse_lazy("admin:client_app_geneexpressiondata_changelist"),
                        },
                        {
                            "title": _("Epigenetic Data"),
                            "icon": "settings",
                            "link": reverse_lazy("admin:client_app_epigeneticdata_changelist"),
                        },
                        {
                            "title": _("Systemic Therapy Schedule"),
                            "icon": "settings",
                            "link": reverse_lazy("admin:client_app_systemictherapyschedule_changelist"),
                        },                        
                        {
                            "title": _("Radiotherapy Volume"),
                            "icon": "settings",
                            "link": reverse_lazy("admin:client_app_radiotherapyvolume_changelist"),
                        },          
                        {
                            "title": _("Radiotherapy Dose Volume Data"),
                            "icon": "settings",
                            "link": reverse_lazy("admin:client_app_radiotherapydosevolumedata_changelist"),
                        },                        
                        
                ],
            },  

        ],
    },    

}


