# Generated by Django 5.1.4 on 2025-01-31 03:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMStudy',
            fields=[
                ('study_instance_uid', models.CharField(help_text='A unique identifier for this specific imaging study. This is like a serial number - no two imaging studies anywhere should have the same Study Instance UID. This helps prevent any confusion between different studies.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('study_date', models.DateField(blank=True, help_text='The date when this imaging study was performed. This is recorded as YYYY-MM-DD format (for example: 2023-12-25).', null=True)),
                ('study_description', models.CharField(blank=True, help_text='Description of the study Provided in the DICOM Data', max_length=255, null=True)),
                ('series_descriptions', models.TextField(blank=True, help_text='Description of the series in the study. This is a text field that can store multiple series descriptions, separated by commas.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'DICOM Studies',
            },
        ),
        migrations.CreateModel(
            name='LookupAJCCMStageDescriptor',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupAJCCNStageDescriptor',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupAJCCStagePrefix',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupAJCCStageSuffix',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupAJCCTStageDescriptor',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupClinicalSignificance',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clinical Significance',
            },
        ),
        migrations.CreateModel(
            name='LookupCosmic',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=500, null=True)),
                ('gene_description', models.CharField(max_length=500, null=True)),
                ('gene_aliases', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookupDiagnosticModality',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnostic Modalities',
                'db_table': 'lookup_diagnostic_modality',
            },
        ),
        migrations.CreateModel(
            name='LookupDrugRoute',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupFMACode',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupGrade',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Grade',
            },
        ),
        migrations.CreateModel(
            name='LookupICDCode',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icd_version', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupIHCResult',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC Results',
            },
        ),
        migrations.CreateModel(
            name='LookupIHCStainingIntensity',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC Staining Intensities',
            },
        ),
        migrations.CreateModel(
            name='LookupLaterality',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupLesionType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupMajorCancerCategory',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Major Cancer Category',
            },
        ),
        migrations.CreateModel(
            name='LookupMarginStatus',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Margin Status',
            },
        ),
        migrations.CreateModel(
            name='LookupOutcome',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupOutcomeType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupPathology',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pathology',
            },
        ),
        migrations.CreateModel(
            name='LookupPathologyDescriptors',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pathology Descriptors',
            },
        ),
        migrations.CreateModel(
            name='LookupPresentation',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupRadiotherapyModality',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Modality',
            },
        ),
        migrations.CreateModel(
            name='LookupRadiotherapyTechnique',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Techniques',
            },
        ),
        migrations.CreateModel(
            name='LookupRadiotherapyType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Type',
            },
        ),
        migrations.CreateModel(
            name='LookupRadiotherapyVolumeType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Volume Types',
            },
        ),
        migrations.CreateModel(
            name='LookupResponseType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupStageDescriptor',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupStagingSystem',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staging_system_version', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupStagingType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Staging Type',
            },
        ),
        migrations.CreateModel(
            name='LookupSystemicAgent',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupSystemicTherapyRegimen',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Systemic Therapy Regimen',
            },
        ),
        migrations.CreateModel(
            name='LookupSystemicTherapyType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Systemic Therapy Types',
                'db_table': 'lookup_systemic_therapy_type',
            },
        ),
        migrations.CreateModel(
            name='LookupTreatmentEffect',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Treatment Effect',
            },
        ),
        migrations.CreateModel(
            name='LookupTreatmentIntent',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupTreatmentSequence',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupUniProt',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=500, null=True)),
                ('uniport_id', models.CharField(max_length=500, null=True)),
                ('protein_name', models.CharField(max_length=3500, null=True)),
                ('all_gene_names', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookupUnits',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_abbreviation', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('chavi_consent', models.BooleanField(blank=True, default=False, help_text="Indicates whether the patient has provided consent for their data to be used in the CHAVI project. This field is required and must be set to True for the patient's data to be included in the project.", null=True)),
                ('date_chavi_consent', models.DateField(blank=True, help_text='The date when the patient provided consent for their data to be used in the CHAVI project. This field is required if chavi_consent is True.', null=True)),
                ('patient_id', models.CharField(help_text="This should be your institution's medical record number or another consistent identifier used by your center.", max_length=255, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Non-Binary', 'Non Binary')], default='Female', help_text="The patient's gender", max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="The patient's date of birth in YYYY-MM-DD format.", null=True)),
                ('date_of_registration', models.DateField(blank=True, help_text='Date of registration in hospital.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this patient record was first created in the system. This field is automatically set and cannot be modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this patient record was last updated. This field is automatically updated whenever any information in the record is modified.')),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='ProInstrument',
            fields=[
                ('chavi_pro_instrument_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pro_instrument', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PRO Instruments',
                'db_table': 'pro_instrument',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('chavi_project_id', models.CharField(help_text='A unique identifier for the project.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(blank=True, help_text="The descriptive name of the project. This should be a clear, recognizable title. Example: 'Breast Cancer Imaging Study 2023'", max_length=900, null=True)),
                ('project_abbreviation', models.CharField(blank=True, help_text='The abbreviation for the project.', max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, help_text="The date when this project officially began. Format: YYYY-MM-DD. Example: '01-01-2023'", null=True)),
                ('project_irb_approval', models.BooleanField(blank=True, help_text='Indicate whether this project has received IRB (Institutional Review Board) approval. Check the box for Yes, leave unchecked for No.', null=True)),
                ('project_irb_approval_number', models.CharField(blank=True, help_text="If IRB approval was received, enter the IRB protocol number here. This can typically be found on your IRB approval letter. Example: 'IRB-2023-123'", max_length=255, null=True)),
                ('completion_date', models.DateField(blank=True, help_text="The date when this project was or is expected to be completed. Format: YYYY-MM-DD. Example: '31-12-2024'", null=True)),
                ('description', models.TextField(blank=True, help_text="A detailed description of the project's purpose, goals, and methods. This should be comprehensive enough for others to understand what the project is about.", null=True)),
                ('license', models.CharField(blank=True, help_text="The type of license under which this project's data is shared. Example: 'MIT', 'Apache 2.0', 'CC BY 4.0'", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('chavi_center_id', models.CharField(default='Site ID. This will be provided to you at the time of installation.', max_length=255, primary_key=True, serialize=False)),
                ('center_name', models.CharField(default='Your Hospital', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('chavi_diagnosis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_date', models.DateField(blank=True, help_text='Select the data at which the diagnosis was made. This can be a date when the patient came to the hospital for the first time or when a pathological proof was obtained', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis_dicom_study', models.ManyToManyField(blank=True, help_text='Select the DICOM studies that were used to diagnose the cancer. You can select multiple studies.', to='client_app.dicomstudy')),
                ('diagnostic_modality', models.ForeignKey(blank=True, help_text='If the cancer was diagnosed with a method like cytology, biopsy etc then the modality can be entered here. Please ensure that the modality is spelled correctly.', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupdiagnosticmodality')),
                ('cancer_site', models.ForeignKey(help_text='Select the cancer site. This can be a site where the cancer was first diagnosed or a site where the cancer was recurred or metastasized.', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode')),
                ('diagnosis', models.ForeignKey(help_text='Select the diagbnosis ICD code. If the patient has multiple diagnoses then you can add another instance of the form.', on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_code', to='client_app.lookupicdcode')),
                ('cancer_side', models.ForeignKey(help_text='Select the side at which the cancer was present.', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality')),
                ('cancer_system', models.ForeignKey(help_text='Select the major cancer category', on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_major_cancer_category', to='client_app.lookupmajorcancercategory')),
                ('presentation_type', models.ForeignKey(help_text='Select the type of presentation. This can be a new presentation or a recurrence or a metastasis.', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuppresentation')),
                ('patient', models.ForeignKey(help_text='Select the patient', on_delete=django.db.models.deletion.CASCADE, to='client_app.patient')),
                ('diagnosis_project', models.ManyToManyField(blank=True, help_text='Select the project that was used to diagnose the cancer. You can select multiple projects.', to='client_app.project')),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'db_table': 'diagnosis',
            },
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('chavi_lesion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_lesion_assessed', models.DateField(blank=True, help_text='The date when this lesion was first identified or assessed by a medical professional', null=True)),
                ('lesion_size_x_axis', models.DecimalField(blank=True, decimal_places=2, help_text='The width (x-axis measurement) of the lesion in the specified unit of measurement', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('lesion_size_y_axis', models.DecimalField(blank=True, decimal_places=2, help_text='The length (y-axis measurement) of the lesion in the specified unit of measurement', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('lesion_size_z_axis', models.DecimalField(blank=True, decimal_places=2, help_text='The depth (z-axis measurement) of the lesion in the specified unit of measurement', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('lesion_volume', models.DecimalField(blank=True, decimal_places=2, help_text='The total volume of the lesion, calculated from the three-dimensional measurements', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(help_text='Select the diagnosis that this lesion is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('lesion_dicom_study', models.ManyToManyField(blank=True, help_text='Select all the DICOM Studies associated with this Lesion', related_name='lesion_dicom_study', to='client_app.dicomstudy')),
                ('lesion_site', models.ForeignKey(help_text="The anatomical location where the lesion is found (e.g., 'Left Breast', 'Right Lung')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode')),
                ('lesion_laterality', models.ForeignKey(help_text="Indicates which side of the body the lesion is on (e.g., 'Left', 'Right', 'Bilateral')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality')),
                ('lesion_type', models.ForeignKey(help_text="The type or category of the lesion (e.g., 'Primary Tumor', 'Metastatic Lesion')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplesiontype')),
                ('lesion_size_unit', models.ForeignKey(blank=True, help_text="The unit of measurement used for the lesion dimensions (e.g., 'millimeters', 'centimeters')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesion_size_unit', to='client_app.lookupunits')),
                ('lesion_volume_unit', models.ForeignKey(blank=True, help_text="The unit of measurement used for the lesion volume (e.g., 'cubic millimeters', 'cubic centimeters')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesion_volume_unit', to='client_app.lookupunits')),
            ],
            options={
                'verbose_name_plural': 'Lesions',
                'db_table': 'lesion',
            },
        ),
        migrations.CreateModel(
            name='LookupCTCAEGrade',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ctcae_term', models.CharField(max_length=255)),
                ('meddra_code', models.CharField(max_length=255)),
                ('ctcae_grade', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ctcae_term', 'ctcae_grade'), name='unique_ctcae_term_grade')],
            },
        ),
        migrations.CreateModel(
            name='AdverseEffects',
            fields=[
                ('chavi_adverse_effects_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adverse_effect_start_date', models.DateField(blank=True, help_text='Enter the date when this adverse effect was first noticed (format: YYYY-MM-DD)', null=True)),
                ('adverse_effect_end_date', models.DateField(blank=True, help_text='Enter the date when this adverse effect resolved, if applicable (format: YYYY-MM-DD)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(help_text='Select the diagnosis this adverse effect is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('ctcae_grade_lookup', models.ForeignKey(blank=True, help_text='Select the standardized CTCAE grade for this adverse effect', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupctcaegrade')),
            ],
        ),
        migrations.CreateModel(
            name='LesionResponse',
            fields=[
                ('chavi_lesion_response_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesion_response_date', models.DateField(blank=True, help_text="The date when the lesion's response to treatment was evaluated", null=True)),
                ('residual_lesion_size_x_axis', models.DecimalField(blank=True, decimal_places=2, help_text='The width (left to right measurement) of any remaining lesion after treatment', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('residual_lesion_size_y_axis', models.DecimalField(blank=True, decimal_places=2, help_text='The length (front to back measurement) of any remaining lesion after treatment', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('residual_lesion_size_z_axis', models.DecimalField(blank=True, decimal_places=2, help_text='The height (top to bottom measurement) of any remaining lesion after treatment', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('residual_lesion_volume', models.DecimalField(blank=True, decimal_places=2, help_text='The total volume (size in three dimensions) of any remaining lesion after treatment', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesion', models.ForeignKey(help_text='The specific lesion (abnormal tissue) that is being monitored for response to treatment', on_delete=django.db.models.deletion.CASCADE, to='client_app.lesion')),
                ('lesion_response_dicom_study', models.ManyToManyField(blank=True, help_text='The DICOM study associated with the lesion response', related_name='lesion_response_dicom_study', to='client_app.dicomstudy')),
                ('lesion_response', models.ForeignKey(help_text='How the lesion has responded to treatment (e.g., complete response, partial response, stable disease, etc.)', on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupresponsetype')),
            ],
            options={
                'verbose_name_plural': 'Lesion Responses',
                'db_table': 'lesion_response',
            },
        ),
        migrations.CreateModel(
            name='ConcomitantMedications',
            fields=[
                ('chavi_medication_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(help_text='Enter the name of the medication as it appears in the medical record', max_length=255)),
                ('medication_dose', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the prescribed dose of the medication (can be left blank if unknown)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date_medication_start_date', models.DateField(help_text='Enter the date when the medication was started (format: YYYY-MM-DD)')),
                ('date_medication_end_date', models.DateField(blank=True, help_text='Enter the date when the medication was stopped, if applicable (format: YYYY-MM-DD)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(help_text='Select the diagnosis that this treatment is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('medication_route', models.ForeignKey(help_text='Select how the medication was administered (e.g., oral, intravenous, etc.)', on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupdrugroute')),
                ('medication_dose_units', models.ForeignKey(blank=True, help_text='Select the units for the medication dose (e.g., mg, mL, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medication_dose_units', to='client_app.lookupunits')),
            ],
            options={
                'verbose_name_plural': 'ConcomitantMedications',
                'db_table': 'concomitant_medications',
            },
        ),
        migrations.CreateModel(
            name='OtherTreatment',
            fields=[
                ('chavi_treatment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treatment', models.CharField(help_text='Enter the name or description of the treatment', max_length=255)),
                ('treatment_start_date', models.DateField(blank=True, help_text='Start date of Treatment', null=True)),
                ('treatment_end_date', models.DateField(blank=True, help_text='End date of Treatment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this treatment record was created (automatically set)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(help_text='Select the diagnosis that this treatment is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
            ],
            options={
                'verbose_name': 'Other Treatment',
                'verbose_name_plural': 'Other Treatments',
                'db_table': 'other_treatment',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('chavi_outcome_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_outcome_assessed', models.DateField(blank=True, help_text='Date this Outcome was assessed or documented or confirmed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('outcome_dicom_study', models.ManyToManyField(blank=True, help_text='Select all DICOM Studies for this Disease Outcome', related_name='outcome_dicom_study', to='client_app.dicomstudy')),
                ('outcome_type', models.ForeignKey(help_text='Select the Type of Outcome. If you wish to add another outcome then please create another instance of the form.', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupoutcometype')),
            ],
            options={
                'verbose_name': 'Cancer Outcome',
                'verbose_name_plural': 'Cancer Outcomes',
                'db_table': 'outcome',
            },
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('chavi_pathology_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_pathology', models.DateField(blank=True, help_text='The date when the pathology specimen was collected or the pathology report was issued', null=True)),
                ('specimen_type', models.CharField(blank=True, help_text="The type of specimen collected (e.g., 'Core Biopsy', 'Surgical Resection', 'Fine Needle Aspiration')", max_length=500, null=True)),
                ('greatest_dimension_of_tumor', models.DecimalField(blank=True, decimal_places=2, help_text='The primary dimension of the tumor measured in centimeters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('additional_tumor_dimension_1', models.DecimalField(blank=True, decimal_places=2, help_text='The second dimension of the tumor measured in centimeters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('additional_tumor_dimension_2', models.DecimalField(blank=True, decimal_places=2, help_text='The third dimension of the tumor measured in centimeters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tumor_focality', models.CharField(blank=True, help_text='Whether the tumor is unifocal (single focus) or multifocal (multiple foci)', max_length=50, null=True)),
                ('necrosis_percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Percentage of necrosis in the specimen', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('mitotic_count', models.PositiveIntegerField(blank=True, help_text='Number of mitoses per 10 high power field or 2 square mm', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('closest_margin_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance to the closest margin of the specimen.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('primary_gleason_grade', models.PositiveIntegerField(blank=True, help_text='Enter the primary Gleason grade of the specimen', null=True)),
                ('secondary_gleason_grade', models.PositiveIntegerField(blank=True, help_text='Enter the secondary Gleason grade of the specimen', null=True)),
                ('lymph_nodes_removed', models.BooleanField(blank=True, help_text='Whether lymph nodes were removed in the specimen', null=True)),
                ('lymph_nodes_in_specimen', models.PositiveIntegerField(blank=True, help_text='Total number of lymph nodes found in the specimen', null=True)),
                ('number_of_uninvolved_nodes', models.PositiveIntegerField(blank=True, help_text='Number of lymph nodes without any tumor involvement', null=True)),
                ('number_of_nodes_with_macrometastases', models.PositiveIntegerField(blank=True, help_text='Number of lymph nodes with visible tumor deposits', null=True)),
                ('number_of_nodes_with_micrometastases', models.PositiveIntegerField(blank=True, help_text='Number of lymph nodes with microscopic tumor deposits (0.2-2.0mm)', null=True)),
                ('number_of_nodes_with_isolated_tumor_cells', models.PositiveIntegerField(blank=True, help_text='Number of lymph nodes with isolated tumor cells (<0.2mm)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closest_margin_distance_unit', models.ForeignKey(blank=True, help_text='Unit of measurement for the closest margin distance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_closest_margin_distance_unit', to='client_app.lookupunits')),
                ('dermal_lymphatic_vascular_invasion', models.ForeignKey(blank=True, help_text='Presence or absence of perineural invasion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_dermal_lymphatic_vascular_invasion', to='client_app.lookuppathologydescriptors')),
                ('diagnosis', models.ForeignKey(help_text='The diagnosis associated with this pathology report', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('histological_grade', models.ForeignKey(blank=True, help_text="The degree of differentiation of the tumor cells (e.g., 'Grade 1', 'Grade 2', 'Grade 3')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_histological_grade', to='client_app.lookupgrade')),
                ('histological_type', models.ForeignKey(blank=True, help_text="The primary histological classification of the tumor (e.g., 'Adenocarcinoma', 'Squamous Cell Carcinoma')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_histological_type', to='client_app.lookuppathology')),
                ('lymphatic_vascular_invasion', models.ForeignKey(blank=True, help_text='Presence or absence of perineural invasion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_lymphatic_vascular_invasion', to='client_app.lookuppathologydescriptors')),
                ('margin_status', models.ForeignKey(blank=True, help_text='Select the margin status of the specimen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_margin_status', to='client_app.lookupmarginstatus')),
                ('necrosis', models.ForeignKey(blank=True, help_text='Presence or absence of necrosis', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_necrosis', to='client_app.lookuppathologydescriptors')),
                ('perineural_invasion', models.ForeignKey(blank=True, help_text='Presence or absence of perineural invasion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_perineural_invasion', to='client_app.lookuppathologydescriptors')),
                ('treatment_effect', models.ForeignKey(blank=True, help_text='Select the treatment effect of the specimen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_treatment_effect', to='client_app.lookuptreatmenteffect')),
                ('tumor_dimesion_unit', models.ForeignKey(blank=True, help_text='The unit of measurement for the tumor dimension', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_tumor_dimesion_unit', to='client_app.lookupunits')),
                ('tumor_side', models.ForeignKey(help_text="The side of the body where the tumor is located (e.g., 'Left', 'Right', 'Bilateral')", on_delete=django.db.models.deletion.CASCADE, related_name='pathology_tumor_side', to='client_app.lookuplaterality')),
                ('tumor_site', models.ForeignKey(help_text='The anatomical location of the tumor as defined by the Foundational Model of Anatomy (FMA)', on_delete=django.db.models.deletion.CASCADE, related_name='pathology_tumor_site', to='client_app.lookupfmacode')),
            ],
            options={
                'verbose_name_plural': 'Pathology',
                'db_table': 'pathology',
            },
        ),
        migrations.CreateModel(
            name='Immunohistochemistry',
            fields=[
                ('chavi_ihc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_ihc', models.DateField(blank=True, help_text='Enter the date when the immunohistochemistry test was performed (format: YYYY-MM-DD)', null=True)),
                ('percentage_positive_tumor_cells', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the percentage of positive cells for IHC staining', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('percentage_positive_immune_cells', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the percentage of positive immune cells for IHC staining', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('allred_score', models.PositiveIntegerField(blank=True, help_text='Enter the Allred score for IHC staining', null=True)),
                ('cps_score', models.PositiveIntegerField(blank=True, help_text='Number of Tumor and Immune Cells with Staining per 100 Tumor Cells (CPS)', null=True)),
                ('tps_score', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the TPS score for IHC staining in %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ihc_result', models.ForeignKey(blank=True, help_text='Select the result of the IHC staning Test overall', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ihc_result', to='client_app.lookupihcresult')),
                ('tumor_cell_staining_intensity', models.ForeignKey(blank=True, help_text='Select the staining intensity of the cells for IHC staining', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupihcstainingintensity')),
                ('protein_name', models.ForeignKey(help_text='Select the protein that was tested for in this immunohistochemistry test', on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupuniprot')),
                ('pathology', models.ForeignKey(help_text='Select the pathology report this immunohistochemistry test is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.pathology')),
            ],
            options={
                'verbose_name_plural': 'Immunohistochemistries',
                'db_table': 'immunohistochemistry',
            },
        ),
        migrations.CreateModel(
            name='Cytogenetics',
            fields=[
                ('chavi_cytogenetics_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_cytogenetics', models.DateField(blank=True, help_text='Enter the date when the cytogenetics test was performed (format: YYYY-MM-DD)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gene', models.ForeignKey(help_text='Select the gene that was tested for in this cytogenetics test', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupcosmic')),
                ('cytogenetic_result', models.ForeignKey(blank=True, help_text='Select the result of the cytogenetics test', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cytogenetics_result', to='client_app.lookupihcresult')),
                ('pathology', models.ForeignKey(help_text='Select the pathology report this cytogenetics test is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.pathology')),
            ],
            options={
                'verbose_name_plural': 'Cytogenetics',
                'db_table': 'cytogenetics',
            },
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='patient',
            field=models.ForeignKey(help_text='Reference to the patient that this imaging study belongs to. When a patient record is deleted, all associated imaging studies will also be deleted.', on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='client_app.patient'),
        ),
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('chavi_comorbidity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_comorbidity_diagnosis', models.DateField(blank=True, help_text='Enter the date when this comorbidity was first diagnosed (format: YYYY-MM-DD)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicate whether this comorbidity is currently active (check for Yes, uncheck for No)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comorbidity_type', models.ForeignKey(help_text='Select the ICD code that best describes this comorbidity', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupicdcode')),
                ('patient', models.ForeignKey(help_text='Select the patient who has this comorbidity', on_delete=django.db.models.deletion.CASCADE, to='client_app.patient')),
            ],
            options={
                'verbose_name_plural': 'Comorbidities',
                'db_table': 'comorbidity',
            },
        ),
        migrations.CreateModel(
            name='PatientDicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Please upload a single zip file having the DICOM studies for a single patients. You can choose to upload multiple studies at the same time.', upload_to='dicom_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_dicom_files', to='client_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientOutcome',
            fields=[
                ('chavi_pt_outcome_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_death', models.DateField(blank=True, help_text='Enter the date of death, if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.patient')),
                ('patient_status', models.ForeignKey(help_text='Select the patients last known status', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupoutcome')),
                ('primary_cause_of_death', models.ForeignKey(blank=True, help_text='Select the primary cause of death, if applicable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_cause', to='client_app.lookupicdcode')),
                ('secondary_cause_of_death', models.ForeignKey(blank=True, help_text='Select the secondary cause of death, if applicable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_cause', to='client_app.lookupicdcode')),
                ('tertiary_cause_of_death', models.ForeignKey(blank=True, help_text='Select the tertiary cause of death, if applicable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tertiary_cause', to='client_app.lookupicdcode')),
            ],
            options={
                'verbose_name_plural': 'Patient Outcomes',
                'db_table': 'patient_outcome',
            },
        ),
        migrations.CreateModel(
            name='ProDomain',
            fields=[
                ('chavi_prodomain_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pro_domain', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.proinstrument')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_project',
            field=models.ManyToManyField(blank=True, help_text='The project(s) that the patient is enrolled in.', related_name='patient_project', to='client_app.project'),
        ),
        migrations.CreateModel(
            name='DICOMStudyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudy')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.project')),
            ],
            options={
                'verbose_name': 'Project for DICOM Study',
                'verbose_name_plural': 'Projects for DICOM Study',
            },
        ),
        migrations.CreateModel(
            name='ProQuestion',
            fields=[
                ('chavi_pro_question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pro_question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.prodomain')),
            ],
        ),
        migrations.CreateModel(
            name='PatientReportedOutcome',
            fields=[
                ('chavi_pro_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pro_date', models.DateField(blank=True, help_text='Enter the date when this assessment was completed (format: YYYY-MM-DD)', null=True)),
                ('pro_answer', models.TextField(blank=True, help_text="Enter the patient's response to this specific question", null=True)),
                ('pro_score', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the numerical score for this response, if applicable (e.g., on a scale of 0-10)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Select the patient who completed this patient-reported outcome assessment', on_delete=django.db.models.deletion.CASCADE, to='client_app.patient')),
                ('domain', models.ForeignKey(help_text="Select the specific domain or category of the assessment (e.g., 'Physical Function', 'Emotional Well-being')", on_delete=django.db.models.deletion.CASCADE, to='client_app.prodomain')),
                ('instrument', models.ForeignKey(help_text="Select the assessment instrument or questionnaire that was used (e.g., 'EORTC QLQ-C30', 'FACT-G')", on_delete=django.db.models.deletion.CASCADE, to='client_app.proinstrument')),
                ('question', models.ForeignKey(help_text='Select the specific question from the assessment that was answered', on_delete=django.db.models.deletion.CASCADE, to='client_app.proquestion')),
            ],
            options={
                'verbose_name_plural': 'Patient Reported Outcomes',
                'db_table': 'patient_reported_outcome',
            },
        ),
        migrations.CreateModel(
            name='Radiotherapy',
            fields=[
                ('chavi_radiotherapy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_dose', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the total radiation dose delivered during the entire course of treatment (in Gray or specified units)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_fractions', models.PositiveIntegerField(blank=True, help_text='Enter the total number of treatment sessions (fractions) planned for the complete course of radiotherapy', null=True)),
                ('fractions_per_day', models.PositiveIntegerField(blank=True, default=1, help_text='Enter the number of treatment sessions (fractions) delivered per day', null=True)),
                ('radiotherapy_machine', models.CharField(blank=True, help_text='Enter the name or model of the radiation therapy machine used', max_length=255, null=True)),
                ('radiotherapy_start_date', models.DateField(blank=True, help_text='Enter the date when the treatment was started (format: YYYY-MM-DD)', null=True)),
                ('radiotherapy_end_date', models.DateField(blank=True, help_text='Enter the date when the treatment was completed (format: YYYY-MM-DD)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(help_text='Select the diagnosis that this treatment is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('radiation_dose_units', models.ForeignKey(blank=True, help_text="Select the units used to measure the radiation dose (e.g., 'Gy', 'cGy')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiation_course_dose_units', to='client_app.lookupunits')),
                ('radiotherapy_dicom_study', models.ManyToManyField(blank=True, help_text='Select the DICOM studies associated with this radiotherapy course', related_name='radiotherapy_dicom_studies', to='client_app.dicomstudy')),
                ('radiotherapy_modality', models.ForeignKey(blank=True, help_text='Select the modality of the radiotherapy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiotherapy_modality', to='client_app.lookupradiotherapymodality')),
                ('radiotherapy_sequence', models.ForeignKey(help_text="Select the sequence of this radiotherapy in relation to other treatments (e.g., 'Primary', 'Boost', 'Concurrent')", on_delete=django.db.models.deletion.PROTECT, related_name='radiotherapy_sequence', to='client_app.lookuptreatmentsequence')),
                ('radiotherapy_side', models.ForeignKey(help_text="Select which side of the body is being treated (e.g., 'Left', 'Right', 'Bilateral')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality')),
                ('radiotherapy_site', models.ForeignKey(help_text='Select the anatomical location where the radiation is being delivered', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode')),
                ('radiotherapy_technique', models.ForeignKey(blank=True, help_text='Select the technique used to deliver the radiation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiotherapy_technique', to='client_app.lookupradiotherapytechnique')),
                ('radiotherapy_type', models.ForeignKey(blank=True, help_text='Select the type of radiotherapy treatment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiotherapy_type', to='client_app.lookupradiotherapytype')),
            ],
            options={
                'verbose_name': 'Radiotherapy Course',
                'verbose_name_plural': 'Radiotherapy Courses',
                'db_table': 'radiotherapy',
            },
        ),
        migrations.CreateModel(
            name='RadiotherapyDoseVolumeData',
            fields=[
                ('radiotherapy_dose_volume_data_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this radiotherapy dose volume data', primary_key=True, serialize=False)),
                ('volume_name', models.CharField(help_text='Enter a name for this dose volume data', max_length=255)),
                ('absolute_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the absolute volume in cubic centimeters (cc)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('relative_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the relative volume as a percentage (%). Enter a value between 0 and 100.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('absolute_dose', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the absolute dose in Gray (Gy) or cGy', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('relative_dose', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the relative dose as a percentage (%). Enter a value between 0 and 100.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('volume_dose_prescribed', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the dose prescribed to this volume in Gray (Gy) or cGy', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('radiation_dose_units', models.ForeignKey(blank=True, help_text="Select the units for the dose (e.g., 'Gy', 'cGy', '%')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiation_dose_units', to='client_app.lookupunits')),
                ('radiotherapy', models.ForeignKey(help_text='Select the radiotherapy session that this dose volume data is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.radiotherapy')),
                ('volume_type', models.ForeignKey(help_text="Select the type of volume (e.g., 'CTV', 'PTV')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupradiotherapyvolumetype')),
                ('volume_units', models.ForeignKey(blank=True, help_text="Select the units for the volume (e.g., 'cc', '%')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volume_units', to='client_app.lookupunits')),
            ],
            options={
                'verbose_name': 'Radiotherapy Dose Volume',
                'verbose_name_plural': 'Radiotherapy Dose Volumes',
                'db_table': 'radiotherapy_dose_volumes',
            },
        ),
        migrations.CreateModel(
            name='RadiotherapyVolume',
            fields=[
                ('radiotherapy_volume_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this radiotherapy dose volume data', primary_key=True, serialize=False)),
                ('volume_name', models.CharField(blank=True, help_text='Enter a name or description for this volume', max_length=255, null=True)),
                ('volume_dose_prescribed', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the prescribed dose for this volume in Gray (Gy)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('volume_fractions', models.PositiveIntegerField(blank=True, help_text='Enter the number of fractions for this volume', null=True)),
                ('volume_radiotherapy_start_date', models.DateField(blank=True, help_text='Enter the start date for this volume (format: YYYY-MM-DD)', null=True)),
                ('volume_radiotherapy_end_date', models.DateField(blank=True, help_text='Enter the end date for this volume (format: YYYY-MM-DD)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radiation_dose_units', models.ForeignKey(blank=True, help_text="Select the units used to measure the radiation dose (e.g., 'Gy', 'cGy')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiotherapy_volume_dose_units', to='client_app.lookupunits')),
                ('radiotherapy', models.ForeignKey(help_text='Select the radiotherapy course that this volume is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.radiotherapy')),
                ('volume_type', models.ForeignKey(blank=True, help_text='Select the type of volume (e.g., PTV, CTV, OAR)', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupradiotherapyvolumetype')),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Volumes',
                'db_table': 'radiotherapy_volume',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='center',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_center', to='client_app.siteconfiguration'),
        ),
        migrations.AddField(
            model_name='patient',
            name='center',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center', to='client_app.siteconfiguration'),
        ),
        migrations.CreateModel(
            name='SomaticGenomicAlterations',
            fields=[
                ('chavi_somatic_genomic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_test', models.DateField(blank=True, help_text='Enter the date when the genomic testing was performed (format: YYYY-MM-DD)', null=True)),
                ('reference_sequence', models.CharField(blank=True, help_text="Enter the reference sequence identifier (e.g., 'NM_007294.3' for BRCA1)", max_length=255, null=True)),
                ('protein_modification', models.CharField(blank=True, help_text="Describe the protein-level change using standard nomenclature (e.g., 'p.Val600Glu' for BRAF V600E mutation)", max_length=255, null=True)),
                ('variant_type', models.CharField(blank=True, help_text="Specify the type of variant (e.g., 'Missense', 'Frameshift', 'Deletion', 'Insertion')", max_length=255, null=True)),
                ('allele_frequency', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the variant allele frequency as a decimal (e.g., 0.45 for 45%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('read_depth', models.IntegerField(blank=True, help_text='Enter the sequencing read depth at this position (e.g., 500)', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_significance', models.ForeignKey(blank=True, help_text='Select the clinical significance of the variant', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_significance', to='client_app.lookupclinicalsignificance')),
                ('cosmic_gene_name', models.ForeignKey(help_text='Select the gene where the alteration was found, using COSMIC database nomenclature', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupcosmic')),
                ('pathology', models.ForeignKey(help_text='Select the pathology report this genomic alteration is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.pathology')),
            ],
            options={
                'verbose_name_plural': 'Somatic Genomic Alterations',
                'db_table': 'somatic_genomic_alterations',
            },
        ),
        migrations.CreateModel(
            name='StageInformation',
            fields=[
                ('chavi_stage_information_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(help_text='Select the diagnosis this staging information is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('m_stage', models.ForeignKey(blank=True, help_text="Enter the M stage describing distant metastasis (e.g., 'M0', 'M1', 'M1a', 'M1b')", null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupajccmstagedescriptor')),
                ('m_stage_prefix', models.ForeignKey(blank=True, help_text="Select any prefix modifiers for the M stage (e.g., 'c' for clinical, 'p' for pathological)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m_stage_prefix', to='client_app.lookupajccstageprefix')),
                ('m_stage_suffix', models.ForeignKey(blank=True, help_text="Enter any suffix modifiers for the M stage (e.g., 'a', 'b', 'c')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m_stage_suffix', to='client_app.lookupajccstagesuffix')),
                ('n_stage', models.ForeignKey(blank=True, help_text="Enter the N stage describing lymph node involvement (e.g., 'N0', 'N1', 'N2', 'N3')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='n_stage', to='client_app.lookupajccnstagedescriptor')),
                ('n_stage_prefix', models.ForeignKey(blank=True, help_text="Select any prefix modifiers for the N stage (e.g., 'c' for clinical, 'p' for pathological)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='n_stage_prefix', to='client_app.lookupajccstageprefix')),
                ('n_stage_suffix', models.ForeignKey(blank=True, help_text="Select any suffix modifiers for the N stage (e.g., 'a', 'b', 'c')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='n_stage_suffix', to='client_app.lookupajccstagesuffix')),
                ('overall_stage', models.ForeignKey(blank=True, help_text="Enter the overall stage grouping (e.g., 'Stage I', 'Stage II', 'Stage III', 'Stage IV')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overall_stage', to='client_app.lookupstagedescriptor')),
                ('stage_type', models.ForeignKey(blank=True, help_text='Select the type of staging information', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_type', to='client_app.lookupstagingtype')),
                ('staging_system', models.ForeignKey(blank=True, help_text="Select the staging system used (e.g., 'TNM 8th Edition', 'FIGO')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staging_system', to='client_app.lookupstagingsystem')),
                ('t_stage', models.ForeignKey(blank=True, help_text="Select the T stage describing the primary tumor (e.g., 'T1', 'T2', 'T3', 'T4')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_stage', to='client_app.lookupajcctstagedescriptor')),
                ('t_stage_prefix', models.ForeignKey(blank=True, help_text="Select the prefix modifiers for the T stage (e.g., 'c' for clinical, 'p' for pathological)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_stage_prefix', to='client_app.lookupajccstageprefix')),
                ('t_stage_suffix', models.ForeignKey(blank=True, help_text="Enter any suffix modifiers for the T stage (e.g., 'a', 'b', 'c')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_stage_suffix', to='client_app.lookupajccstagesuffix')),
            ],
            options={
                'verbose_name_plural': 'Stage Informations',
                'db_table': 'stage_information',
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('chavi_surgery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surgery_date', models.DateField(blank=True, help_text='Enter the date when the surgery was performed (format: YYYY-MM-DD)', null=True)),
                ('surgery_type', models.CharField(help_text="Enter the type of surgical procedure performed (e.g., 'Mastectomy', 'Lumpectomy', 'Excisional Biopsy')", max_length=255)),
                ('nodal_assessment', models.BooleanField(blank=True, help_text='Indicate whether lymph nodes were assessed during surgery (check for Yes, leave unchecked for No)', null=True)),
                ('nodal_assessment_type', models.CharField(blank=True, help_text="If nodes were assessed, specify the type of assessment (e.g., 'Sentinel Node Biopsy', 'Axillary Dissection')", max_length=255, null=True)),
                ('reconstruction', models.BooleanField(blank=True, help_text='Indicate whether reconstructive surgery was performed (check for Yes, leave unchecked for No)', null=True)),
                ('type_reconstruction', models.CharField(blank=True, help_text="If reconstruction was performed, specify the type (e.g., 'Implant-Based', 'Autologous Tissue', 'DIEP Flap')", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(help_text='Select the diagnosis that this treatment is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('surgery_dicom_study', models.ManyToManyField(blank=True, help_text='Select the DICOM studies associated with this surgical procedure', related_name='surgery_dicom_studies', to='client_app.dicomstudy')),
                ('surgery_side', models.ForeignKey(blank=True, help_text="Select which side of the body the surgery was performed on (e.g., 'Left', 'Right', 'Bilateral')", null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality')),
                ('surgery_site', models.ForeignKey(help_text='Select the anatomical location where the surgery was performed', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode')),
            ],
            options={
                'verbose_name_plural': 'Surgery',
                'db_table': 'surgery',
            },
        ),
        migrations.CreateModel(
            name='SystemicTherapy',
            fields=[
                ('chavi_systemic_therapy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systemic_therapy_start_date', models.DateField(blank=True, help_text='Enter the date when the treatment was started (format: YYYY-MM-DD)', null=True)),
                ('systemic_therapy_end_date', models.DateField(blank=True, help_text='Enter the date when the treatment was completed (format: YYYY-MM-DD)', null=True)),
                ('cycles_delivered', models.PositiveIntegerField(blank=True, help_text='Total Number of Cycles delivered if applicable.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(help_text='Select the diagnosis that this treatment is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('systemic_therapy_dicom_study', models.ManyToManyField(blank=True, help_text='Select the DICOM studies associated with this systemic therapy course', related_name='systemic_therapy_dicom_studies', to='client_app.dicomstudy')),
                ('systemic_therapy_regimen', models.ForeignKey(blank=True, help_text='Select the regimen for the systemic therapy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemic_therapy_regimen', to='client_app.lookupsystemictherapyregimen')),
                ('systemic_therapy_sequence', models.ForeignKey(blank=True, help_text='Select the sequence for the systemic therapy', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuptreatmentsequence')),
                ('systemic_therapy_type', models.ForeignKey(blank=True, help_text='Select the type of systemic therapy.', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupsystemictherapytype')),
            ],
            options={
                'verbose_name': 'Systemic Therapy Course',
                'verbose_name_plural': 'Systemic Therapy Courses',
                'db_table': 'systemic_therapy',
            },
        ),
        migrations.CreateModel(
            name='SystemicTherapySchedule',
            fields=[
                ('chavi_systemic_therapy_schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systemic_therapy_agent_start_date', models.DateField(blank=True, help_text='Enter the date when this specific medication was started (format: YYYY-MM-DD)', null=True)),
                ('systemic_therapy_agent_end_date', models.DateField(blank=True, help_text='Enter the date when this specific medication was stopped (format: YYYY-MM-DD).', null=True)),
                ('systemic_therapy_dose_planned', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the planned dose for this medication (numerical value only)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('systemic_therapy_dose_administered', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the actual dose of medication that was administered (numerical value only)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('systemic_therapy', models.ForeignKey(blank=True, help_text='Select the systemic therapy treatment this schedule is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systemic_therapy_schedule', to='client_app.systemictherapy')),
                ('systemic_therapy_agent', models.ForeignKey(blank=True, help_text='Select the specific medication or agent used in this treatment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemic_therapy_agent', to='client_app.lookupsystemicagent')),
                ('systemic_therapy_agent_route', models.ForeignKey(blank=True, help_text='Select how the medication was administered (e.g., oral, intravenous, subcutaneous)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemic_therapy_agent_route', to='client_app.lookupdrugroute')),
                ('systemic_therapy_dose_units', models.ForeignKey(blank=True, help_text='Select the units used for the dose (e.g., mg, mg/m², mg/kg)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systemic_therapy_dose_units', to='client_app.lookupunits')),
            ],
            options={
                'verbose_name': 'Medication Detail',
                'verbose_name_plural': 'Medication Details',
                'db_table': 'systematic_therapy_schedule',
            },
        ),
        migrations.AddConstraint(
            model_name='prodomain',
            constraint=models.UniqueConstraint(fields=('instrument', 'pro_domain'), name='unique_instrument_pro_domain'),
        ),
        migrations.AddConstraint(
            model_name='dicomstudyproject',
            constraint=models.UniqueConstraint(fields=('dicom_study', 'project'), name='unique_dicom_study_project'),
        ),
        migrations.AddConstraint(
            model_name='proquestion',
            constraint=models.UniqueConstraint(fields=('domain', 'pro_question'), name='unique_dommain_pro_question'),
        ),
    ]
