# Generated by Django 5.1.4 on 2024-12-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chavi_center_id', models.CharField(max_length=255, unique=True)),
                ('center_address', models.TextField()),
                ('center_city', models.TextField()),
                ('center_state', models.TextField()),
                ('center_country', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DICOMStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_of_reference_uid', models.CharField(max_length=255)),
                ('sop_instance_uid', models.CharField(max_length=255, unique=True)),
                ('modality', models.CharField(max_length=50)),
                ('study_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookupLaterality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_laterality_code', models.CharField(max_length=20)),
                ('side_description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DICOMSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(max_length=255, unique=True)),
                ('frame_of_reference_uid', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dicom_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudy')),
            ],
        ),
        migrations.CreateModel(
            name='DICOMStudyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('number_of_files', models.IntegerField()),
                ('file_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dicom_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudy')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.center')),
            ],
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.patient'),
        ),
        migrations.CreateModel(
            name='PatientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chavi_project_id', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('license', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patients', models.ManyToManyField(through='client_app.PatientProject', to='client_app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patientproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.project'),
        ),
        migrations.AlterUniqueTogether(
            name='patientproject',
            unique_together={('patient', 'project')},
        ),
    ]
