# Generated by Django 5.1.4 on 2025-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comorbidity',
            name='comorbidity_resolved',
            field=models.BooleanField(default=False, help_text='Indicate if the comorbidity has been resolved'),
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='date_of_comorbidity_assessment',
            field=models.DateField(blank=True, help_text='Enter the date when this comorbidity was last assessed (format:DD/MM/YYYY)', null=True),
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='duration_of_comorbidity',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the duration of the comorbidity in months', null=True),
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='medication_for_comorbidity',
            field=models.BooleanField(default=False, help_text='Indicate if the patient is currently taking medication for the comorbidity'),
        ),
        migrations.AlterField(
            model_name='dicomstudy',
            name='study_date',
            field=models.DateField(blank=True, help_text='The date when this imaging study was performed. This is recorded as DD/MM/YYYY format (for example: 2023-12-25).', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="The patient's date of birth in DD/MM/YYYY format.", null=True),
        ),
    ]
