# Generated by Django 5.1.4 on 2025-01-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookupcosmic',
            name='cosmic_gene_name',
        ),
        migrations.AddField(
            model_name='lookupcosmic',
            name='gene_aliases',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lookupcosmic',
            name='gene_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lookupcosmic',
            name='gene_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
