# Generated by Django 5.1.4 on 2024-12-26 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupFMACode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookupICDCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_version', models.DecimalField(decimal_places=2, max_digits=5)),
                ('icd_code', models.CharField(max_length=255)),
                ('icd_description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookupPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_date', models.DateField()),
                ('diagnostic_modality', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancer_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuplaterality')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.patient')),
                ('cancer_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupfmacode')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupicdcode')),
                ('presentation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuppresentation')),
            ],
        ),
    ]
