# Generated by Django 5.1.4 on 2025-01-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudy',
            name='series_descriptions',
            field=models.TextField(blank=True, help_text='Description of the series in the study. This is a text field that can store multiple series descriptions, separated by commas.', null=True),
        ),
    ]
