# Generated by Django 5.1.4 on 2025-01-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomstudyfiles',
            name='dicom_study',
        ),
        migrations.RemoveField(
            model_name='dicomtaginformation',
            name='dicom_study_files',
        ),
        migrations.DeleteModel(
            name='DICOMSeries',
        ),
        migrations.DeleteModel(
            name='DICOMStudyFiles',
        ),
        migrations.DeleteModel(
            name='DICOMTagInformation',
        ),
    ]
