# Generated by Django 5.1.4 on 2025-01-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_remove_lookupcosmic_cosmic_gene_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookupsystemicagent',
            name='systemic_agent_type',
        ),
    ]
