# Generated by Django 5.1.4 on 2025-01-11 16:50
import csv
from django.db import migrations
from pathlib import Path

def import_csv_data(apps, schema_editor):
    # Get the model
    LookupLaterality = apps.get_model('client_app', 'LookupLaterality')
    
    # Path to your CSV file
    # Assuming the CSV is in a 'data' directory in your Django project root
    csv_path = Path(__file__).resolve().parent.parent.parent / 'data' / 'laterality.csv'
    
    # Read CSV and create objects
    with open(csv_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        
        # Create objects in bulk for better performance
        objects_to_create = []
        for row in reader:
            objects_to_create.append(
                LookupLaterality(
                    code=row['code'],
                    label=row['label']
                )
            )
        
        # Bulk create all objects
        LookupLaterality.objects.bulk_create(objects_to_create)  


def reverse_migration(apps, schema_editor):
    # Get the model
    LookupLaterality = apps.get_model('client_app', 'LookupLaterality')
    # Delete all objects created by this migration
    LookupLaterality.objects.all().delete()        



class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_dicomstudy_series_descriptions'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration),        
    ]
