# Generated by Django 5.1.4 on 2024-12-26 15:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_lookupfmacode_lookupicdcode_lookuppresentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupLesionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesion_location_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LookupOutcomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('chavi_lesion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_lesion_assessed', models.DateField()),
                ('lesion_size_x_axis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lesion_size_y_axis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lesion_size_z_axis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lesion_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('lesion_laterality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuplaterality')),
                ('lesion_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupfmacode')),
                ('lesion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuplesiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('chavi_outcome_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_outcome_assessed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('outcome_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupoutcometype')),
            ],
        ),
    ]
