# Generated by Django 5.1.4 on 2025-04-06 10:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_comorbidity_comorbidity_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesion',
            name='lesion_detection_modality',
            field=models.CharField(blank=True, choices=[('CT', 'CT'), ('MRI', 'MRI'), ('PET', 'PET'), ('US', 'US'), ('MR_PET', 'MR_PET'), ('CT_PET', 'CT_PET'), ('Bone Scan', 'Bone Scan'), ('FDG_PET', 'FDG_PET'), ('PSMA_PET', 'PSMA_PET'), ('Clinical', 'Clinical'), ('X-ray', 'X-ray'), ('Other', 'Other')], help_text='The modality used to detect the lesion', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesion',
            name='lesion_suv_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The maximum SUV value of the lesion', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AddField(
            model_name='lesionresponse',
            name='lesion_response_modality',
            field=models.CharField(blank=True, choices=[('CT', 'CT'), ('MRI', 'MRI'), ('PET', 'PET'), ('US', 'US'), ('MR_PET', 'MR_PET'), ('CT_PET', 'CT_PET'), ('Bone Scan', 'Bone Scan'), ('FDG_PET', 'FDG_PET'), ('PSMA_PET', 'PSMA_PET'), ('Clinical', 'Clinical'), ('X-ray', 'X-ray'), ('Other', 'Other')], help_text='The modality used to detect the lesion response', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesionresponse',
            name='lesion_response_suv_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
