# Generated by Django 5.1.4 on 2025-01-05 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_remove_dicomstudyfiles_dicom_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdicomfile',
            name='processing_directory',
            field=models.CharField(blank=True, help_text='Path to the directory containing extracted DICOM files', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientdicomfile',
            name='file',
            field=models.FileField(help_text='Please upload a single zip file having the DICOM studies for a single patients. You can choose to upload multiple studies at the same time.', upload_to='dicom_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
    ]
