# Generated by Django 5.1.8 on 2025-04-06 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_lesion_lesion_detection_modality_and_more'),
        ('lookup', '0058_lookup_nodal_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='date_symptom_assessment',
            field=models.DateField(blank=True, help_text='The date when the symptom was first assessed', null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='duration_of_symptom',
            field=models.IntegerField(blank=True, help_text='The duration of the symptom in months', null=True),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='date_of_comorbidity_diagnosis',
            field=models.DateField(blank=True, help_text='This will be automatically calculated based on assessment date and duration', null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='date_onset',
            field=models.DateField(blank=True, help_text='The date when the symptom first appeared', null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='date_resolution',
            field=models.DateField(blank=True, help_text='The date when the symptom resolved', null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='severity',
            field=models.ForeignKey(blank=True, help_text='The severity of the symptom', null=True, on_delete=django.db.models.deletion.PROTECT, to='lookup.lookupseverity'),
        ),
    ]
