# Generated by Django 5.1.4 on 2025-01-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_remove_lookupsystemicagent_systemic_agent_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookupctcaegrade',
            old_name='ctcae_grade_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='lookupctcaegrade',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='lookupctcaegrade',
            name='meddra_soc',
        ),
    ]
