# Generated by Django 5.1.4 on 2025-01-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_patientdicomfile_processing_directory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdicomfile',
            name='processing_directory',
        ),
    ]
