# Generated by Django 5.1.4 on 2024-12-26 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_lookuplesiontype_lookupoutcometype_lesion_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupCosmic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosmic_gene_id', models.CharField(max_length=255, unique=True)),
                ('cosmic_gene_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LookupResponseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(max_length=255)),
                ('response_measurement_criteria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LookupUniProt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_name', models.CharField(max_length=500)),
                ('uniprot_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LesionResponse',
            fields=[
                ('chavi_lesion_response_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesion_response_date', models.DateField()),
                ('residual_lesion_size_x_axis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('residual_lesion_size_y_axis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('residual_lesion_size_z_axis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('residual_lesion_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lesion')),
                ('lesion_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupresponsetype')),
            ],
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('chavi_pathology_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_pathology', models.DateField()),
                ('specimen_type', models.CharField(max_length=255)),
                ('histological_type', models.CharField(max_length=255)),
                ('histological_subtype', models.CharField(max_length=255)),
                ('histological_grade', models.CharField(max_length=50)),
                ('histological_grading_schema', models.CharField(max_length=255)),
                ('greatest_tumor_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('greatest_dimension_of_tumor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_tumor_dimension_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_tumor_dimension_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tumor_focality', models.CharField(max_length=50)),
                ('lymphatic_vascular_invasion', models.CharField(max_length=255)),
                ('perineural_invasion', models.CharField(max_length=255)),
                ('dermal_lymphatic_vascular_invasion', models.CharField(max_length=255)),
                ('count_lymph_nodes_in_specimen', models.BigIntegerField(blank=True, null=True)),
                ('count_lymph_nodes_uninvolved', models.BigIntegerField(blank=True, null=True)),
                ('count_lymph_nodes_macroscopic', models.BigIntegerField(blank=True, null=True)),
                ('count_lymph_nodes_micrometastasis', models.BigIntegerField(blank=True, null=True)),
                ('count_lymph_node_isolated_tumor_cells', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('tumor_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuplaterality')),
                ('tumor_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupfmacode')),
            ],
        ),
        migrations.CreateModel(
            name='Immunohistochemistry',
            fields=[
                ('chavi_ihc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_ihc', models.DateField()),
                ('ihc_result', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protein_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupuniprot')),
                ('pathology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.pathology')),
            ],
        ),
        migrations.CreateModel(
            name='Cytogenetics',
            fields=[
                ('chavi_cytogenetics_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_cytogenetics', models.DateField()),
                ('cytogenetic_result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupcosmic')),
                ('pathology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.pathology')),
            ],
        ),
        migrations.CreateModel(
            name='SomaticGenomicAlterations',
            fields=[
                ('chavi_somatic_genomic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_test', models.DateField()),
                ('reference_sequence', models.CharField(max_length=255)),
                ('protein_modification', models.CharField(max_length=255)),
                ('variant_type', models.CharField(max_length=50)),
                ('allele_frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('read_depth', models.IntegerField(blank=True, null=True)),
                ('clinical_significance', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cosmic_gene_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupcosmic')),
                ('pathology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.pathology')),
            ],
        ),
    ]
