# Generated by Django 5.1.4 on 2025-01-12 03:49
from django.db import migrations
import pandas as pd

def import_csv_data(apps, schema_editor):
    # Get the model
    LookupICDCode = apps.get_model('client_app', 'LookupICDCode')
    
    # Read CSV and create objects

    url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/diagnosis_neoplasm.csv?inline=false'

    df = pd.read_csv(url)
    df = df.drop_duplicates(subset=['code'], keep='first')       

        
    # Create objects in bulk for better performance
    objects_to_create = [
        LookupICDCode(
            code=row['code'],
            icd_version = '11.0',
            label=row['label']
        ) for _, row in df.iterrows()
    ]
        
        # Bulk create all objects
    LookupICDCode.objects.bulk_create(objects_to_create)  


def reverse_migration(apps, schema_editor):
    # Get the model
    LookupICDCode = apps.get_model('client_app', 'LookupICDCode')
    # Delete all objects created by this migration
    LookupICDCode.objects.all().delete()        







class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_lookup_laterality'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration), 
    ]
