# Generated by Django 5.1.4 on 2024-12-26 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_lookupcosmic_lookupresponsetype_lookupuniprot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupTreatmentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_intent', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LookupTreatmentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_sequence', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('chavi_treatment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treatment_start_date', models.DateField()),
                ('treatment_end_date', models.DateField(blank=True, null=True)),
                ('treatment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('treatment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuptreatmentintent')),
                ('treatment_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuptreatmentsequence')),
            ],
        ),
        migrations.CreateModel(
            name='Radiotherapy',
            fields=[
                ('chavi_radiotherapy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('radiotherapy_modality', models.CharField(max_length=255)),
                ('total_dose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fractions', models.BigIntegerField(blank=True, null=True)),
                ('radiotherapy_type', models.CharField(max_length=255)),
                ('radiotherapy_technique', models.CharField(max_length=255)),
                ('fractions_per_day', models.BigIntegerField(blank=True, null=True)),
                ('treatment_volume', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radiotherapy_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuptreatmentsequence')),
                ('radiotherapy_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuplaterality')),
                ('radiotherapy_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupfmacode')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.treatment')),
            ],
        ),
    ]
