# Generated by Django 5.1.4 on 2025-01-12 03:56

from django.db import migrations
import pandas as pd

def import_csv_data(apps, schema_editor):
    # Get the model
    LookupFMACode = apps.get_model('client_app', 'LookupFMACode')
    
    # Read CSV and create objects
    url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/anatomical_site.csv?inline=false'

    df = pd.read_csv(url)
    df = df.drop_duplicates(subset=['code'], keep='first')           
    
    # Create objects in bulk for better performance
    objects_to_create = [
        LookupFMACode(
            code=row['code'],
            label=row['label']
        ) for _, row in df.iterrows()
    ]
        
        # Bulk create all objects
    LookupFMACode.objects.bulk_create(objects_to_create)  

def reverse_migration(apps, schema_editor):
    # Get the model
    LookupFMACode = apps.get_model('client_app', 'LookupFMACode')
    # Delete all objects created by this migration
    LookupFMACode.objects.all().delete()        


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_lookup_icd_code'),
    ]
    operations = [
        migrations.RunPython(import_csv_data, reverse_migration), 
    ]
