# Generated by Django 5.1.4 on 2025-01-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_rename_ctcae_grade_description_lookupctcaegrade_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupstagingsystem',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
