# Generated by Django 5.1.4 on 2025-01-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_remove_patientdicomfile_processing_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudy',
            name='study_description',
            field=models.CharField(blank=True, help_text='Description of the study Provided in the DICOM Data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dicomstudy',
            name='modality',
            field=models.CharField(blank=True, help_text='The type of imaging equipment used, such as CT (Computed Tomography), MRI (Magnetic Resonance Imaging), X-Ray, Ultrasound, etc. This tells us what kind of imaging study this is.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dicomstudy',
            name='study_date',
            field=models.DateField(blank=True, help_text='The date when this imaging study was performed. This is recorded as YYYY-MM-DD format (for example: 2023-12-25).', null=True),
        ),
        migrations.AlterField(
            model_name='dicomstudy',
            name='study_instance_uid',
            field=models.CharField(blank=True, help_text='A unique identifier for this specific imaging study. This is like a serial number - no two imaging studies anywhere should have the same Study Instance UID. This helps prevent any confusion between different studies.', max_length=255, null=True, unique=True),
        ),
    ]
