# Generated by Django 5.1.8 on 2025-04-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_symptom_date_symptom_assessment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptom',
            options={'verbose_name_plural': 'Symptoms'},
        ),
        migrations.AlterModelTable(
            name='symptom',
            table='symptom',
        ),
    ]
