# Generated by Django 5.1.4 on 2025-01-12 04:17

from django.db import migrations

import pandas as pd

def import_csv_data(apps, schema_editor):
    # Get the model
    LookupPresentation = apps.get_model('client_app', 'LookupPresentation')
    
    # Read CSV and create objects
    url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/presentation_type.csv?inline=false'

    df = pd.read_csv(url)
    
    # Create objects in bulk for better performance
    objects_to_create = [
        LookupPresentation(
            code=row['code'],
            presentation_type=row['presentation_type']
        ) for _, row in df.iterrows()
    ]
        
        # Bulk create all objects
    LookupPresentation.objects.bulk_create(objects_to_create)  

def reverse_migration(apps, schema_editor):
    # Get the model
    LookupPresentation = apps.get_model('client_app', 'LookupPresentation')
    # Delete all objects created by this migration
    LookupPresentation.objects.all().delete()        


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_lookup_fma_code'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration), 

    ]
