# Generated by Django 5.1.8 on 2025-04-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_alter_symptom_options_alter_symptom_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='duration_of_symptom',
            field=models.PositiveIntegerField(blank=True, help_text='The duration of the symptom in months', null=True),
        ),
    ]
