# Generated by Django 5.1.4 on 2025-01-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_dicomstudy_study_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomstudy',
            name='modality',
        ),
    ]
