# Generated by Django 5.1.4 on 2024-12-26 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_lookuptreatmentintent_lookuptreatmentsequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupDoseUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('unit_abbreviation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LookupDrugRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LookupSystemicAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemic_agent_name', models.CharField(max_length=255)),
                ('systemic_agent_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('chavi_surgery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surgery_date', models.DateField()),
                ('surgery_type', models.CharField(max_length=255)),
                ('nodal_dissection', models.BooleanField()),
                ('type_nodal_dissection', models.CharField(max_length=255)),
                ('reconstruction', models.BooleanField()),
                ('type_reconstruction', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('surgery_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupfmacode')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.treatment')),
            ],
        ),
    ]
