# Generated by Django 5.1.4 on 2024-12-26 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_lookupdoseunits_lookupdrugroute_lookupsystemicagent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcomitantMedications',
            fields=[
                ('chavi_medication_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('medication_dose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_medication_start_date', models.DateField()),
                ('date_medication_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupdrugroute')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='LookupCTCAEGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctcae_id', models.CharField(max_length=255, unique=True)),
                ('ctcae_term', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('meddra_code', models.CharField(max_length=255)),
                ('meddra_soc', models.CharField(max_length=255)),
                ('ctcae_grade', models.BigIntegerField()),
                ('ctcae_grade_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('ctcae_term', 'ctcae_grade')},
            },
        ),
        migrations.CreateModel(
            name='SystemicTherapy',
            fields=[
                ('chavi_systemic_therapy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_systemic_therapy', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('systemic_therapy_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuptreatmentsequence')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='SystemicTherapySchedule',
            fields=[
                ('chavi_systemic_therapy_schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systemic_therapy_agent_start_date', models.DateField()),
                ('systemic_therapy_agent_end_date', models.DateField(blank=True, null=True)),
                ('systemic_therapy_dose_planned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('systemic_therapy_dose_administered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('systemic_therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.systemictherapy')),
                ('systemic_therapy_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupsystemicagent')),
                ('systemic_therapy_agent_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupdrugroute')),
                ('systemic_therapy_dose_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupdoseunits')),
            ],
        ),
    ]
