# Generated by Django 5.2 on 2025-04-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_alter_symptom_duration_of_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='specimen_type',
            field=models.CharField(blank=True, choices=[('Core Biopsy', 'Core Biopsy'), ('Excision Biopsy', 'Excision Biopsy'), ('Incisional Biopsy', 'Incisional Biopsy'), ('Surgical Resection', 'Surgical Resection'), ('Fine Needle Aspiration', 'Fine Needle Aspiration'), ('Liquid Biopsy', 'Liquid Biopsy'), ('Other', 'Other')], help_text="The type of specimen collected (e.g., 'Core Biopsy', 'Surgical Resection', 'Fine Needle Aspiration')", max_length=500, null=True),
        ),
    ]
