# Generated by Django 5.1.4 on 2024-12-26 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_concomitantmedications_lookupctcaegrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_instrument', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_domain', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.proinstrument')),
            ],
            options={
                'unique_together': {('instrument', 'pro_domain')},
            },
        ),
        migrations.CreateModel(
            name='AdverseEffects',
            fields=[
                ('chavi_adverse_effects_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adverse_effect_type', models.CharField(max_length=255)),
                ('adverse_effect_grade', models.BigIntegerField()),
                ('adverse_effect_start_date', models.DateField()),
                ('adverse_effect_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.treatment')),
            ],
            options={
                'unique_together': {('adverse_effect_type', 'adverse_effect_grade')},
            },
        ),
        migrations.CreateModel(
            name='ProQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.prodomain')),
            ],
            options={
                'unique_together': {('domain', 'pro_question')},
            },
        ),
    ]
