# Generated by Django 5.2 on 2025-04-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_alter_pathology_specimen_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemictherapyschedule',
            options={'verbose_name': 'Systemic Therapy Medication Detail', 'verbose_name_plural': 'Systemic Therapy Medication Details'},
        ),
    ]
