# Generated by Django 5.2 on 2025-04-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_alter_systemictherapyschedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdicomfile',
            name='processed',
            field=models.BooleanField(default=False, help_text='Indicates whether the DICOM file has been processed.'),
        ),
        migrations.AddField(
            model_name='patientdicomfile',
            name='processing_log',
            field=models.TextField(blank=True, help_text='Log of the processing of the DICOM file.', null=True),
        ),
    ]
