# Generated by Django 5.1.4 on 2024-12-26 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_proinstrument_prodomain_adverseeffects_proquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('chavi_comorbidity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_comorbidity_diagnosis', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comorbidity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupicdcode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientOutcome',
            fields=[
                ('chavi_pt_outcome_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.patient')),
                ('patient_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupoutcome')),
                ('primary_cause_of_death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_cause', to='client_app.lookupicdcode')),
                ('secondary_cause_of_death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_cause', to='client_app.lookupicdcode')),
                ('tertiary_cause_of_death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_cause', to='client_app.lookupicdcode')),
            ],
        ),
        migrations.CreateModel(
            name='PatientReportedOutcome',
            fields=[
                ('chavi_pro_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pro_date', models.DateField()),
                ('pro_answer', models.TextField()),
                ('pro_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.prodomain')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.proinstrument')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.patient')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.proquestion')),
            ],
        ),
    ]
