# Generated by Django 5.1.4 on 2025-01-12 04:30

from django.db import migrations

import pandas as pd

def import_csv_data(apps, schema_editor):
    # Get the model
    LookupResponseType = apps.get_model('client_app', 'LookupResponseType')
    
    # Read CSV and create objects
    url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/response_type.csv?inline=false'

    df = pd.read_csv(url)
    
    # Create objects in bulk for better performance
    objects_to_create = [
        LookupResponseType(
            code=row['code'],
            response_type=row['response_type']
        ) for _, row in df.iterrows()
    ]
        
        # Bulk create all objects
    LookupResponseType.objects.bulk_create(objects_to_create)  

def reverse_migration(apps, schema_editor):
    # Get the model
    LookupResponseType = apps.get_model('client_app', 'LookupResponseType')
    # Delete all objects created by this migration
    LookupResponseType.objects.all().delete()        


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_lookup_lesion_type'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration), 

    ]
