# Generated by Django 5.1.4 on 2025-01-12 04:34

from django.db import migrations
from django.db import transaction
import pandas as pd

def import_csv_data(apps, schema_editor):
    # Get the model
    LookupUniProt = apps.get_model('client_app', 'LookupUniProt')
    
    try:
        
        # Read CSV and create objects
        url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/uniprot.csv?inline=false'
        df = pd.read_csv(url)

        df = df.drop_duplicates(subset=['code'], keep='first')        
        
        # Create objects in bulk for better performance
        objects_to_create = [
            LookupUniProt(
                code=row['code'],
                gene_name=row['gene_name'],
                uniport_id=row['uniprot_id'],
                protein_name=row['protein_name'],
                all_gene_names=row['all_gene_names']
            ) for _, row in df.iterrows()
        ]
        
        # Bulk create all objects in smaller chunks to prevent memory issues
        batch_size = 200
        while objects_to_create:
            batch = objects_to_create[:batch_size]
            LookupUniProt.objects.bulk_create(batch)
            objects_to_create = objects_to_create[batch_size:]
            
    except Exception as e:
        raise Exception(f"Failed to import data: {str(e)}")

def reverse_migration(apps, schema_editor):
    # Get the model
    LookupUniProt = apps.get_model('client_app', 'LookupUniProt')
    # Delete all objects created by this migration
    LookupUniProt.objects.all().delete()        

class Migration(migrations.Migration):

    atomic = True # Ensure data integrity during migration

    dependencies = [
        ('client_app', '0009_lookup_response_type'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration), 

    ]
