# Generated by Django 5.1.4 on 2024-12-26 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_lookupoutcome_comorbidity_patientoutcome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupStagingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging_system', models.CharField(max_length=255)),
                ('staging_system_version', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageInformation',
            fields=[
                ('chavi_stage_information_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_type', models.CharField(max_length=255)),
                ('t_stage_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('t_stage', models.CharField(max_length=255)),
                ('t_stage_suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('n_stage_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('n_stage', models.CharField(max_length=255)),
                ('n_stage_suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('m_stage_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('m_stage_suffix', models.CharField(max_length=255)),
                ('overall_stage', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('staging_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupstagingsystem')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisDICOMStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('dicom_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudy')),
            ],
            options={
                'unique_together': {('diagnosis', 'dicom_study')},
            },
        ),
        migrations.CreateModel(
            name='LesionDICOMStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudy')),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lesion')),
            ],
            options={
                'unique_together': {('lesion', 'dicom_study')},
            },
        ),
    ]
