# Generated by Django 5.2 on 2025-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_patientdicomfile_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudyproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
