# Generated by Django 5.1.4 on 2025-01-12 05:43

from django.db import migrations
from django.db import transaction
import pandas as pd

def import_csv_data(apps, schema_editor):
    # Get the model
    LookupCosmic = apps.get_model('client_app', 'LookupCosmic')
    
    try:
        
        # Read CSV and create objects
        url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/gene_data.csv?inline=false'
        df = pd.read_csv(url)

        df = df.drop_duplicates(subset=['gene_id'], keep='first')        
        
        # Create objects in bulk for better performance
        objects_to_create = [
            LookupCosmic(
                code=row['gene_id'],
                gene_name=row['gene_name'],
                gene_description=row['gene_description'],
                gene_aliases=row['gene_aliases']
            ) for _, row in df.iterrows()
        ]
        
        # Bulk create all objects in smaller chunks to prevent memory issues
        batch_size = 200
        while objects_to_create:
            batch = objects_to_create[:batch_size]
            LookupCosmic.objects.bulk_create(batch)
            objects_to_create = objects_to_create[batch_size:]
            
    except Exception as e:
        raise Exception(f"Failed to import data: {str(e)}")

def reverse_migration(apps, schema_editor):
    # Get the model
    LookupCosmic = app

class Migration(migrations.Migration):
    atomic = True # Ensure data integrity during migration


    dependencies = [
        ('client_app', '0010_lookup_uniprot'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration), 

    ]
