# Generated by Django 5.1.4 on 2024-12-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_lookupstagingsystem_stageinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.project')),
            ],
            options={
                'unique_together': {('diagnosis', 'project')},
            },
        ),
        migrations.CreateModel(
            name='DICOMStudyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudy')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.project')),
            ],
            options={
                'unique_together': {('dicom_study', 'project')},
            },
        ),
        migrations.CreateModel(
            name='LesionResponseDICOMStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudy')),
                ('lesion_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lesionresponse')),
            ],
            options={
                'unique_together': {('lesion_response', 'dicom_study')},
            },
        ),
        migrations.CreateModel(
            name='OutcomeDICOMStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudy')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.outcome')),
            ],
            options={
                'unique_together': {('outcome', 'dicom_study')},
            },
        ),
        migrations.CreateModel(
            name='RadiotherapyDICOMStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudy')),
                ('radiotherapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.radiotherapy')),
            ],
            options={
                'unique_together': {('radiotherapy', 'dicom_study')},
            },
        ),
    ]
