# Generated by Django 5.2 on 2025-05-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_dicomstudyproject_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudy',
            name='study_type',
            field=models.CharField(blank=True, choices=[('PRETREATMENT_DIAGNOSTIC_IMAGE', 'Pre-treatment Diagnostic Image'), ('PLANNING_IMAGE', 'Planning Image'), ('ON_TREATMENT_VERIFICATION_IMAGE', 'On-treatment Verification Image'), ('PLANNING_IMAGE_FOR_ADAPTIVE_TREATMENT', 'Planning Image for Adaptive Treatment'), ('POSTTREATMENT_THERAPY_RESPONSE_IMAGE', 'Post-treatment Therapy Response Image'), ('THERAPY_DELIVERY_IMAGE', 'Therapy Delivery Image'), ('THERAPY_QA_IMAGE', 'Therapy QA Image'), ('POSTTREATMENT_DIAGNOSTIC_IMAGE', 'Post-treatment Diagnostic Image'), ('OTHER', 'Other')], help_text='The type of study. This is a choice field that can be selected from the list of study types.', max_length=255, null=True),
        ),
    ]
