# Generated by Django 5.2 on 2025-05-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_dicomstudy_study_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudy',
            name='study_modalities',
            field=models.CharField(blank=True, help_text='The modalities inside the the study. ', max_length=255, null=True),
        ),
    ]
