# Generated by Django 5.1.4 on 2024-12-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_diagnosisproject_dicomstudyproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseeffects',
            name='ctcae_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupctcaegrade'),
        ),
    ]
