# Generated by Django 5.2 on 2025-05-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0012_dicomstudy_study_modalities'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dicomstudyproject',
            name='unique_dicom_study_project',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='diagnosis_dicom_study',
            new_name='study_instance_uid',
        ),
        migrations.RenameField(
            model_name='dicomstudyproject',
            old_name='dicom_study',
            new_name='study_instance_uid',
        ),
        migrations.RenameField(
            model_name='lesion',
            old_name='lesion_dicom_study',
            new_name='study_instance_uid',
        ),
        migrations.RenameField(
            model_name='lesionresponse',
            old_name='lesion_response_dicom_study',
            new_name='study_instance_uid',
        ),
        migrations.RenameField(
            model_name='outcome',
            old_name='outcome_dicom_study',
            new_name='study_instance_uid',
        ),
        migrations.RenameField(
            model_name='radiotherapy',
            old_name='radiotherapy_dicom_study',
            new_name='study_instance_uid',
        ),
        migrations.RenameField(
            model_name='surgery',
            old_name='surgery_dicom_study',
            new_name='study_instance_uid',
        ),
        migrations.RenameField(
            model_name='systemictherapy',
            old_name='systemic_therapy_dicom_study',
            new_name='study_instance_uid',
        ),
        migrations.AddConstraint(
            model_name='dicomstudyproject',
            constraint=models.UniqueConstraint(fields=('study_instance_uid', 'project'), name='unique_dicom_study_project'),
        ),
    ]
