# Generated by Django 5.1.4 on 2024-12-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0012_adverseeffects_ctcae_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientoutcome',
            name='patient_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupoutcome'),
        ),
        migrations.AlterField(
            model_name='patientoutcome',
            name='primary_cause_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_cause', to='client_app.lookupicdcode'),
        ),
        migrations.AlterField(
            model_name='patientoutcome',
            name='secondary_cause_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_cause', to='client_app.lookupicdcode'),
        ),
        migrations.AlterField(
            model_name='patientoutcome',
            name='tertiary_cause_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tertiary_cause', to='client_app.lookupicdcode'),
        ),
    ]
