# Generated by Django 5.1.4 on 2024-12-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0013_alter_patientoutcome_patient_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageinformation',
            name='staging_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupstagingsystem'),
        ),
    ]
