# Generated by Django 5.2 on 2025-05-01 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0013_remove_dicomstudyproject_unique_dicom_study_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnprocessedDICOMStudies',
            fields=[
                ('study_instance_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('dicom_patient_id', models.CharField(blank=True, max_length=64, null=True)),
                ('folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.patient')),
            ],
        ),
    ]
