# Generated by Django 5.2 on 2025-05-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0014_unprocesseddicomstudies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unprocesseddicomstudies',
            options={'verbose_name': 'Unprocessed DICOM Study', 'verbose_name_plural': 'Unprocessed DICOM Studies'},
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='folder_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
