# Generated by Django 5.1.4 on 2024-12-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0014_alter_stageinformation_staging_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuptreatmentsequence'),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode'),
        ),
    ]
