# Generated by Django 5.2 on 2025-05-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0015_alter_unprocesseddicomstudies_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cytogenetics',
            old_name='cytogentic_abnormality',
            new_name='cytogenetic_abnormality',
        ),
    ]
