# Generated by Django 5.1.4 on 2024-12-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0015_alter_radiotherapy_radiotherapy_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupsystemicagent'),
        ),
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_agent_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupdrugroute'),
        ),
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_dose_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupdoseunits'),
        ),
    ]
