# Generated by Django 5.2.4 on 2025-08-24 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0016_rename_cytogentic_abnormality_cytogenetics_cytogenetic_abnormality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdicomupload',
            name='file',
            field=models.FileField(help_text='Upload a zip file containing DICOM studies from multiple patients. Files will be processed and sorted based on Patient IDs found in DICOM metadata. Maximum file size: 10GB.', upload_to='bulk_dicom_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
    ]
