# Generated by Django 5.1.4 on 2024-12-27 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0016_alter_systemictherapyschedule_systemic_therapy_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='client_app.center'),
        ),
        migrations.AlterField(
            model_name='project',
            name='patients',
            field=models.ManyToManyField(related_name='Projects', through='client_app.PatientProject', to='client_app.patient'),
        ),
    ]
