# Generated by Django 5.2.4 on 2025-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0017_alter_bulkdicomupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesion',
            name='lesion_detection_modality',
            field=models.CharField(blank=True, choices=[('CT', 'CT'), ('MRI', 'MRI'), ('PET', 'PET'), ('US', 'US'), ('MR_PET', 'MR_PET'), ('CT_PET', 'CT_PET'), ('Bone Scan', 'Bone Scan'), ('FDG_PET', 'FDG_PET'), ('PSMA_PET', 'PSMA_PET'), ('NASAL_ENDOSCOPY', 'NASAL_ENDOSCOPY'), ('LARYNGOSCOPY', 'LARYNGOSCOPY'), ('UPPER_GI_ENDOSCOPY', 'UPPER_GI_ENDOSCOPY'), ('SIGMOIDOSCOPY', 'SIGMOIDOSCOPY'), ('PROCTOSCOPY', 'PROCTOSCOPY'), ('ERCP', 'ERCP'), ('CHOLANGIOGRAPHY', 'CHOLANGIOGRAPHY'), ('OTOSCOPY', 'OTOSCOPY'), ('COLONOSCOPY', 'COLONOSCOPY'), ('CAPSULE_ENDOSCOPY', 'CAPSULE_ENDOSCOPY'), ('COLPOSCOPY', 'COLPOSCOPY'), ('CYSTOSCOPY', 'CYSTOSCOPY'), ('URETEROSCOPY', 'URETEROSCOPY'), ('LAPAROSCOPY', 'LAPAROSCOPY'), ('Clinical', 'Clinical'), ('X-ray', 'X-ray'), ('Other', 'Other')], help_text='The modality used to detect the lesion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='lesion_response_modality',
            field=models.CharField(blank=True, choices=[('CT', 'CT'), ('MRI', 'MRI'), ('PET', 'PET'), ('US', 'US'), ('MR_PET', 'MR_PET'), ('CT_PET', 'CT_PET'), ('Bone Scan', 'Bone Scan'), ('FDG_PET', 'FDG_PET'), ('PSMA_PET', 'PSMA_PET'), ('NASAL_ENDOSCOPY', 'NASAL_ENDOSCOPY'), ('LARYNGOSCOPY', 'LARYNGOSCOPY'), ('UPPER_GI_ENDOSCOPY', 'UPPER_GI_ENDOSCOPY'), ('SIGMOIDOSCOPY', 'SIGMOIDOSCOPY'), ('PROCTOSCOPY', 'PROCTOSCOPY'), ('ERCP', 'ERCP'), ('CHOLANGIOGRAPHY', 'CHOLANGIOGRAPHY'), ('OTOSCOPY', 'OTOSCOPY'), ('COLONOSCOPY', 'COLONOSCOPY'), ('CAPSULE_ENDOSCOPY', 'CAPSULE_ENDOSCOPY'), ('COLPOSCOPY', 'COLPOSCOPY'), ('CYSTOSCOPY', 'CYSTOSCOPY'), ('URETEROSCOPY', 'URETEROSCOPY'), ('LAPAROSCOPY', 'LAPAROSCOPY'), ('Clinical', 'Clinical'), ('X-ray', 'X-ray'), ('Other', 'Other')], help_text='The modality used to detect the lesion response', max_length=255, null=True),
        ),
    ]
