# Generated by Django 5.1.4 on 2024-12-27 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0017_alter_diagnosis_patient_alter_patient_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='cancer_side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='cancer_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupicdcode'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.patient'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='presentation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuppresentation'),
        ),
    ]
