# Generated by Django 5.1.4 on 2024-12-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0018_alter_diagnosis_cancer_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comorbidity',
            name='date_of_comorbidity_diagnosis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='m_stage_suffix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='overall_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='stage_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
