# Generated by Django 5.2.4 on 2025-08-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0018_alter_lesion_lesion_detection_modality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='specimen_type',
            field=models.CharField(blank=True, choices=[('Core Biopsy', 'Core Biopsy'), ('Punch Biopsy', 'Punch Biopsy'), ('Excision Biopsy', 'Excision Biopsy'), ('Incisional Biopsy', 'Incisional Biopsy'), ('Surgical Resection', 'Surgical Resection'), ('Fine Needle Aspiration', 'Fine Needle Aspiration'), ('Liquid Biopsy', 'Liquid Biopsy'), ('Other', 'Other')], help_text="The type of specimen collected (e.g., 'Core Biopsy', 'Surgical Resection', 'Fine Needle Aspiration')", max_length=500, null=True),
        ),
    ]
