# Generated by Django 5.1.4 on 2024-12-27 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0019_alter_comorbidity_date_of_comorbidity_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseeffects',
            name='adverse_effect_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='comorbidity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupicdcode'),
        ),
        migrations.AlterField(
            model_name='patientreportedoutcome',
            name='pro_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientreportedoutcome',
            name='pro_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
