# Generated by Django 5.2.7 on 2025-11-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0019_alter_pathology_specimen_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dicomstudyproject',
            name='unique_dicom_study_project',
        ),
    ]
