# Generated by Django 5.2.7 on 2025-11-03 07:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0020_remove_dicomstudyproject_unique_dicom_study_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDICOMUploadSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(help_text='Uploaded zip file containing DICOM studies from multiple patients', upload_to='bulk_dicom_sessions', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('temp_directory', models.CharField(blank=True, help_text='Temporary directory path for extracted files', max_length=500, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EXTRACTED', 'Extracted'), ('ANALYZED', 'Analyzed'), ('MATCHING', 'Awaiting Manual Matching'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('total_studies', models.IntegerField(default=0)),
                ('auto_matched_studies', models.IntegerField(default=0)),
                ('manual_match_required', models.IntegerField(default=0)),
                ('unmatched_studies', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_dicom_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk DICOM Upload Session',
                'verbose_name_plural': 'Bulk DICOM Upload Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkDICOMStudyMatch',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_instance_uid', models.CharField(max_length=255)),
                ('dicom_patient_id', models.CharField(max_length=255)),
                ('study_description', models.CharField(blank=True, max_length=255, null=True)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('modalities', models.CharField(blank=True, max_length=255, null=True)),
                ('series_descriptions', models.TextField(blank=True, null=True)),
                ('file_count', models.IntegerField(default=0)),
                ('match_status', models.CharField(choices=[('AUTO_MATCHED', 'Automatically Matched'), ('MANUAL_MATCH_REQUIRED', 'Manual Match Required'), ('MANUALLY_MATCHED', 'Manually Matched'), ('CONFIRMED', 'Confirmed'), ('UNMATCHED', 'Unmatched'), ('PROCESSED', 'Processed')], default='MANUAL_MATCH_REQUIRED', max_length=30)),
                ('temp_folder_path', models.CharField(blank=True, max_length=500, null=True)),
                ('final_folder_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_study_matches', to='client_app.patient')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_matches', to='client_app.bulkdicomuploadsession')),
            ],
            options={
                'verbose_name': 'Bulk DICOM Study Match',
                'verbose_name_plural': 'Bulk DICOM Study Matches',
                'unique_together': {('session', 'study_instance_uid')},
            },
        ),
    ]
