# Generated by Django 5.1.4 on 2024-12-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0020_alter_adverseeffects_adverse_effect_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adverseeffects',
            old_name='ctcae_grade',
            new_name='ctcae_grade_lookup',
        ),
        migrations.AlterUniqueTogether(
            name='adverseeffects',
            unique_together=set(),
        ),
    ]
