# Generated by Django 6.0.8 on 2026-08-10 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0021_bulkdicomuploadsession_bulkdicomstudymatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdicomuploadsession',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task id of the most recently dispatched task', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bulkdicomuploadsession',
            name='last_progress_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last progress update, used for stall detection', null=True),
        ),
        migrations.AddField(
            model_name='bulkdicomuploadsession',
            name='progress_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkdicomuploadsession',
            name='progress_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bulkdicomuploadsession',
            name='progress_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkdicomuploadsession',
            name='resume_count',
            field=models.IntegerField(default=0, help_text='Number of times this session has been resumed'),
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Celery task id', max_length=255, unique=True)),
                ('task_name', models.CharField(help_text='Celery task name', max_length=255)),
                ('task_type', models.CharField(choices=[('DICOM_IMPORT', 'DICOM Import'), ('DICOM_EXPORT', 'DICOM Export'), ('BULK_DICOM', 'Bulk DICOM'), ('PATIENT_EXPORT', 'Patient Export'), ('ASSOCIATE', 'Associate to Project'), ('UNPROCESSED', 'Process Unprocessed DICOM')], default='DICOM_IMPORT', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('STALLED', 'Stalled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('progress_current', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(default=0)),
                ('progress_description', models.CharField(blank=True, max_length=255, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('resume_count', models.IntegerField(default=0, help_text='Number of times this task has been resumed')),
                ('manifest_path', models.CharField(blank=True, help_text='Path to JSONL manifest for per-file checkpointing', max_length=500, null=True)),
                ('result_summary', models.JSONField(blank=True, help_text='Task return value stored as JSON', null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('related_session_id', models.UUIDField(blank=True, help_text='Links to BulkDICOMUploadSession when applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Run',
                'verbose_name_plural': 'Task Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TASK_COMPLETED', 'Task Completed'), ('TASK_FAILED', 'Task Failed'), ('TASK_STALLED', 'Task Stalled'), ('TASK_RESUMED', 'Task Resumed')], default='TASK_COMPLETED', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='client_app.taskrun')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskrun',
            index=models.Index(fields=['status'], name='client_app__status_bdf4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrun',
            index=models.Index(fields=['user'], name='client_app__user_id_7477b8_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrun',
            index=models.Index(fields=['task_type'], name='client_app__task_ty_f5dac7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='client_app__user_id_4cc838_idx'),
        ),
    ]
