# Generated by Django 5.1.4 on 2024-12-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0021_rename_ctcae_grade_adverseeffects_ctcae_grade_lookup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_agent_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
