# Generated by Django 5.1.4 on 2025-01-12 08:52

from django.db import migrations
import pandas as pd
def import_csv_data(apps, schema_editor):
    # Get the model
    LookupAJCCTStageDescriptor = apps.get_model('client_app', 'LookupAJCCTStageDescriptor')
    
    try:
        
        # Read CSV and create objects
        url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/ajcc_t_stage.csv?inline=false'
        df = pd.read_csv(url)
        df = df.drop_duplicates(subset=['key'], keep='first')        
        
        # Create objects in bulk for better performance
        objects_to_create = [
            LookupAJCCTStageDescriptor(
                code=row['key'],
                label=row['description'] 
            ) for _, row in df.iterrows()
        ]
        
        # Bulk create all objects in smaller chunks to prevent memory issues
        batch_size = 200
        while objects_to_create:
            batch = objects_to_create[:batch_size]
            LookupAJCCTStageDescriptor.objects.bulk_create(batch)
            objects_to_create = objects_to_create[batch_size:]
            
    except Exception as e:
        raise Exception(f"Failed to import data: {str(e)}")
def reverse_migration(apps, schema_editor):
    # Get the model
    LookupAJCCTStageDescriptor = apps.get_model('client_app', 'LookupAJCCTStageDescriptor')
    # Delete all objects created by this migration
    LookupAJCCTStageDescriptor.objects.all().delete() 

class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0021_lookup_ajcc_prefix'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration),
    ]
