# Generated by Django 5.1.4 on 2024-12-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0022_alter_systemictherapyschedule_systemic_therapy_agent_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemictherapy',
            name='systemic_therapy_sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuptreatmentsequence'),
        ),
        migrations.AlterField(
            model_name='systemictherapy',
            name='type_systemic_therapy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
