# Generated by Django 6.0.8 on 2026-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0022_bulkdicomuploadsession_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='task_args',
            field=models.JSONField(blank=True, help_text='Original positional arguments used to dispatch this task, for resume/retry', null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='task_kwargs',
            field=models.JSONField(blank=True, help_text='Original keyword arguments used to dispatch this task, for resume/retry', null=True),
        ),
    ]
