# Generated by Django 5.1.4 on 2024-12-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0023_alter_systemictherapy_systemic_therapy_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgery',
            name='nodal_dissection',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='type_nodal_dissection',
        ),
        migrations.AddField(
            model_name='surgery',
            name='nodal_assessment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='nodal_assessment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='reconstruction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='type_reconstruction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
