# Generated by Django 6.0.6 on 2026-08-15 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0023_taskrun_task_args_taskrun_task_kwargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('DICOM_IMPORT', 'DICOM Import'), ('DICOM_EXPORT', 'DICOM Export'), ('BULK_DICOM', 'Bulk DICOM'), ('PATIENT_EXPORT', 'Patient Export'), ('ASSOCIATE', 'Associate to Project'), ('UNPROCESSED', 'Process Unprocessed DICOM'), ('DEIDENTIFICATION', 'Deidentification')], default='DICOM_IMPORT', max_length=30),
        ),
        migrations.CreateModel(
            name='DICOMSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(help_text='DICOM tag (0020,000E) — Series Instance UID.', max_length=128, unique=True)),
                ('series_date', models.DateField(blank=True, help_text='DICOM tag (0008,0021) — Series Date.', null=True)),
                ('modality', models.CharField(help_text='DICOM tag (0008,0060) — Modality (e.g. CT, MR, RTPLAN).', max_length=16)),
                ('frame_of_reference_uid', models.CharField(blank=True, help_text='DICOM tag (0020,0052) — Frame of Reference UID.', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(help_text='Reference to the DICOM study this series belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='series', to='client_app.dicomstudy')),
            ],
            options={
                'verbose_name_plural': 'DICOM Series',
                'db_table': 'dicom_series',
            },
        ),
        migrations.CreateModel(
            name='DICOMInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(help_text='DICOM tag (0008,0018) — SOP Instance UID.', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(help_text='Reference to the DICOM series this instance belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='client_app.dicomseries')),
            ],
            options={
                'verbose_name_plural': 'DICOM Instances',
                'db_table': 'dicom_instances',
            },
        ),
    ]
