# Generated by Django 5.1.4 on 2025-01-12 09:00

from django.db import migrations
import pandas as pd
def import_csv_data(apps, schema_editor):
    # Get the model
    LookupAJCCMStageDescriptor = apps.get_model('client_app', 'LookupAJCCMStageDescriptor')
    
    try:
        
        # Read CSV and create objects
        url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/ajcc_m_stage.csv?inline=false'
        df = pd.read_csv(url)
        df = df.drop_duplicates(subset=['key'], keep='first')        
        
        # Create objects in bulk for better performance
        objects_to_create = [
            LookupAJCCMStageDescriptor(
                code=row['key'],
                label=row['description'] 
            ) for _, row in df.iterrows()
        ]
        
        # Bulk create all objects in smaller chunks to prevent memory issues
        batch_size = 200
        while objects_to_create:
            batch = objects_to_create[:batch_size]
            LookupAJCCMStageDescriptor.objects.bulk_create(batch)
            objects_to_create = objects_to_create[batch_size:]
            
    except Exception as e:
        raise Exception(f"Failed to import data: {str(e)}")
def reverse_migration(apps, schema_editor):
    # Get the model
    LookupAJCCMStageDescriptor = apps.get_model('client_app', 'LookupAJCCMStageDescriptor')
    # Delete all objects created by this migration
    LookupAJCCMStageDescriptor.objects.all().delete() 


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0023_lookup_ajcc_nstage'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_migration),
    ]
