# Generated by Django 5.1.4 on 2024-12-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0024_remove_surgery_nodal_dissection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='surgery_side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode'),
        ),
    ]
