# Generated by Django 5.1.4 on 2025-01-12 09:05

from django.db import migrations
import pandas as pd
def import_csv_data(apps, schema_editor):
    # Get the model
    LookupDiagnosticModality = apps.get_model('client_app', 'LookupDiagnosticModality')
    
    try:
        
        # Read CSV and create objects
        url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/diagnostic_modality.csv?inline=false'
        df = pd.read_csv(url)    
        
        # Create objects in bulk for better performance
        objects_to_create = [
            LookupDiagnosticModality(
                diagnostic_modality=row['diagnostic_modality'] 
            ) for _, row in df.iterrows()
        ]
        
        # Bulk create all objects in smaller chunks to prevent memory issues
        batch_size = 200
        while objects_to_create:
            batch = objects_to_create[:batch_size]
            LookupDiagnosticModality.objects.bulk_create(batch)
            objects_to_create = objects_to_create[batch_size:]
            
    except Exception as e:
        raise Exception(f"Failed to import data: {str(e)}")
def reverse_migration(apps, schema_editor):
    # Get the model
    LookupDiagnosticModality = apps.get_model('client_app', 'LookupDiagnosticModality')
    # Delete all objects created by this migration
    LookupDiagnosticModality.objects.all().delete() 



class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0024_lookup_ajcc_mstage'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_code=reverse_migration),
    ]
