# Generated by Django 6.0.6 on 2026-08-20 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0024_alter_taskrun_task_type_dicomseries_dicominstance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskrun',
            index=models.Index(fields=['-created_at'], name='client_app__created_3c93a1_idx'),
        ),
    ]
