# Generated by Django 5.1.4 on 2024-12-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0025_surgery_surgery_side_alter_surgery_surgery_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiotherapy',
            name='treatment_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
