# Generated by Django 6.0.8 on 2026-09-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0025_taskrun_client_app__created_3c93a1_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_type', models.CharField(choices=[('PRETREATMENT_DIAGNOSTIC_IMAGE', 'Pre-treatment Diagnostic Image'), ('PLANNING_IMAGE', 'Planning Image'), ('ON_TREATMENT_VERIFICATION_IMAGE', 'On-treatment Verification Image'), ('PLANNING_IMAGE_FOR_ADAPTIVE_TREATMENT', 'Planning Image for Adaptive Treatment'), ('POSTTREATMENT_THERAPY_RESPONSE_IMAGE', 'Post-treatment Therapy Response Image'), ('THERAPY_DELIVERY_IMAGE', 'Therapy Delivery Image'), ('THERAPY_QA_IMAGE', 'Therapy QA Image'), ('POSTTREATMENT_DIAGNOSTIC_IMAGE', 'Post-treatment Diagnostic Image'), ('OTHER', 'Other')], max_length=50)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Rules are evaluated in ascending priority order; the first match wins.')),
                ('enabled', models.BooleanField(default=True)),
                ('match_modality', models.CharField(blank=True, default='', max_length=255)),
                ('modality_operator', models.CharField(choices=[('contains', 'contains (case-insensitive)'), ('exact', 'exact'), ('regex', 'matches regex')], default='contains', max_length=20)),
                ('match_study_description', models.CharField(blank=True, default='', max_length=255)),
                ('study_description_operator', models.CharField(choices=[('contains', 'contains (case-insensitive)'), ('exact', 'exact'), ('regex', 'matches regex')], default='contains', max_length=20)),
                ('match_series_description', models.CharField(blank=True, default='', max_length=255)),
                ('series_description_operator', models.CharField(choices=[('contains', 'contains (case-insensitive)'), ('exact', 'exact'), ('regex', 'matches regex')], default='contains', max_length=20)),
                ('reference_event', models.CharField(choices=[('NONE', 'None'), ('DIAGNOSIS_DATE', 'Diagnosis date'), ('RADIOTHERAPY_START', 'Radiotherapy start'), ('RADIOTHERAPY_END', 'Radiotherapy end'), ('SYSTEMIC_THERAPY_START', 'Systemic therapy start'), ('SYSTEMIC_THERAPY_END', 'Systemic therapy end')], default='NONE', help_text='Optional clinical date used for a date-window check.', max_length=40)),
                ('date_window_start_days', models.IntegerField(default=-7)),
                ('date_window_end_days', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Study type rule',
                'verbose_name_plural': 'Study type rules',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='study_type_source',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='AUTO', help_text='AUTO = set by classification rules; MANUAL = user override, never overwritten.', max_length=10),
        ),
    ]
