# Generated by Django 6.0.8 on 2026-09-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0026_studytyperule_dicomstudy_study_type_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='canonical_patient_id',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Normalised patient_id for canonical DICOM matching (set automatically on save).', max_length=255),
        ),
    ]
