# Generated by Django 5.1.4 on 2024-12-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0026_alter_radiotherapy_treatment_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_modality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_technique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='treatment_volume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
