# Generated by Django 5.1.4 on 2025-01-12 09:17

from django.db import migrations
import pandas as pd
def import_csv_data(apps, schema_editor):
    # Get the model
    LookupRadiotherapyVolumeType = apps.get_model('client_app', 'LookupRadiotherapyVolumeType')
    
    try:
        
        # Read CSV and create objects
        url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/radiotherapy_volume.csv?inline=false'
        df = pd.read_csv(url) 
        df = df.drop_duplicates(subset=['code'], keep='first')        

        
        # Create objects in bulk for better performance
        objects_to_create = [
            LookupRadiotherapyVolumeType(
                code=row['code'],
                radiotherapy_volume_type = row['radiotherapy_volume_type'] 
            ) for _, row in df.iterrows()
        ]
        
        # Bulk create all objects in smaller chunks to prevent memory issues
        batch_size = 200
        while objects_to_create:
            batch = objects_to_create[:batch_size]
            LookupRadiotherapyVolumeType.objects.bulk_create(batch)
            objects_to_create = objects_to_create[batch_size:]
            
    except Exception as e:
        raise Exception(f"Failed to import data: {str(e)}")
def reverse_migration(apps, schema_editor):
    # Get the model
    LookupRadiotherapyVolumeType = apps.get_model('client_app', 'LookupRadiotherapyVolumeType')
    # Delete all objects created by this migration
    LookupRadiotherapyVolumeType.objects.all().delete() 


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0026_lookup_systemictherapy_type'),
    ]

    operations = [
        migrations.RunPython(import_csv_data, reverse_code=reverse_migration),
    ]
