# Generated by Django 5.1.4 on 2025-01-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0027_lookup_radiotherapy_volume_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupStageDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
