# Generated by Django 5.1.4 on 2024-12-27 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0027_alter_radiotherapy_radiotherapy_modality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treatment_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuptreatmentintent'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuptreatmentsequence'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
