# Generated by Django 6.0.8 on 2026-09-27 02:59

import re

from django.db import migrations


def backfill(apps, schema_editor):
    Patient = apps.get_model('client_app', 'Patient')
    batch = []
    for patient in Patient.objects.all().iterator():
        patient.canonical_patient_id = re.sub(
            r'[^a-zA-Z0-9]', '', patient.patient_id or ''
        ).upper()
        batch.append(patient)
        if len(batch) >= 500:
            Patient.objects.bulk_update(batch, ['canonical_patient_id'])
            batch = []
    if batch:
        Patient.objects.bulk_update(batch, ['canonical_patient_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0027_patient_canonical_patient_id'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
