# Generated by Django 5.1.4 on 2024-12-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0028_alter_treatment_treatment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='clinical_significance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='cosmic_gene_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupcosmic'),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='date_test',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='protein_modification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='reference_sequence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='variant_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
