# Generated by Django 5.1.4 on 2025-01-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0028_lookupstagedescriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageinformation',
            name='overall_stage',
            field=models.ForeignKey(blank=True, help_text="Enter the overall stage grouping (e.g., 'Stage I', 'Stage II', 'Stage III', 'Stage IV')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overall_stage', to='client_app.lookupstagedescriptor'),
        ),
    ]
