# Generated by Django 5.1.4 on 2024-12-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0030_alter_cytogenetics_cytogenetic_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunohistochemistry',
            name='date_ihc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunohistochemistry',
            name='ihc_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
