# Generated by Django 5.1.4 on 2025-01-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0030_auto_20250113_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesion',
            name='lesion_volume_unit',
            field=models.ForeignKey(blank=True, help_text="The unit of measurement used for the lesion volume (e.g., 'cubic millimeters', 'cubic centimeters')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesion_volume_unit', to='client_app.lookupunits'),
        ),
    ]
