# Generated by Django 5.1.4 on 2025-01-13 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0031_lesion_lesion_volume_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnostic_modality',
            field=models.ForeignKey(blank=True, help_text='If the cancer was diagnosed with a method like cytology, biopsy etc then the modality can be entered here. Please ensure that the modality is spelled correctly.', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupdiagnosticmodality'),
        ),
    ]
