# Generated by Django 5.1.4 on 2024-12-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0031_alter_immunohistochemistry_date_ihc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='date_pathology',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='dermal_lymphatic_vascular_invasion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_grading_schema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_subtype',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='lymphatic_vascular_invasion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='perineural_invasion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tumor_focality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
