# Generated by Django 5.1.4 on 2024-12-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0032_alter_pathology_date_pathology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesionresponse',
            name='lesion_response_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
