# Generated by Django 5.1.4 on 2025-01-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0032_alter_diagnosis_diagnostic_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_registration',
            field=models.DateField(blank=True, help_text='Date of registration in hospital.', null=True),
        ),
    ]
