# Generated by Django 5.1.4 on 2024-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0033_alter_lesionresponse_lesion_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesion',
            name='date_lesion_assessed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
