# Generated by Django 5.1.4 on 2024-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0034_alter_lesion_date_lesion_assessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='date_outcome_assessed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
