# Generated by Django 5.1.4 on 2024-12-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0035_alter_outcome_date_outcome_assessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnostic_modality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
