# Generated by Django 5.1.4 on 2024-12-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0036_alter_diagnosis_diagnosis_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('unit_abbreviation', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_laterality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplesiontype'),
        ),
        migrations.AddField(
            model_name='lesion',
            name='lesion_size_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupunits'),
        ),
    ]
