# Generated by Django 5.1.4 on 2024-12-27 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0037_lookupunits_alter_lesion_lesion_laterality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='outcome_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupoutcometype'),
        ),
    ]
