# Generated by Django 5.1.4 on 2024-12-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0038_alter_outcome_outcome_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomstudyfiles',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dicomstudyfiles',
            name='number_of_files',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
