# Generated by Django 5.1.4 on 2024-12-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0039_alter_dicomstudyfiles_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMTagInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dicom_study_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudyfiles')),
            ],
        ),
    ]
