# Generated by Django 5.1.4 on 2024-12-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0040_dicomtaginformation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prodomain',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proquestion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='prodomain',
            constraint=models.UniqueConstraint(fields=('instrument', 'pro_domain'), name='unique_instrument_pro_domain'),
        ),
        migrations.AddConstraint(
            model_name='proquestion',
            constraint=models.UniqueConstraint(fields=('domain', 'pro_question'), name='unique_dommain_pro_question'),
        ),
    ]
