# Generated by Django 5.1.4 on 2024-12-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0041_alter_prodomain_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientproject',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='patientproject',
            constraint=models.UniqueConstraint(fields=('patient', 'project'), name='unique_patient_project'),
        ),
    ]
