# Generated by Django 5.1.4 on 2024-12-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0042_alter_patientproject_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diagnosisdicomstudy',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='diagnosisdicomstudy',
            constraint=models.UniqueConstraint(fields=('diagnosis', 'dicom_study'), name='unique_diagnosis_dicom_study'),
        ),
    ]
