# Generated by Django 5.1.4 on 2024-12-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0043_alter_diagnosisdicomstudy_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lookupctcaegrade',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lookupctcaegrade',
            constraint=models.UniqueConstraint(fields=('ctcae_term', 'ctcae_grade'), name='unique_ctcae_term_grade'),
        ),
    ]
