# Generated by Django 5.1.4 on 2024-12-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0044_alter_lookupctcaegrade_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outcomedicomstudy',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='outcomedicomstudy',
            constraint=models.UniqueConstraint(fields=('outcome', 'dicom_study'), name='unique_outcome_dicom_study'),
        ),
    ]
