# Generated by Django 5.1.4 on 2024-12-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0045_alter_outcomedicomstudy_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dicomstudyproject',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dicomstudyproject',
            constraint=models.UniqueConstraint(fields=('dicom_study', 'project'), name='unique_dicom_study_project'),
        ),
    ]
