# Generated by Django 5.1.4 on 2025-02-01 15:13

from django.db import migrations
import pandas as pd
def import_csv_data(apps, schema_editor):
    # Get the model
    LookupRTLocation = apps.get_model('client_app', 'LookupRTLocation')
    
    try:
        
        # Read CSV and create objects
        url = 'https://gitlab.com/drsantam/chavi-lookup-data/-/raw/main/lookup_datasets/lookup_radiotherapy_volumes.csv?ref_type=heads&inline=false'
        df = pd.read_csv(url)

        df = df.drop_duplicates(subset=['code'], keep='first')        
        
        # Create objects in bulk for better performance
        objects_to_create = [
            LookupRTLocation(
                code=row['code'],
                unit_abbreviation=row['unit_abbreviation'],
                label = row['unit']
            ) for _, row in df.iterrows()
        ]
        
        # Bulk create all objects in smaller chunks to prevent memory issues
        batch_size = 200
        while objects_to_create:
            batch = objects_to_create[:batch_size]
            LookupRTLocation.objects.bulk_create(batch)
            objects_to_create = objects_to_create[batch_size:]
            
    except Exception as e:
        raise Exception(f"Failed to import data: {str(e)}")
def reverse_migration(apps, schema_editor):
    # Get the model
    LookupRTLocation = apps.get_model('client_app', 'LookupRTLocation')
    # Delete all objects created by this migration
    LookupRTLocation.objects.all().delete() 

class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0046_lookup_lab_value_units'),
    ]

    operations = [
        migrations.RunPython(import_csv_data,reverse_migration),
    ]
