# Generated by Django 5.1.4 on 2024-12-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0046_alter_dicomstudyproject_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='radiotherapydicomstudy',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='radiotherapydicomstudy',
            constraint=models.UniqueConstraint(fields=('radiotherapy', 'dicom_study'), name='unique_radiotherapy_dicom_study'),
        ),
    ]
