# Generated by Django 5.1.4 on 2024-12-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0047_alter_radiotherapydicomstudy_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diagnosisproject',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='diagnosisproject',
            constraint=models.UniqueConstraint(fields=('diagnosis', 'project'), name='unique_diagnosis_project'),
        ),
    ]
