# Generated by Django 5.1.4 on 2025-02-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0048_lookup_laboratory_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stageinformation',
            options={'verbose_name_plural': 'Stage Information'},
        ),
    ]
