# Generated by Django 5.1.4 on 2024-12-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0048_alter_diagnosisproject_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesiondicomstudy',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lesiondicomstudy',
            constraint=models.UniqueConstraint(fields=('lesion', 'dicom_study'), name='unique_lesion_dicom_study'),
        ),
    ]
