# Generated by Django 5.1.4 on 2024-12-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0049_alter_lesiondicomstudy_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesionresponsedicomstudy',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lesionresponsedicomstudy',
            constraint=models.UniqueConstraint(fields=('lesion_response', 'dicom_study'), name='unique_lesion_response_dicom_study'),
        ),
    ]
