# Generated by Django 5.1.4 on 2024-12-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0050_alter_lesionresponsedicomstudy_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': ('Patients',)},
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
