# Generated by Django 5.1.4 on 2024-12-28 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0051_alter_patient_options_alter_patient_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
