# Generated by Django 5.1.4 on 2024-12-28 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0052_alter_project_options_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': ('Diagnoses',)},
        ),
        migrations.AlterModelOptions(
            name='lesion',
            options={'verbose_name_plural': ('Lesions',)},
        ),
        migrations.AlterModelOptions(
            name='outcome',
            options={'verbose_name_plural': ('Outcomes',)},
        ),
        migrations.AlterModelTable(
            name='diagnosis',
            table='diagnosis',
        ),
        migrations.AlterModelTable(
            name='lesion',
            table='lesion',
        ),
        migrations.AlterModelTable(
            name='outcome',
            table='outcome',
        ),
    ]
