# Generated by Django 5.1.4 on 2024-12-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0053_alter_diagnosis_options_alter_lesion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesionresponse',
            options={'verbose_name_plural': ('Lesion Responses',)},
        ),
        migrations.AlterModelOptions(
            name='pathology',
            options={'verbose_name_plural': ('Pathology',)},
        ),
        migrations.AlterModelTable(
            name='lesionresponse',
            table='lesion_response',
        ),
        migrations.AlterModelTable(
            name='pathology',
            table='pathology',
        ),
    ]
