# Generated by Django 5.1.4 on 2024-12-28 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0054_alter_lesionresponse_options_alter_pathology_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immunohistochemistry',
            options={'verbose_name_plural': 'Immunohistochemistries'},
        ),
        migrations.AlterModelTable(
            name='immunohistochemistry',
            table='immunohistochemistry',
        ),
    ]
