# Generated by Django 5.1.4 on 2024-12-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0055_alter_immunohistochemistry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cytogenetics',
            options={'verbose_name_plural': ('Cytogenetics',)},
        ),
        migrations.AlterModelOptions(
            name='somaticgenomicalterations',
            options={'verbose_name_plural': ('Somatic Genomic Alterations',)},
        ),
        migrations.AlterModelTable(
            name='cytogenetics',
            table='cytogenetics',
        ),
        migrations.AlterModelTable(
            name='somaticgenomicalterations',
            table='somatic_genomic_alterations',
        ),
    ]
