# Generated by Django 5.1.4 on 2024-12-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0056_alter_cytogenetics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name_plural': ('Treatment',)},
        ),
        migrations.AlterModelTable(
            name='treatment',
            table='treatment',
        ),
    ]
