# Generated by Django 5.1.4 on 2024-12-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0057_alter_treatment_options_alter_treatment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiotherapy',
            options={'verbose_name_plural': ('Radiotherapy',)},
        ),
        migrations.AlterModelOptions(
            name='surgery',
            options={'verbose_name_plural': ('Surgery',)},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name_plural': ('Treatments',)},
        ),
        migrations.AlterModelTable(
            name='radiotherapy',
            table='radiotherapy',
        ),
        migrations.AlterModelTable(
            name='surgery',
            table='surgery',
        ),
    ]
