# Generated by Django 5.1.4 on 2024-12-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0058_alter_radiotherapy_options_alter_surgery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concomitantmedications',
            options={'verbose_name_plural': ('ConcomitantMedications',)},
        ),
        migrations.AlterModelOptions(
            name='systemictherapy',
            options={'verbose_name_plural': ('Systemic Therapies',)},
        ),
        migrations.AlterModelOptions(
            name='systemictherapyschedule',
            options={'verbose_name_plural': ('Systematic Therapy Schedules',)},
        ),
        migrations.AlterModelTable(
            name='concomitantmedications',
            table='concomitant_medications',
        ),
        migrations.AlterModelTable(
            name='systemictherapy',
            table='systemic_therapy',
        ),
        migrations.AlterModelTable(
            name='systemictherapyschedule',
            table='systematic_therapy_schedule',
        ),
    ]
