# Generated by Django 5.1.4 on 2024-12-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0059_alter_concomitantmedications_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adverseeffects',
            options={'verbose_name_plural': ('Adverse Effects',)},
        ),
        migrations.AlterModelTable(
            name='adverseeffects',
            table='adverse_effects',
        ),
    ]
