# Generated by Django 5.1.4 on 2024-12-28 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0060_alter_adverseeffects_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proinstrument',
            options={'verbose_name_plural': ('PRO Instruments',)},
        ),
        migrations.AlterModelTable(
            name='proinstrument',
            table='pro_instruments',
        ),
    ]
