# Generated by Django 5.1.4 on 2024-12-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0061_alter_proinstrument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proinstrument',
            table='pro_instrument',
        ),
    ]
