# Generated by Django 5.1.4 on 2024-12-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0062_alter_proinstrument_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientreportedoutcome',
            options={'verbose_name_plural': ('Patient Reported Outcomes',)},
        ),
        migrations.AlterModelTable(
            name='patientreportedoutcome',
            table='patient_reported_outcome',
        ),
    ]
