# Generated by Django 5.1.4 on 2024-12-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0063_alter_patientreportedoutcome_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientoutcome',
            options={'verbose_name_plural': ('Patient Outcomes',)},
        ),
        migrations.AlterModelTable(
            name='patientoutcome',
            table='patient_outcome',
        ),
    ]
