# Generated by Django 5.1.4 on 2024-12-28 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0064_alter_patientoutcome_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comorbidity',
            options={'verbose_name_plural': ('Comorbidities',)},
        ),
        migrations.AlterModelTable(
            name='comorbidity',
            table='comorbidity',
        ),
    ]
