# Generated by Django 5.1.4 on 2024-12-28 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0065_alter_comorbidity_options_alter_comorbidity_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stageinformation',
            options={'verbose_name_plural': ('Stage Informations',)},
        ),
        migrations.AlterModelTable(
            name='stageinformation',
            table='stage_information',
        ),
    ]
