# Generated by Django 5.1.4 on 2024-12-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0066_alter_stageinformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_irb_approval',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_irb_approval_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
