# Generated by Django 5.1.4 on 2024-12-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0067_center_center_name_project_project_irb_approval_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name_plural': 'Centers'},
        ),
        migrations.AlterModelTable(
            name='center',
            table='center',
        ),
    ]
