# Generated by Django 5.1.4 on 2024-12-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0068_alter_center_options_alter_center_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chavi_consent',
            field=models.BooleanField(blank=True, default=False, help_text="Indicates whether the patient has provided consent for their data to be used in the CHAVI project. This field is required and must be set to True for the patient's data to be included in the project.", null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_chavi_consent',
            field=models.DateField(blank=True, help_text='The date when the patient provided consent for their data to be used in the CHAVI project. This field is required if chavi_consent is True.', null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_address',
            field=models.TextField(blank=True, help_text="The complete street address of the medical center. Should include building number, street name, and any additional address details like suite or floor number. Example: '1216 Second Street SW'. This field is optional.", null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_city',
            field=models.TextField(blank=True, help_text="The city where the medical center is located. Should be written in full without abbreviations. Example: 'Rochester' or 'New York City'. This field is optional.", null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_country',
            field=models.TextField(blank=True, help_text="The country where the medical center is located. Use the full country name, not abbreviations. Example: 'United States' or 'Canada'. This field is optional.", null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_name',
            field=models.CharField(blank=True, help_text="The official name of the medical center or healthcare facility. Example: 'Mayo Clinic Rochester' or 'Memorial Sloan Kettering Cancer Center'. This field is optional.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_state',
            field=models.TextField(blank=True, help_text="The state or province where the medical center is located. For US locations, use the full state name or standard two-letter abbreviation. For international locations, use appropriate regional divisions. Example: 'Minnesota' or 'MN'. This field is optional.", null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='chavi_center_id',
            field=models.CharField(help_text='A unique identifier for the medical center. This will be provided to you and will be consistent for your center.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when this center record was first created. This field is automatically set and cannot be modified.'),
        ),
        migrations.AlterField(
            model_name='center',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp when this center record was last updated. This field is automatically updated whenever the record is modified.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='center',
            field=models.ForeignKey(help_text='The medical center where this patient is being treated. This field links to a registered healthcare facility in our system. This is a required field and cannot be changed once set.', on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='client_app.center'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this patient record was first created in the system. This field is automatically set and cannot be modified.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(help_text="The patient's date of birth in DD-MM-YYYY format. For example: '15-07-1990'. This should match the date of birth in their medical record."),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(help_text="The patient's gender as recorded in their medical record. This should be entered exactly as it appears in your medical record system. For example: 'Male', 'Female', 'Non-Binary', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(help_text="A unique identifier for the patient. This should be your institution's medical record number or another consistent identifier used by your center. This must be unique across all patients and cannot be changed once set. For example: 'MRN123456' or 'PAT-2023-001'.", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this patient record was last updated. This field is automatically updated whenever any information in the record is modified.'),
        ),
    ]
