# Generated by Django 5.1.4 on 2024-12-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0069_patient_chavi_consent_patient_date_chavi_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_abbreviation',
            field=models.CharField(blank=True, help_text='The abbreviation for the project.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='chavi_project_id',
            field=models.CharField(help_text='A unique identifier for the project.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, help_text="The date when this project was or is expected to be completed. Format: DD-MM-YYYY. Example: '31-12-2024'", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text="A detailed description of the project's purpose, goals, and methods. This should be comprehensive enough for others to understand what the project is about.", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='license',
            field=models.CharField(blank=True, help_text="The type of license under which this project's data is shared. Example: 'MIT', 'Apache 2.0', 'CC BY 4.0'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_irb_approval',
            field=models.BooleanField(blank=True, help_text='Indicate whether this project has received IRB (Institutional Review Board) approval. Check the box for Yes, leave unchecked for No.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_irb_approval_number',
            field=models.CharField(blank=True, help_text="If IRB approval was received, enter the IRB protocol number here. This can typically be found on your IRB approval letter. Example: 'IRB-2023-123'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, help_text="The descriptive name of the project. This should be a clear, recognizable title. Example: 'Breast Cancer Imaging Study 2023'", max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text="The date when this project officially began. Format: DD-MM-YYYY. Example: '01-01-2023'", null=True),
        ),
    ]
