# Generated by Django 5.1.4 on 2024-12-29 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0070_project_project_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomstudy',
            name='frame_of_reference_uid',
            field=models.CharField(help_text="A unique identifier that helps link different imaging series and studies together that were taken in the same physical space and time reference. Think of this like a coordinate system - images with the same frame of reference UID were taken in the same 'space and time'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='dicomstudy',
            name='modality',
            field=models.CharField(help_text='The type of imaging equipment used, such as CT (Computed Tomography), MRI (Magnetic Resonance Imaging), X-Ray, Ultrasound, etc. This tells us what kind of imaging study this is.', max_length=50),
        ),
        migrations.AlterField(
            model_name='dicomstudy',
            name='patient',
            field=models.ForeignKey(help_text='Reference to the patient that this imaging study belongs to. When a patient record is deleted, all associated imaging studies will also be deleted.', on_delete=django.db.models.deletion.CASCADE, to='client_app.patient'),
        ),
        migrations.AlterField(
            model_name='dicomstudy',
            name='sop_instance_uid',
            field=models.CharField(help_text='A globally unique identifier for this specific imaging study. This is like a serial number - no two imaging studies anywhere should have the same SOP Instance UID. This helps prevent any confusion between different studies.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dicomstudy',
            name='study_date',
            field=models.DateField(help_text='The date when this imaging study was performed. This is recorded as YYYY-MM-DD format (for example: 2023-12-25).'),
        ),
    ]
