# Generated by Django 5.1.4 on 2024-12-29 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0071_alter_dicomstudy_frame_of_reference_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupDiagnosticModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_modality', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='cancer_side',
            field=models.ForeignKey(help_text='Select the side at which the cancer was present.', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='cancer_site',
            field=models.ForeignKey(help_text='Select the cancer site. This can be a site where the cancer was first diagnosed or a site where the cancer was recurred or metastasized.', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.ForeignKey(help_text='Select the diagbnosis ICD code. If the patient has multiple diagnoses then you can add another instance of the form.', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupicdcode'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_date',
            field=models.DateField(blank=True, help_text='Select the data at which the diagnosis was made. This can be a date when the patient came to the hospital for the first time or when a pathological proof was obtained', null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnostic_modality',
            field=models.CharField(blank=True, help_text='If the cancer was diagnosed with a method like cytology, biopsy etc then the modality can be entered here. Please ensure that the modality is spelled correctly.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(help_text='Select the patient', on_delete=django.db.models.deletion.CASCADE, to='client_app.patient'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='presentation_type',
            field=models.ForeignKey(help_text='Select the type of presentation. This can be a new presentation or a recurrence or a metastasis.', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuppresentation'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnostic_modality_type',
            field=models.ForeignKey(blank=True, help_text='Select the type of diagnostic modality used to diagnose the cancer. This can be a clinical examination, imaging, biopsy, cytology, etc.', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupdiagnosticmodality'),
        ),
    ]
