# Generated by Django 5.1.4 on 2024-12-29 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0072_lookupdiagnosticmodality_alter_diagnosis_cancer_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesion',
            name='date_lesion_assessed',
            field=models.DateField(blank=True, help_text='Enter the date when this lesion was assessed or measured. Format: DD-MM-YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='diagnosis',
            field=models.ForeignKey(help_text='Select the diagnosis this lesion is associated with.', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_laterality',
            field=models.ForeignKey(help_text='Select which side of the body the lesion is on (e.g., left, right, bilateral).', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_site',
            field=models.ForeignKey(help_text='Select the anatomical location where the lesion is found.', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_unit',
            field=models.ForeignKey(blank=True, help_text='Select the unit of measurement used for the lesion sizes (e.g., mm, cm).', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupunits'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_x_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the width of the lesion. Use decimal points for fractions.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_y_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the height of the lesion. Use decimal points for fractions.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_z_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the depth of the lesion. Use decimal points for fractions.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_type',
            field=models.ForeignKey(help_text='Select the type of lesion (e.g., primary tumor, metastasis).', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplesiontype'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the total volume of the lesion if available. Use decimal points for fractions.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='lesion',
            field=models.ForeignKey(help_text='Select the lesion this response assessment is for.', on_delete=django.db.models.deletion.CASCADE, to='client_app.lesion'),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='lesion_response',
            field=models.ForeignKey(help_text='Select how the lesion responded to treatment (e.g., complete response, partial response).', on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupresponsetype'),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='lesion_response_date',
            field=models.DateField(blank=True, help_text="Enter the date when the lesion's response to treatment was assessed. Format: DD-MM-YYYY", null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_size_x_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the width of the lesion after treatment. Use decimal points for fractions.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_size_y_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the height of the lesion after treatment. Use decimal points for fractions.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_size_z_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the depth of the lesion after treatment. Use decimal points for fractions.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the total volume of the lesion after treatment if available. Use decimal points for fractions.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date_outcome_assessed',
            field=models.DateField(blank=True, help_text='Enter the date when this outcome was assessed by the healthcare team. Format: DD-MM-YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='diagnosis',
            field=models.ForeignKey(help_text='Select the diagnosis this outcome is associated with.', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='outcome_type',
            field=models.ForeignKey(help_text='Select the type of outcome that was assessed (e.g., treatment response, disease progression).', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupoutcometype'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='additional_tumor_dimension_1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the second largest measurement of the tumor.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='additional_tumor_dimension_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the third largest measurement of the tumor.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_node_isolated_tumor_cells',
            field=models.BigIntegerField(blank=True, help_text='Enter the number of lymph nodes with individual cancer cells.', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_in_specimen',
            field=models.BigIntegerField(blank=True, help_text='Enter the total number of lymph nodes found in the specimen.', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_macroscopic',
            field=models.BigIntegerField(blank=True, help_text='Enter the number of lymph nodes with visible cancer deposits.', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_micrometastasis',
            field=models.BigIntegerField(blank=True, help_text='Enter the number of lymph nodes with microscopic cancer deposits.', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_uninvolved',
            field=models.BigIntegerField(blank=True, help_text='Enter the number of lymph nodes that did not contain cancer.', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='date_pathology',
            field=models.DateField(blank=True, help_text='Enter the date when the pathology specimen was collected. Format: DD-MM-YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='dermal_lymphatic_vascular_invasion',
            field=models.CharField(blank=True, help_text='Enter whether cancer cells were found in skin lymph vessels.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='diagnosis',
            field=models.ForeignKey(help_text='Select the diagnosis this pathology report is associated with.', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='greatest_dimension_of_tumor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the largest overall measurement of the tumor.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='greatest_tumor_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the largest dimension of the tumor measured in the pathology specimen.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_grade',
            field=models.CharField(blank=True, help_text='Enter the grade of the tumor (indicates how abnormal the cancer cells look).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_grading_schema',
            field=models.CharField(blank=True, help_text='Enter the system used to determine the tumor grade.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_subtype',
            field=models.CharField(blank=True, help_text='Enter any specific subtype of the cancer if identified.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_type',
            field=models.CharField(blank=True, help_text='Enter the main type of cancer as determined by microscopic examination.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='lymphatic_vascular_invasion',
            field=models.CharField(blank=True, help_text='Enter whether cancer cells were found in blood or lymph vessels.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='perineural_invasion',
            field=models.CharField(blank=True, help_text='Enter whether cancer cells were found around nerves.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='specimen_type',
            field=models.CharField(blank=True, help_text='Enter the type of specimen collected (e.g., biopsy, surgical resection).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tumor_focality',
            field=models.CharField(blank=True, help_text='Enter whether the tumor is unifocal (single) or multifocal (multiple locations).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tumor_side',
            field=models.ForeignKey(help_text='Select which side of the body the tumor was found on (e.g., left, right, bilateral).', on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tumor_site',
            field=models.ForeignKey(help_text='Select the anatomical location where the tumor was found.', on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupfmacode'),
        ),
    ]
