# Generated by Django 5.1.4 on 2024-12-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0074_alter_cytogenetics_cytogenetic_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='diagnostic_modality_type',
        ),
        migrations.AlterField(
            model_name='cytogenetics',
            name='cytogenetic_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cytogenetics',
            name='date_cytogenetics',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cytogenetics',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupcosmic'),
        ),
        migrations.AlterField(
            model_name='cytogenetics',
            name='pathology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.pathology'),
        ),
        migrations.AlterField(
            model_name='immunohistochemistry',
            name='date_ihc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunohistochemistry',
            name='ihc_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='immunohistochemistry',
            name='pathology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.pathology'),
        ),
        migrations.AlterField(
            model_name='immunohistochemistry',
            name='protein_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupuniprot'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='date_lesion_assessed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_laterality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupunits'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_x_axis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_y_axis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_z_axis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplesiontype'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='lesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lesion'),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='lesion_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupresponsetype'),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='lesion_response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_size_x_axis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_size_y_axis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_size_z_axis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='additional_tumor_dimension_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='additional_tumor_dimension_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_node_isolated_tumor_cells',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_in_specimen',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_macroscopic',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_micrometastasis',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_uninvolved',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='date_pathology',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='dermal_lymphatic_vascular_invasion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='greatest_dimension_of_tumor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='greatest_tumor_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_grading_schema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_subtype',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='lymphatic_vascular_invasion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='perineural_invasion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tumor_focality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tumor_side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tumor_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupfmacode'),
        ),
    ]
