# Generated by Django 5.1.4 on 2024-12-29 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0075_remove_diagnosis_diagnostic_modality_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesion',
            name='date_lesion_assessed',
            field=models.DateField(blank=True, help_text='The date when this lesion was first identified or assessed by a medical professional', null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='diagnosis',
            field=models.ForeignKey(help_text='Select the diagnosis that this lesion is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_laterality',
            field=models.ForeignKey(help_text="Indicates which side of the body the lesion is on (e.g., 'Left', 'Right', 'Bilateral')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_site',
            field=models.ForeignKey(help_text="The anatomical location where the lesion is found (e.g., 'Left Breast', 'Right Lung')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_unit',
            field=models.ForeignKey(blank=True, help_text="The unit of measurement used for the lesion dimensions (e.g., 'millimeters', 'centimeters')", null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupunits'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_x_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The width (x-axis measurement) of the lesion in the specified unit of measurement', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_y_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The length (y-axis measurement) of the lesion in the specified unit of measurement', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size_z_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The depth (z-axis measurement) of the lesion in the specified unit of measurement', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_type',
            field=models.ForeignKey(help_text="The type or category of the lesion (e.g., 'Primary Tumor', 'Metastatic Lesion')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplesiontype'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total volume of the lesion, calculated from the three-dimensional measurements', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='lesion',
            field=models.ForeignKey(help_text='The specific lesion (abnormal tissue) that is being monitored for response to treatment', on_delete=django.db.models.deletion.CASCADE, to='client_app.lesion'),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='lesion_response',
            field=models.ForeignKey(help_text='How the lesion has responded to treatment (e.g., complete response, partial response, stable disease, etc.)', on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupresponsetype'),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='lesion_response_date',
            field=models.DateField(blank=True, help_text="The date when the lesion's response to treatment was evaluated", null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_size_x_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The width (left to right measurement) of any remaining lesion after treatment', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_size_y_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The length (front to back measurement) of any remaining lesion after treatment', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_size_z_axis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The height (top to bottom measurement) of any remaining lesion after treatment', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesionresponse',
            name='residual_lesion_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total volume (size in three dimensions) of any remaining lesion after treatment', max_digits=10, null=True),
        ),
    ]
