# Generated by Django 5.1.4 on 2024-12-29 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0076_alter_lesion_date_lesion_assessed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='additional_tumor_dimension_1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The second dimension of the tumor measured in centimeters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='additional_tumor_dimension_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The third dimension of the tumor measured in centimeters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_node_isolated_tumor_cells',
            field=models.BigIntegerField(blank=True, help_text='Number of lymph nodes with isolated tumor cells (<0.2mm)', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_in_specimen',
            field=models.BigIntegerField(blank=True, help_text='Total number of lymph nodes found in the specimen', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_macroscopic',
            field=models.BigIntegerField(blank=True, help_text='Number of lymph nodes with visible tumor deposits', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_micrometastasis',
            field=models.BigIntegerField(blank=True, help_text='Number of lymph nodes with microscopic tumor deposits (0.2-2.0mm)', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='count_lymph_nodes_uninvolved',
            field=models.BigIntegerField(blank=True, help_text='Number of lymph nodes without any tumor involvement', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='date_pathology',
            field=models.DateField(blank=True, help_text='The date when the pathology specimen was collected or the pathology report was issued', null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='dermal_lymphatic_vascular_invasion',
            field=models.CharField(blank=True, help_text='Presence or absence of tumor cells within dermal lymphatic vessels', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='diagnosis',
            field=models.ForeignKey(help_text='The diagnosis associated with this pathology report', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='greatest_dimension_of_tumor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The primary dimension of the tumor measured in centimeters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='greatest_tumor_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The largest dimension of the tumor measured in centimeters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_grade',
            field=models.CharField(blank=True, help_text="The degree of differentiation of the tumor cells (e.g., 'Grade 1', 'Grade 2', 'Grade 3')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_grading_schema',
            field=models.CharField(blank=True, help_text="The system used to determine the histological grade (e.g., 'Nottingham', 'Gleason', 'WHO')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_subtype',
            field=models.CharField(blank=True, help_text="A more specific classification within the histological type (e.g., 'Mucinous', 'Papillary')", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='histological_type',
            field=models.CharField(blank=True, help_text="The primary histological classification of the tumor (e.g., 'Adenocarcinoma', 'Squamous Cell Carcinoma')", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='lymphatic_vascular_invasion',
            field=models.CharField(blank=True, help_text='Presence or absence of tumor cells within lymphatic or blood vessels', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='perineural_invasion',
            field=models.CharField(blank=True, help_text='Presence or absence of tumor cells invading nerve tissue', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='specimen_type',
            field=models.CharField(blank=True, help_text="The type of specimen collected (e.g., 'Core Biopsy', 'Surgical Resection', 'Fine Needle Aspiration')", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tumor_focality',
            field=models.CharField(blank=True, help_text='Whether the tumor is unifocal (single focus) or multifocal (multiple foci)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tumor_side',
            field=models.ForeignKey(help_text="The side of the body where the tumor is located (e.g., 'Left', 'Right', 'Bilateral')", on_delete=django.db.models.deletion.CASCADE, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='tumor_site',
            field=models.ForeignKey(help_text='The anatomical location of the tumor as defined by the Foundational Model of Anatomy (FMA)', on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupfmacode'),
        ),
    ]
