# Generated by Django 5.1.4 on 2024-12-29 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0077_alter_pathology_additional_tumor_dimension_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunohistochemistry',
            name='date_ihc',
            field=models.DateField(blank=True, help_text='Enter the date when the immunohistochemistry test was performed (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='immunohistochemistry',
            name='ihc_result',
            field=models.CharField(blank=True, help_text="Enter the result of the immunohistochemistry test (e.g., 'Positive', 'Negative', or specific values like '3+')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='immunohistochemistry',
            name='pathology',
            field=models.ForeignKey(help_text='Select the pathology report this immunohistochemistry test is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.pathology'),
        ),
        migrations.AlterField(
            model_name='immunohistochemistry',
            name='protein_name',
            field=models.ForeignKey(help_text='Select the protein that was tested for in this immunohistochemistry test', on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupuniprot'),
        ),
    ]
