# Generated by Django 5.1.4 on 2024-12-29 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0079_alter_cytogenetics_cytogenetic_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='allele_frequency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the variant allele frequency as a decimal (e.g., 0.45 for 45%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='clinical_significance',
            field=models.CharField(blank=True, help_text="Indicate the clinical significance of the variant (e.g., 'Pathogenic', 'Benign', 'VUS')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='cosmic_gene_name',
            field=models.ForeignKey(help_text='Select the gene where the alteration was found, using COSMIC database nomenclature', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupcosmic'),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='date_test',
            field=models.DateField(blank=True, help_text='Enter the date when the genomic testing was performed (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='pathology',
            field=models.ForeignKey(help_text='Select the pathology report this genomic alteration is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.pathology'),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='protein_modification',
            field=models.CharField(blank=True, help_text="Describe the protein-level change using standard nomenclature (e.g., 'p.Val600Glu' for BRAF V600E mutation)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='read_depth',
            field=models.IntegerField(blank=True, help_text='Enter the sequencing read depth at this position (e.g., 500)', null=True),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='reference_sequence',
            field=models.CharField(blank=True, help_text="Enter the reference sequence identifier (e.g., 'NM_007294.3' for BRCA1)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='somaticgenomicalterations',
            name='variant_type',
            field=models.CharField(blank=True, help_text="Specify the type of variant (e.g., 'Missense', 'Frameshift', 'Deletion', 'Insertion')", max_length=255, null=True),
        ),
    ]
