# Generated by Django 5.1.4 on 2024-12-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0080_alter_somaticgenomicalterations_allele_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when this treatment record was created (automatically set)'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='diagnosis',
            field=models.ForeignKey(help_text='Select the diagnosis that this treatment is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment',
            field=models.CharField(help_text='Enter the name or description of the treatment', max_length=255),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_end_date',
            field=models.DateField(blank=True, help_text='Enter the date when the treatment was completed (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_intent',
            field=models.ForeignKey(help_text="Select the intended purpose of this treatment (e.g., 'Curative', 'Palliative', 'Supportive Care')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuptreatmentintent'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_sequence',
            field=models.ForeignKey(help_text="Select the sequence of this treatment (e.g., 'First Line', 'Second Line', 'Adjuvant')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuptreatmentsequence'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_start_date',
            field=models.DateField(blank=True, help_text='Enter the date when the treatment was started (format: YYYY-MM-DD)', null=True),
        ),
    ]
