# Generated by Django 5.1.4 on 2024-12-29 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0081_alter_treatment_created_at_alter_treatment_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiotherapy',
            name='fractions_per_day',
            field=models.BigIntegerField(blank=True, help_text='Enter the number of treatment sessions (fractions) delivered per day', null=True),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_modality',
            field=models.CharField(blank=True, help_text="Enter the type of radiation used (e.g., 'External Beam', 'Brachytherapy', 'Proton Therapy')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_sequence',
            field=models.ForeignKey(help_text="Select the sequence of this radiotherapy in relation to other treatments (e.g., 'Primary', 'Boost', 'Concurrent')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuptreatmentsequence'),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_side',
            field=models.ForeignKey(help_text="Select which side of the body is being treated (e.g., 'Left', 'Right', 'Bilateral')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_site',
            field=models.ForeignKey(help_text='Select the anatomical location where the radiation is being delivered', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode'),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_technique',
            field=models.CharField(blank=True, help_text="Enter the specific technique used to deliver the radiation (e.g., 'IMRT', '3D-CRT', 'VMAT')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='radiotherapy_type',
            field=models.CharField(blank=True, help_text="Enter the type of radiotherapy treatment (e.g., 'Definitive', 'Palliative', 'Adjuvant')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='total_dose',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the total radiation dose delivered during the entire course of treatment (in Gray or specified units)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='total_fractions',
            field=models.BigIntegerField(blank=True, help_text='Enter the total number of treatment sessions (fractions) planned for the complete course of radiotherapy', null=True),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='treatment',
            field=models.ForeignKey(help_text='Select the treatment that this radiotherapy is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.treatment'),
        ),
        migrations.AlterField(
            model_name='radiotherapy',
            name='treatment_volume',
            field=models.TextField(blank=True, help_text='Enter a description of the area being treated, including any specific targeting information or boundaries', null=True),
        ),
    ]
