# Generated by Django 5.1.4 on 2024-12-29 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0082_alter_radiotherapy_fractions_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='nodal_assessment',
            field=models.BooleanField(blank=True, help_text='Indicate whether lymph nodes were assessed during surgery (check for Yes, leave unchecked for No)', null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='nodal_assessment_type',
            field=models.CharField(blank=True, help_text="If nodes were assessed, specify the type of assessment (e.g., 'Sentinel Node Biopsy', 'Axillary Dissection')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='reconstruction',
            field=models.BooleanField(blank=True, help_text='Indicate whether reconstructive surgery was performed (check for Yes, leave unchecked for No)', null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_date',
            field=models.DateField(blank=True, help_text='Enter the date when the surgery was performed (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_side',
            field=models.ForeignKey(blank=True, help_text="Select which side of the body the surgery was performed on (e.g., 'Left', 'Right', 'Bilateral')", null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuplaterality'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_site',
            field=models.ForeignKey(help_text='Select the anatomical location where the surgery was performed', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupfmacode'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_type',
            field=models.CharField(help_text="Enter the type of surgical procedure performed (e.g., 'Mastectomy', 'Lumpectomy', 'Excisional Biopsy')", max_length=255),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='treatment',
            field=models.ForeignKey(help_text='Select the treatment that this surgery is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.treatment'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='type_reconstruction',
            field=models.CharField(blank=True, help_text="If reconstruction was performed, specify the type (e.g., 'Implant-Based', 'Autologous Tissue', 'DIEP Flap')", max_length=255, null=True),
        ),
    ]
