# Generated by Django 5.1.4 on 2024-12-29 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0083_alter_surgery_nodal_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concomitantmedications',
            name='date_medication_end_date',
            field=models.DateField(blank=True, help_text='Enter the date when the medication was stopped, if applicable (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='concomitantmedications',
            name='date_medication_start_date',
            field=models.DateField(help_text='Enter the date when the medication was started (format: YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='concomitantmedications',
            name='medication_dose',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the prescribed dose of the medication (can be left blank if unknown)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='concomitantmedications',
            name='medication_name',
            field=models.CharField(help_text='Enter the name of the medication as it appears in the medical record', max_length=255),
        ),
        migrations.AlterField(
            model_name='concomitantmedications',
            name='medication_route',
            field=models.ForeignKey(help_text='Select how the medication was administered (e.g., oral, intravenous, etc.)', on_delete=django.db.models.deletion.CASCADE, to='client_app.lookupdrugroute'),
        ),
        migrations.AlterField(
            model_name='concomitantmedications',
            name='treatment',
            field=models.ForeignKey(help_text='Select the treatment that this medication is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.treatment'),
        ),
    ]
