# Generated by Django 5.1.4 on 2024-12-29 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0084_alter_concomitantmedications_date_medication_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupSystemicTherapyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemic_therapy_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Systemic Therapy Types',
                'db_table': 'lookup_systemic_therapy_type',
            },
        ),
        migrations.AlterField(
            model_name='systemictherapy',
            name='systemic_therapy_sequence',
            field=models.ForeignKey(help_text='Select the sequence for the systemic therapy', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookuptreatmentsequence'),
        ),
        migrations.AlterField(
            model_name='systemictherapy',
            name='treatment',
            field=models.ForeignKey(help_text='Select the treatment record for this systemic therapy', on_delete=django.db.models.deletion.CASCADE, to='client_app.treatment'),
        ),
        migrations.AlterField(
            model_name='systemictherapy',
            name='type_systemic_therapy',
            field=models.CharField(blank=True, help_text='Select the type of systemic therapy.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemictherapy',
            name='systemic_therapy_type',
            field=models.ForeignKey(blank=True, help_text='Select the type of systemic therapy.', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupsystemictherapytype'),
        ),
    ]
