# Generated by Django 5.1.4 on 2024-12-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0085_lookupsystemictherapytype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemictherapy',
            name='type_systemic_therapy',
        ),
    ]
