# Generated by Django 5.1.4 on 2024-12-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0086_remove_systemictherapy_type_systemic_therapy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy',
            field=models.ForeignKey(help_text='Select the systemic therapy treatment this schedule is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.systemictherapy'),
        ),
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_agent',
            field=models.ForeignKey(help_text='Select the specific medication or agent used in this treatment', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupsystemicagent'),
        ),
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_agent_end_date',
            field=models.DateField(blank=True, help_text='Enter the date when this specific medication was stopped (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_agent_route',
            field=models.ForeignKey(help_text='Select how the medication was administered (e.g., oral, intravenous, subcutaneous)', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupdrugroute'),
        ),
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_agent_start_date',
            field=models.DateField(blank=True, help_text='Enter the date when this specific medication was started (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_dose_administered',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the actual dose of medication that was administered (numerical value only)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_dose_planned',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the planned dose for this medication (numerical value only)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_dose_units',
            field=models.ForeignKey(help_text='Select the units used for the dose (e.g., mg, mg/m², mg/kg)', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupdoseunits'),
        ),
    ]
