# Generated by Django 5.1.4 on 2024-12-29 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0087_alter_systemictherapyschedule_systemic_therapy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseeffects',
            name='adverse_effect_end_date',
            field=models.DateField(blank=True, help_text='Enter the date when this adverse effect resolved, if applicable (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='adverseeffects',
            name='adverse_effect_grade',
            field=models.BigIntegerField(help_text='Enter the severity grade of the adverse effect (typically 1-5, where 5 is most severe)'),
        ),
        migrations.AlterField(
            model_name='adverseeffects',
            name='adverse_effect_start_date',
            field=models.DateField(blank=True, help_text='Enter the date when this adverse effect was first noticed (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='adverseeffects',
            name='adverse_effect_type',
            field=models.CharField(help_text='Enter the type or name of the adverse effect', max_length=255),
        ),
        migrations.AlterField(
            model_name='adverseeffects',
            name='ctcae_grade_lookup',
            field=models.ForeignKey(blank=True, help_text='Select the standardized CTCAE grade for this adverse effect', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupctcaegrade'),
        ),
        migrations.AlterField(
            model_name='adverseeffects',
            name='diagnosis',
            field=models.ForeignKey(help_text='Select the diagnosis this adverse effect is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='adverseeffects',
            name='treatment',
            field=models.ForeignKey(blank=True, help_text='Select the treatment that caused this adverse effect, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.treatment'),
        ),
    ]
