# Generated by Django 5.1.4 on 2024-12-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0088_alter_adverseeffects_adverse_effect_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreportedoutcome',
            name='domain',
            field=models.ForeignKey(help_text="Select the specific domain or category of the assessment (e.g., 'Physical Function', 'Emotional Well-being')", on_delete=django.db.models.deletion.CASCADE, to='client_app.prodomain'),
        ),
        migrations.AlterField(
            model_name='patientreportedoutcome',
            name='instrument',
            field=models.ForeignKey(help_text="Select the assessment instrument or questionnaire that was used (e.g., 'EORTC QLQ-C30', 'FACT-G')", on_delete=django.db.models.deletion.CASCADE, to='client_app.proinstrument'),
        ),
        migrations.AlterField(
            model_name='patientreportedoutcome',
            name='patient',
            field=models.ForeignKey(help_text='Select the patient who completed this patient-reported outcome assessment', on_delete=django.db.models.deletion.CASCADE, to='client_app.patient'),
        ),
        migrations.AlterField(
            model_name='patientreportedoutcome',
            name='pro_answer',
            field=models.TextField(blank=True, help_text="Enter the patient's response to this specific question", null=True),
        ),
        migrations.AlterField(
            model_name='patientreportedoutcome',
            name='pro_date',
            field=models.DateField(blank=True, help_text='Enter the date when this assessment was completed (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='patientreportedoutcome',
            name='pro_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the numerical score for this response, if applicable (e.g., on a scale of 0-10)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientreportedoutcome',
            name='question',
            field=models.ForeignKey(help_text='Select the specific question from the assessment that was answered', on_delete=django.db.models.deletion.CASCADE, to='client_app.proquestion'),
        ),
    ]
