# Generated by Django 5.1.4 on 2024-12-29 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0089_alter_patientreportedoutcome_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientoutcome',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Enter the date of death, if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='patientoutcome',
            name='patient_status',
            field=models.ForeignKey(help_text='Select the patients last known status', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupoutcome'),
        ),
        migrations.AlterField(
            model_name='patientoutcome',
            name='primary_cause_of_death',
            field=models.ForeignKey(blank=True, help_text='Select the primary cause of death, if applicable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_cause', to='client_app.lookupicdcode'),
        ),
        migrations.AlterField(
            model_name='patientoutcome',
            name='secondary_cause_of_death',
            field=models.ForeignKey(blank=True, help_text='Select the secondary cause of death, if applicable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_cause', to='client_app.lookupicdcode'),
        ),
        migrations.AlterField(
            model_name='patientoutcome',
            name='tertiary_cause_of_death',
            field=models.ForeignKey(blank=True, help_text='Select the tertiary cause of death, if applicable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tertiary_cause', to='client_app.lookupicdcode'),
        ),
    ]
