# Generated by Django 5.1.4 on 2024-12-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0090_alter_patientoutcome_date_of_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comorbidity',
            name='comorbidity_type',
            field=models.ForeignKey(help_text='Select the ICD code that best describes this comorbidity', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupicdcode'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='date_of_comorbidity_diagnosis',
            field=models.DateField(blank=True, help_text='Enter the date when this comorbidity was first diagnosed (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicate whether this comorbidity is currently active (check for Yes, uncheck for No)'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='patient',
            field=models.ForeignKey(help_text='Select the patient who has this comorbidity', on_delete=django.db.models.deletion.CASCADE, to='client_app.patient'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='diagnosis',
            field=models.ForeignKey(help_text='Select the diagnosis this staging information is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='m_stage_prefix',
            field=models.CharField(blank=True, help_text="Enter any prefix modifiers for the M stage (e.g., 'c' for clinical, 'p' for pathological)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='m_stage_suffix',
            field=models.CharField(blank=True, help_text="Enter any suffix modifiers for the M stage (e.g., 'a', 'b', 'c')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage',
            field=models.CharField(blank=True, help_text="Enter the N stage describing lymph node involvement (e.g., 'N0', 'N1', 'N2', 'N3')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage_prefix',
            field=models.CharField(blank=True, help_text="Enter any prefix modifiers for the N stage (e.g., 'c' for clinical, 'p' for pathological)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage_suffix',
            field=models.CharField(blank=True, help_text="Enter any suffix modifiers for the N stage (e.g., 'a', 'b', 'c')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='overall_stage',
            field=models.CharField(blank=True, help_text="Enter the overall stage grouping (e.g., 'Stage I', 'Stage II', 'Stage III', 'Stage IV')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='stage_type',
            field=models.CharField(blank=True, help_text="Enter the type of staging (e.g., 'Clinical', 'Pathological', 'Post-therapy')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='staging_system',
            field=models.ForeignKey(help_text="Select the staging system used (e.g., 'TNM 8th Edition', 'FIGO')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupstagingsystem'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage',
            field=models.CharField(blank=True, help_text="Enter the T stage describing the primary tumor (e.g., 'T1', 'T2', 'T3', 'T4')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage_prefix',
            field=models.CharField(blank=True, help_text="Enter any prefix modifiers for the T stage (e.g., 'c' for clinical, 'p' for pathological)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage_suffix',
            field=models.CharField(blank=True, help_text="Enter any suffix modifiers for the T stage (e.g., 'a', 'b', 'c')", max_length=255, null=True),
        ),
    ]
