# Generated by Django 5.1.4 on 2024-12-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0091_alter_comorbidity_comorbidity_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adverseeffects',
            options={'verbose_name_plural': 'Adverse Effects'},
        ),
        migrations.AlterModelOptions(
            name='comorbidity',
            options={'verbose_name_plural': 'Comorbidities'},
        ),
        migrations.AlterModelOptions(
            name='concomitantmedications',
            options={'verbose_name_plural': 'ConcomitantMedications'},
        ),
        migrations.AlterModelOptions(
            name='cytogenetics',
            options={'verbose_name_plural': 'Cytogenetics'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='lesion',
            options={'verbose_name_plural': 'Lesions'},
        ),
        migrations.AlterModelOptions(
            name='lesionresponse',
            options={'verbose_name_plural': 'Lesion Responses'},
        ),
        migrations.AlterModelOptions(
            name='pathology',
            options={'verbose_name_plural': 'Pathology'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='patientreportedoutcome',
            options={'verbose_name_plural': 'Patient Reported Outcomes'},
        ),
        migrations.AlterModelOptions(
            name='proinstrument',
            options={'verbose_name_plural': 'PRO Instruments'},
        ),
        migrations.AlterModelOptions(
            name='radiotherapy',
            options={'verbose_name_plural': 'Radiotherapy'},
        ),
        migrations.AlterModelOptions(
            name='somaticgenomicalterations',
            options={'verbose_name_plural': 'Somatic Genomic Alterations'},
        ),
        migrations.AlterModelOptions(
            name='stageinformation',
            options={'verbose_name_plural': 'Stage Informations'},
        ),
        migrations.AlterModelOptions(
            name='surgery',
            options={'verbose_name_plural': 'Surgery'},
        ),
        migrations.AlterModelOptions(
            name='systemictherapy',
            options={'verbose_name_plural': 'Systemic Therapies'},
        ),
        migrations.AlterModelOptions(
            name='systemictherapyschedule',
            options={'verbose_name_plural': 'Systematic Therapy Schedules'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name_plural': 'Treatments'},
        ),
    ]
