# Generated by Django 5.1.4 on 2024-12-30 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0092_alter_adverseeffects_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomstudy',
            name='patient',
            field=models.ForeignKey(help_text='Reference to the patient that this imaging study belongs to. When a patient record is deleted, all associated imaging studies will also be deleted.', on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='client_app.patient'),
        ),
    ]
