# Generated by Django 5.1.4 on 2024-12-30 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0093_alter_dicomstudy_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicomstudy',
            options={'verbose_name_plural': 'DICOM Studies'},
        ),
    ]
