# Generated by Django 5.1.4 on 2024-12-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0094_alter_dicomstudy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudy',
            name='study_instance_uid',
            field=models.CharField(blank=True, help_text='A unique identifier for this specific imaging study. This is like a serial number - no two imaging studies anywhere should have the same Study Instance UID. This helps prevent any confusion between different studies.', max_length=255, null=True),
        ),
    ]
