# Generated by Django 5.1.4 on 2024-12-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0095_dicomstudy_study_instance_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomstudy',
            name='frame_of_reference_uid',
            field=models.CharField(blank=True, help_text="A unique identifier that helps link different imaging series and studies together that were taken in the same physical space and time reference. Think of this like a coordinate system - images with the same frame of reference UID were taken in the same 'space and time'.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dicomstudy',
            name='sop_instance_uid',
            field=models.CharField(blank=True, help_text='A globally unique identifier for this specific imaging study. This is like a serial number - no two imaging studies anywhere should have the same SOP Instance UID. This helps prevent any confusion between different studies.', max_length=255, null=True, unique=True),
        ),
    ]
