# Generated by Django 5.1.4 on 2024-12-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0096_alter_dicomstudy_frame_of_reference_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseries',
            name='series_instance_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
