# Generated by Django 5.1.4 on 2024-12-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0097_dicomseries_series_instance_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudyfiles',
            name='frame_of_reference_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dicomstudyfiles',
            name='sop_instance_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
