# Generated by Django 5.1.4 on 2024-12-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0098_dicomstudyfiles_frame_of_reference_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomstudy',
            name='frame_of_reference_uid',
        ),
        migrations.RemoveField(
            model_name='dicomstudy',
            name='sop_instance_uid',
        ),
    ]
