# Generated by Django 5.1.4 on 2024-12-31 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0099_remove_dicomstudy_frame_of_reference_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomstudyfiles',
            name='frame_of_reference_uid',
        ),
    ]
