# Generated by Django 5.1.4 on 2024-12-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0100_remove_dicomstudyfiles_frame_of_reference_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcome',
            options={'verbose_name_plural': 'Outcomes'},
        ),
        migrations.AlterModelOptions(
            name='patientoutcome',
            options={'verbose_name_plural': 'Patient Outcomes'},
        ),
    ]
