# Generated by Django 5.1.4 on 2024-12-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0101_alter_outcome_options_alter_patientoutcome_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(help_text="The patient's date of birth in DD-MM-YYYY format."),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Non-Binary', 'Non Binary')], default='Female', help_text="The patient's gender", max_length=20),
        ),
    ]
