# Generated by Django 5.1.4 on 2024-12-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0102_alter_patient_date_of_birth_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientproject',
            options={'verbose_name': 'Associate Project to Patient', 'verbose_name_plural': 'Associate Projects to Patients'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(help_text="This should be your institution's medical record number or another consistent identifier used by your center.", max_length=255, unique=True),
        ),
    ]
