# Generated by Django 5.1.4 on 2024-12-31 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0103_alter_patientproject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientproject',
            options={'verbose_name': 'Project for Patient', 'verbose_name_plural': 'Projects for Patient'},
        ),
    ]
