# Generated by Django 5.1.4 on 2024-12-31 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0104_alter_patientproject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosisdicomstudy',
            options={'verbose_name': 'DICOM study for Diagnosis', 'verbose_name_plural': 'DICOM studies for Diagnosis'},
        ),
        migrations.AlterModelOptions(
            name='diagnosisproject',
            options={'verbose_name': 'Project for Diagnosis', 'verbose_name_plural': 'Projects for Diagnosis'},
        ),
        migrations.AlterModelOptions(
            name='dicomstudyproject',
            options={'verbose_name': 'Project for DICOM Study', 'verbose_name_plural': 'Projects for DICOM Study'},
        ),
        migrations.AlterModelOptions(
            name='lesiondicomstudy',
            options={'verbose_name': 'DICOM study for Lesion', 'verbose_name_plural': 'DICOM studies for Lesion'},
        ),
        migrations.AlterModelOptions(
            name='lesionresponsedicomstudy',
            options={'verbose_name': 'DICOM study for Lesion Response', 'verbose_name_plural': 'DICOM studies for Lesion Response'},
        ),
        migrations.AlterModelOptions(
            name='outcomedicomstudy',
            options={'verbose_name': 'DICOM Study for Outcome', 'verbose_name_plural': 'DICOM Studies for Outcome'},
        ),
        migrations.AlterModelOptions(
            name='radiotherapydicomstudy',
            options={'verbose_name': 'DICOM Study for Radiotherapy', 'verbose_name_plural': 'DICOM Studies for Radiotherapy'},
        ),
    ]
