# Generated by Django 5.1.4 on 2024-12-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0105_alter_diagnosisdicomstudy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chavi_center_id', models.CharField(default='Site ID', max_length=255)),
                ('center_name', models.CharField(default='Your Hospital', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
