# Generated by Django 5.1.4 on 2024-12-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0106_siteconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='center_address',
        ),
        migrations.RemoveField(
            model_name='center',
            name='center_city',
        ),
        migrations.RemoveField(
            model_name='center',
            name='center_country',
        ),
        migrations.RemoveField(
            model_name='center',
            name='center_state',
        ),
        migrations.RemoveField(
            model_name='center',
            name='created_at',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='center_address',
            field=models.TextField(blank=True, help_text="The complete street address of the medical center. Should include building number, street name, and any additional address details like suite or floor number. Example: '1216 Second Street SW'. This field is optional.", null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='center_city',
            field=models.TextField(blank=True, help_text="The city where the medical center is located. Should be written in full without abbreviations. Example: 'Rochester' or 'New York City'. This field is optional.", null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='center_country',
            field=models.TextField(blank=True, help_text="The country where the medical center is located. Use the full country name, not abbreviations. Example: 'United States' or 'Canada'. This field is optional.", null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='center_state',
            field=models.TextField(blank=True, help_text="The state or province where the medical center is located. For US locations, use the full state name or standard two-letter abbreviation. For international locations, use appropriate regional divisions. Example: 'Minnesota' or 'MN'. This field is optional.", null=True),
        ),
    ]
