# Generated by Django 5.1.4 on 2024-12-31 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0107_remove_center_center_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='center',
        ),
    ]
