# Generated by Django 5.1.4 on 2024-12-31 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0108_remove_patient_center'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Center',
        ),
    ]
