# Generated by Django 5.1.4 on 2024-12-31 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0109_delete_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center', to='client_app.siteconfiguration'),
        ),
    ]
