# Generated by Django 5.1.4 on 2025-01-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0111_alter_patient_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemictherapy',
            name='systemic_therapy_regimen',
            field=models.CharField(blank=True, help_text='Please enter the name of the systemic therapy regimen if there is a multi-drug or named regimen being used.', max_length=255, null=True),
        ),
    ]
