# Generated by Django 5.1.4 on 2025-01-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0112_systemictherapy_systemic_therapy_regimen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemictherapyschedule',
            options={'verbose_name_plural': 'Systematic Therapy Administration Schedules'},
        ),
        migrations.AlterField(
            model_name='systemictherapyschedule',
            name='systemic_therapy_agent_end_date',
            field=models.DateField(blank=True, help_text='Enter the date when this specific medication was stopped (format: YYYY-MM-DD).', null=True),
        ),
    ]
