# Generated by Django 5.1.4 on 2025-01-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0113_alter_systemictherapyschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiotherapy',
            options={'verbose_name': 'Radiotherapy Course', 'verbose_name_plural': 'Radiotherapy Courses'},
        ),
    ]
