# Generated by Django 5.1.4 on 2025-01-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0114_alter_radiotherapy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemictherapy',
            options={'verbose_name': 'Systemic Therapy Course', 'verbose_name_plural': 'Systemic Therapy Courses'},
        ),
    ]
