# Generated by Django 5.1.4 on 2025-01-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0115_alter_systemictherapy_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_intent',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_sequence',
        ),
    ]
