# Generated by Django 5.1.4 on 2025-01-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0116_remove_treatment_treatment_intent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_end_date',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_start_date',
        ),
        migrations.AddField(
            model_name='radiotherapy',
            name='radiotherapy_end_date',
            field=models.DateField(blank=True, help_text='Enter the date when the treatment was completed (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='radiotherapy',
            name='radiotherapy_start_date',
            field=models.DateField(blank=True, help_text='Enter the date when the treatment was started (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='systemictherapy',
            name='cycles_delivered',
            field=models.BigIntegerField(blank=True, help_text='Total Number of Cycles delivered if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='systemictherapy',
            name='systemic_therapy_end_date',
            field=models.DateField(blank=True, help_text='Enter the date when the treatment was completed (format: YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='systemictherapy',
            name='systemic_therapy_start_date',
            field=models.DateField(blank=True, help_text='Enter the date when the treatment was started (format: YYYY-MM-DD)', null=True),
        ),
    ]
