# Generated by Django 5.1.4 on 2025-01-01 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0117_remove_treatment_treatment_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiotherapy',
            name='treatment',
        ),
        migrations.AddField(
            model_name='radiotherapy',
            name='diagnosis',
            field=models.ForeignKey(help_text='Select the diagnosis that this treatment is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
    ]
