# Generated by Django 5.1.4 on 2025-01-01 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0118_remove_radiotherapy_treatment_radiotherapy_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiotherapy',
            name='diagnosis',
            field=models.ForeignKey(help_text='Select the diagnosis that this treatment is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.diagnosis'),
        ),
    ]
