# Generated by Django 5.1.4 on 2025-01-01 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0125_alter_systemictherapy_diagnosis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcome',
            options={'verbose_name': 'Outcome for Cancer', 'verbose_name_plural': 'Outcomes for Cancer'},
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date_outcome_assessed',
            field=models.DateField(blank=True, help_text='Date this Outcome was assessed or documented or confirmed.', null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='outcome_type',
            field=models.ForeignKey(help_text='Select the Type of Outcome. If you wish to add another outcome then please create another instance of the form.', on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupoutcometype'),
        ),
    ]
