# Generated by Django 5.1.4 on 2025-01-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0126_alter_outcome_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="The patient's date of birth in DD-MM-YYYY format.", null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Non-Binary', 'Non Binary')], default='Female', help_text="The patient's gender", max_length=20, null=True),
        ),
    ]
