# Generated by Django 5.1.4 on 2025-01-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0127_alter_patient_date_of_birth_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemictherapyschedule',
            options={'verbose_name': 'Medication Detail', 'verbose_name_plural': 'Medication Details'},
        ),
    ]
