# Generated by Django 5.1.4 on 2025-01-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0128_alter_systemictherapyschedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageinformation',
            name='m_stage',
            field=models.CharField(blank=True, help_text="Enter the M stage describing distant metastasis (e.g., 'M0', 'M1', 'M1a', 'M1b')", max_length=255, null=True),
        ),
    ]
