# Generated by Django 5.1.4 on 2025-01-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0129_stageinformation_m_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathology',
            old_name='count_lymph_node_isolated_tumor_cells',
            new_name='count_lymph_nodes_isolated_tumor_cells',
        ),
        migrations.AddField(
            model_name='pathology',
            name='lymph_nodes_removed',
            field=models.BooleanField(blank=True, help_text='Whether lymph nodes were removed in the specimen', null=True),
        ),
    ]
