# Generated by Django 5.1.4 on 2025-01-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0130_rename_count_lymph_node_isolated_tumor_cells_pathology_count_lymph_nodes_isolated_tumor_cells_and_mo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathology',
            old_name='count_lymph_nodes_in_specimen',
            new_name='lymph_nodes_in_specimen',
        ),
        migrations.RenameField(
            model_name='pathology',
            old_name='count_lymph_nodes_isolated_tumor_cells',
            new_name='number_of_nodes_with_isolated_tumor_cells',
        ),
        migrations.RenameField(
            model_name='pathology',
            old_name='count_lymph_nodes_macroscopic',
            new_name='number_of_nodes_with_macrometastases',
        ),
        migrations.RenameField(
            model_name='pathology',
            old_name='count_lymph_nodes_micrometastasis',
            new_name='number_of_nodes_with_micrometastases',
        ),
        migrations.RenameField(
            model_name='pathology',
            old_name='count_lymph_nodes_uninvolved',
            new_name='number_of_uninvolved_nodes',
        ),
    ]
