# Generated by Django 5.1.4 on 2025-01-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0131_rename_count_lymph_nodes_in_specimen_pathology_lymph_nodes_in_specimen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathology',
            name='greatest_tumor_size',
        ),
    ]
