# Generated by Django 5.1.4 on 2025-01-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0132_remove_pathology_greatest_tumor_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverseeffects',
            name='treatment',
        ),
    ]
