# Generated by Django 5.1.4 on 2025-01-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0133_remove_adverseeffects_treatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': 'Other Treatment', 'verbose_name_plural': 'Other Treatments'},
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_end_date',
            field=models.DateField(blank=True, help_text='End date of Treatment', null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_start_date',
            field=models.DateField(blank=True, help_text='Start date of Treatment', null=True),
        ),
        migrations.AlterModelTable(
            name='treatment',
            table='other_treatment',
        ),
    ]
