# Generated by Django 5.1.4 on 2025-01-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0134_alter_treatment_options_treatment_treatment_end_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treatment',
            new_name='OtherTreatment',
        ),
    ]
