# Generated by Django 5.1.4 on 2025-01-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0135_rename_treatment_othertreatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcome',
            options={'verbose_name': 'Cancer Outcome', 'verbose_name_plural': 'Cancer Outcomes'},
        ),
    ]
