# Generated by Django 5.1.4 on 2025-01-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0136_alter_outcome_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="The patient's date of birth in YYYY-MM-DD format.", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, help_text="The date when this project was or is expected to be completed. Format: YYYY-MM-DD. Example: '31-12-2024'", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text="The date when this project officially began. Format: YYYY-MM-DD. Example: '01-01-2023'", null=True),
        ),
    ]
