# Generated by Django 5.1.4 on 2025-01-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0137_alter_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseeffects',
            name='adverse_effect_grade',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the severity grade of the adverse effect (typically 1-5, where 5 is most severe)', null=True),
        ),
    ]
