# Generated by Django 5.1.4 on 2025-01-01 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0138_alter_adverseeffects_adverse_effect_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='concomitantmedications',
            name='medication_dose_units',
            field=models.ForeignKey(blank=True, help_text='Select the units for the medication dose (e.g., mg, mL, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupdoseunits'),
        ),
    ]
