# Generated by Django 5.1.4 on 2025-01-01 13:04

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0139_concomitantmedications_medication_dose_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageinformation',
            name='t_stage_composite',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('t_stage_prefix', 't_stage', 't_stage_suffix'), help_text='The composite T stage, including any prefixes or suffixes', null=True, output_field=models.CharField(max_length=255)),
        ),
    ]
