# Generated by Django 5.1.4 on 2025-01-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0140_stageinformation_t_stage_composite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageinformation',
            name='m_stage_prefix',
            field=models.CharField(blank=True, choices=[('yp', 'Yp'), ('p', 'P'), ('c', 'C'), ('r', 'R')], help_text="Enter any prefix modifiers for the M stage (e.g., 'c' for clinical, 'p' for pathological)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage_prefix',
            field=models.CharField(blank=True, choices=[('yp', 'Yp'), ('p', 'P'), ('c', 'C'), ('r', 'R')], help_text="Enter any prefix modifiers for the N stage (e.g., 'c' for clinical, 'p' for pathological)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage_prefix',
            field=models.CharField(blank=True, choices=[('yp', 'Yp'), ('p', 'P'), ('c', 'C'), ('r', 'R')], help_text="Enter any prefix modifiers for the T stage (e.g., 'c' for clinical, 'p' for pathological)", max_length=255, null=True),
        ),
    ]
