# Generated by Django 5.1.4 on 2025-01-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0141_alter_stageinformation_m_stage_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageinformation',
            name='m_stage_suffix',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], help_text="Enter any suffix modifiers for the M stage (e.g., 'a', 'b', 'c')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage_suffix',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], help_text="Enter any suffix modifiers for the N stage (e.g., 'a', 'b', 'c')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage_suffix',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], help_text="Enter any suffix modifiers for the T stage (e.g., 'a', 'b', 'c')", max_length=255, null=True),
        ),
    ]
