# Generated by Django 5.1.4 on 2025-01-01 13:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0142_alter_stageinformation_m_stage_suffix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageinformation',
            name='m_stage_composite',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('m_stage_prefix', 'm_stage', 'm_stage_suffix'), help_text='The composite M stage, including any prefixes or suffixes', null=True, output_field=models.CharField(max_length=255)),
        ),
        migrations.AddField(
            model_name='stageinformation',
            name='n_stage_composite',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('n_stage_prefix', 'n_stage', 'n_stage_suffix'), help_text='The composite N stage, including any prefixes or suffixes', null=True, output_field=models.CharField(max_length=255)),
        ),
    ]
