# Generated by Django 5.1.4 on 2025-01-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0143_stageinformation_m_stage_composite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageinformation',
            name='m_stage',
            field=models.CharField(blank=True, choices=[('Mx', 'Mx'), ('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2')], help_text="Enter the M stage describing distant metastasis (e.g., 'M0', 'M1', 'M1a', 'M1b')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage',
            field=models.CharField(blank=True, choices=[('Nx', 'Nx'), ('N0', 'N0'), ('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3')], help_text="Enter the N stage describing lymph node involvement (e.g., 'N0', 'N1', 'N2', 'N3')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage',
            field=models.CharField(blank=True, choices=[('Tx', 'Tx'), ('Tis', 'Tis'), ('T0', 'T0'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4')], help_text="Enter the T stage describing the primary tumor (e.g., 'T1', 'T2', 'T3', 'T4')", max_length=255, null=True),
        ),
    ]
