# Generated by Django 5.1.4 on 2025-01-01 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0144_alter_stageinformation_m_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupAJCCStagePrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage_prefix',
            field=models.ForeignKey(blank=True, help_text="Enter any prefix modifiers for the T stage (e.g., 'c' for clinical, 'p' for pathological)", null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupajccstageprefix'),
        ),
    ]
