# Generated by Django 5.1.4 on 2025-01-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0145_lookupajccstageprefix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupAJCCMStageDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LookupAJCCNStageDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LookupAJCCStageSuffix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LookupAJCCTStageDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='m_stage_prefix',
            field=models.ForeignKey(blank=True, help_text="Select any prefix modifiers for the M stage (e.g., 'c' for clinical, 'p' for pathological)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m_stage_prefix', to='client_app.lookupajccstageprefix'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage_prefix',
            field=models.ForeignKey(blank=True, help_text="Select any prefix modifiers for the N stage (e.g., 'c' for clinical, 'p' for pathological)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='n_stage_prefix', to='client_app.lookupajccstageprefix'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage_prefix',
            field=models.ForeignKey(blank=True, help_text="Select the prefix modifiers for the T stage (e.g., 'c' for clinical, 'p' for pathological)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_stage_prefix', to='client_app.lookupajccstageprefix'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='m_stage',
            field=models.ForeignKey(blank=True, help_text="Enter the M stage describing distant metastasis (e.g., 'M0', 'M1', 'M1a', 'M1b')", null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupajccmstagedescriptor'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage',
            field=models.ForeignKey(blank=True, help_text="Enter the N stage describing lymph node involvement (e.g., 'N0', 'N1', 'N2', 'N3')", null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupajccnstagedescriptor'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='m_stage_suffix',
            field=models.ForeignKey(blank=True, help_text="Enter any suffix modifiers for the M stage (e.g., 'a', 'b', 'c')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m_stage_suffix', to='client_app.lookupajccstagesuffix'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage_suffix',
            field=models.ForeignKey(blank=True, help_text="Select any suffix modifiers for the N stage (e.g., 'a', 'b', 'c')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='n_stage_suffix', to='client_app.lookupajccstagesuffix'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage_suffix',
            field=models.ForeignKey(blank=True, help_text="Enter any suffix modifiers for the T stage (e.g., 'a', 'b', 'c')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_stage_suffix', to='client_app.lookupajccstagesuffix'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage',
            field=models.ForeignKey(blank=True, help_text="Select the T stage describing the primary tumor (e.g., 'T1', 'T2', 'T3', 'T4')", null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupajcctstagedescriptor'),
        ),
    ]
