# Generated by Django 5.1.4 on 2025-01-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0146_lookupajccmstagedescriptor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupAJCCStageDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2)),
                ('stage_type', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='m_stage',
            field=models.ForeignKey(blank=True, help_text="Enter the M stage describing distant metastasis (e.g., 'M0', 'M1', 'M1a', 'M1b')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m_stage', to='client_app.lookupajccstagedescriptor'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage',
            field=models.ForeignKey(blank=True, help_text="Enter the N stage describing lymph node involvement (e.g., 'N0', 'N1', 'N2', 'N3')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='n_stage', to='client_app.lookupajccstagedescriptor'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage',
            field=models.ForeignKey(blank=True, help_text="Select the T stage describing the primary tumor (e.g., 'T1', 'T2', 'T3', 'T4')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_stage', to='client_app.lookupajccstagedescriptor'),
        ),
        migrations.DeleteModel(
            name='LookupAJCCMStageDescriptor',
        ),
        migrations.DeleteModel(
            name='LookupAJCCNStageDescriptor',
        ),
        migrations.DeleteModel(
            name='LookupAJCCTStageDescriptor',
        ),
    ]
