# Generated by Django 5.1.4 on 2025-01-02 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_squashed_0147_lookupajccstagedescriptor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupRadiotherapyVolumeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiotherapy_volume_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Volume Types',
                'db_table': 'lookup_radiotherapy_volume_type',
            },
        ),
        migrations.AddField(
            model_name='radiotherapy',
            name='radiation_dose_units',
            field=models.ForeignKey(blank=True, help_text="Select the units used to measure the radiation dose (e.g., 'Gy', 'cGy')", null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupunits'),
        ),
        migrations.CreateModel(
            name='RadiotherapyVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_name', models.CharField(blank=True, help_text='Enter a name or description for this volume', max_length=255, null=True)),
                ('volume_dose_prescribed', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the prescribed dose for this volume in Gray (Gy)', max_digits=10, null=True)),
                ('volume_fractions', models.PositiveIntegerField(blank=True, help_text='Enter the number of fractions for this volume', null=True)),
                ('volume_radiotherapy_start_date', models.DateField(blank=True, help_text='Enter the start date for this volume (format: YYYY-MM-DD)', null=True)),
                ('volume_radiotherapy_end_date', models.DateField(blank=True, help_text='Enter the end date for this volume (format: YYYY-MM-DD)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radiation_dose_units', models.ForeignKey(blank=True, help_text="Select the units used to measure the radiation dose (e.g., 'Gy', 'cGy')", null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupunits')),
                ('radiotherapy', models.ForeignKey(help_text='Select the radiotherapy course that this volume is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.radiotherapy')),
                ('volume_type', models.ForeignKey(blank=True, help_text='Select the type of volume (e.g., PTV, CTV, OAR)', null=True, on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupradiotherapyvolumetype')),
            ],
        ),
    ]
