# Generated by Django 5.1.4 on 2025-01-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0148_lookupradiotherapyvolumetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiotherapy',
            name='treatment_volume',
        ),
        migrations.AddField(
            model_name='radiotherapy',
            name='radiotherapy_machine',
            field=models.CharField(blank=True, help_text='Enter the name or model of the radiation therapy machine used', max_length=255, null=True),
        ),
    ]
