# Generated by Django 5.1.4 on 2025-01-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0149_remove_radiotherapy_treatment_volume_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiotherapyvolume',
            options={'verbose_name_plural': 'Radiotherapy Volumes'},
        ),
        migrations.AlterModelTable(
            name='radiotherapyvolume',
            table='radiotherapy_volume',
        ),
    ]
