# Generated by Django 5.1.4 on 2025-01-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0150_alter_radiotherapyvolume_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiotherapy',
            name='fractions_per_day',
            field=models.BigIntegerField(blank=True, default=1, help_text='Enter the number of treatment sessions (fractions) delivered per day', null=True),
        ),
    ]
