# Generated by Django 5.1.4 on 2025-01-02 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0151_alter_radiotherapy_fractions_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiotherapyDoseVolumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_name', models.CharField(help_text='Enter a name for this dose volume data', max_length=255)),
                ('absolute_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the absolute volume in cubic centimeters (cc)', max_digits=10, null=True)),
                ('relative_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the relative volume as a percentage (%)', max_digits=5, null=True)),
                ('absolute_dose', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the absolute dose in Gray (Gy) or cGy', max_digits=10, null=True)),
                ('relative_dose', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the relative dose as a percentage (%)', max_digits=5, null=True)),
                ('volume_dose_prescribed', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the dose prescribed to this volume in Gray (Gy) or cGy', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('radiation_dose_units', models.ForeignKey(blank=True, help_text="Select the units for the dose (e.g., 'Gy', 'cGy', '%')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiation_dose_units', to='client_app.lookupunits')),
                ('radiotherapy', models.ForeignKey(help_text='Select the radiotherapy session that this dose volume data is associated with', on_delete=django.db.models.deletion.CASCADE, to='client_app.radiotherapy')),
                ('volume_type', models.ForeignKey(help_text="Select the type of volume (e.g., 'CTV', 'PTV')", on_delete=django.db.models.deletion.PROTECT, to='client_app.lookupradiotherapyvolumetype')),
                ('volume_units', models.ForeignKey(blank=True, help_text="Select the units for the volume (e.g., 'cc', '%')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volume_units', to='client_app.lookupunits')),
            ],
            options={
                'verbose_name': 'Radiotherapy Dose Volume',
                'verbose_name_plural': 'Radiotherapy Dose Volumes',
                'db_table': 'radiotherapy_dose_volumes',
            },
        ),
    ]
