# Generated by Django 5.1.4 on 2025-01-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0152_radiotherapydosevolumedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiotherapydicomstudy',
            options={'verbose_name': 'DICOM Study for Radiotherapy Course', 'verbose_name_plural': 'DICOM Studies for Radiotherapy Courses'},
        ),
        migrations.CreateModel(
            name='SystemicTherapyDICOMStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudy')),
                ('systemic_therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.systemictherapy')),
            ],
            options={
                'verbose_name': 'DICOM Study for Systemic Therapy Course',
                'verbose_name_plural': 'DICOM Studies for Systemic Therapy Courses',
                'constraints': [models.UniqueConstraint(fields=('systemic_therapy', 'dicom_study'), name='unique_chemotherapy_dicom_study')],
            },
        ),
    ]
