# Generated by Django 5.1.4 on 2025-01-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0153_alter_radiotherapydicomstudy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryDICOMStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.dicomstudy')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.surgery')),
            ],
            options={
                'verbose_name': 'DICOM Study for Surgery',
                'verbose_name_plural': 'DICOM Studies for Surgery',
                'constraints': [models.UniqueConstraint(fields=('surgery', 'dicom_study'), name='unique_surgery_dicom_study')],
            },
        ),
    ]
