# Generated by Django 5.1.4 on 2025-01-03 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0154_surgerydicomstudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupAJCCMStageDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupAJCCNStageDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupAJCCTStageDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stageinformation',
            name='m_stage_composite',
        ),
        migrations.RemoveField(
            model_name='stageinformation',
            name='n_stage_composite',
        ),
        migrations.RemoveField(
            model_name='stageinformation',
            name='t_stage_composite',
        ),
        migrations.AlterField(
            model_name='lookupajccstageprefix',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lookupajccstagesuffix',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='m_stage',
            field=models.ForeignKey(blank=True, help_text="Enter the M stage describing distant metastasis (e.g., 'M0', 'M1', 'M1a', 'M1b')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='m_stage', to='client_app.lookupajccmstagedescriptor'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='n_stage',
            field=models.ForeignKey(blank=True, help_text="Enter the N stage describing lymph node involvement (e.g., 'N0', 'N1', 'N2', 'N3')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='n_stage', to='client_app.lookupajccnstagedescriptor'),
        ),
        migrations.AlterField(
            model_name='stageinformation',
            name='t_stage',
            field=models.ForeignKey(blank=True, help_text="Select the T stage describing the primary tumor (e.g., 'T1', 'T2', 'T3', 'T4')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='t_stage', to='client_app.lookupajcctstagedescriptor'),
        ),
        migrations.DeleteModel(
            name='LookupAJCCStageDescriptor',
        ),
    ]
