# Generated by Django 5.1.4 on 2025-01-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0155_lookupajccmstagedescriptor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The DICOM file associated with the patient. This file should contain the medical imaging data for the patient.', upload_to='patient_dicom_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_dicom_files', to='client_app.patient')),
            ],
        ),
    ]
